### ISSUE TITLE
(request)thefuck command not found (Help

### ISSUE THREAD

**Issue by bapji** [nvbn/thefuck#1019]
![Screenshot_20191207-052216](https://user-images.githubusercontent.com/58431159/70364237-ae411400-18b1-11ea-80f4-591be84827c3.jpg)
I' m termux user with root please help

**Comment by BrutalBirdie** [comment]
The heading is very misleading.
 You want to use `thefuck` with Termux.
Termux pkg does not include `thefuck`.

I think you need to install it manually.

**Comment by bapji** [comment]
Thanks
