### ISSUE TITLE
Git checkout should provide multiple corrections

### ISSUE THREAD

**Issue by davidhart82** [nvbn/thefuck#1021]
When correcting git checkout, the default is to use the 'closest branch'.  We have a lot of branches with similar names, but quite often, what I actually meant to do was supply the '-b' flag.

Can the git checkout rule be updated to return all of the possible options, rather than trying to guess, based on some arbitrary priority?

**Comment by davidhart82** [comment]
I'll probably have a go at fixing this; though I seem to remember having issues with rules returning lists of corrections.

**Comment by scorphus** [comment]
The `git_checkout`] rule sometimes does that:

https://github.com/nvbn/thefuck/blob/d10fc80fa5da5724ec945aec12720ef41be9551f/thefuck/rules/git_checkout.py#L31-L43

I guess it would be a nice improvement having it returning all possible commands in a list.

And there are quite a few examples in `thefuck/rules/`. To mention a couple, arbitrarily:

* `az_cli`:
https://github.com/nvbn/thefuck/blob/d10fc80fa5da5724ec945aec12720ef41be9551f/thefuck/rules/az_cli.py#L14-L17
* `pacman`:
https://github.com/nvbn/thefuck/blob/d10fc80fa5da5724ec945aec12720ef41be9551f/thefuck/rules/pacman.py#L9-L14

**Comment by davidhart82** [comment]
https://github.com/nvbn/thefuck/pull/1022
