### ISSUE TITLE
Add git lfs support

### ISSUE THREAD

**Issue by Shayan-To** [nvbn/thefuck#1030]
Add support for correcting commands like `git lfs checkuot` to `git lfs checkout`.

From their man pages, it has these commands:

- env
- checkout
- clone
- fetch
- fsck
- install
- lock
- locks
- logs
- ls-files
- migrate
- prune
- pull
- push
- status
- track
- uninstall
- unlock
- untrack
- update
- version
- clean
- pointer
- pre-push
- filter-process
- smudge

Link: https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs.1.ronn
(Note: git lfs clone was recently removed.)

**Comment by cjmartian** [comment]
@scorphus this can be closed

**Comment by scorphus** [comment]
Thanks for your contributions, @cjmartian! 🙌
