### ISSUE TITLE
After installing thefuck terminal starts blank and takes quite a few seconds to show "username@devicename ~/Folder$". Purging thefuck fixes the delay issue, but everytime I open terminal (konsole & xterm) it shows "Command 'thefuck' not found, but can be installed with:  sudo apt install thefuck". 

### ISSUE THREAD

**Issue by mmzaman2007** [nvbn/thefuck#1041]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.11 using Python 2.7.17

Your system (Debian 7, ArchLinux, Windows, etc.):

    KDE neon

How to reproduce the bug:

    FILL THIS IN

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    FILL THIS IN

If the bug only appears with a specific application, the output of that application and its version:

    Konsole 19.12.2, xterm

Anything else you think is relevant:

    FILL THIS IN

**Comment by sukurcf** [comment]
Please update **FILL THIS IN** section

**Comment by scorphus** [comment]
@mmzaman2007 3.11 is quite old. Please update and reopen if still an issue. Please add as much information as you can (i.e. please fill the spaces where it says “fill this in” – a.k.a. please help us help you)
