### ISSUE TITLE
test fail: AttributeError: 'Function' object has no attribute 'get_marker'

### ISSUE THREAD

**Issue by jinwuxia** [nvbn/thefuck#1055]
in version 3.28, after run "pytest",  almost all tests failed.
================ 15 skipped, 3 warnings, 1571 errors in 18.27s ================

All these failures seem to be caused by "AttributeError: 'Function' object has no attribute 'get_marker'"

**Comment by scorphus** [comment]
This issue [was solved a few months ago](https://github.com/pytest-dev/pytest-cov/issues/252) on pytest-cov repository. Please, make sure you have the latest version of both pytest and pytest-cov by issuing `pip install -U pytest pytest-cov `. Then, check the versions with `pip list | grep -i pytest`. Remember to have a virtual environment activated.

Closing this for now. Feel free to reopen in case it's still an issue.
