### ISSUE TITLE
Enable the use of custom keybindings

### ISSUE THREAD

**Issue by bearcatsandor** [nvbn/thefuck#1058]
The Fuck 3.28 using Python 3.6.10 and ZSH 5.8 

system: 5.5.0-gentoo #1 SMP Wed Jan 29 23:29:22 MST 2020 x86_64 AMD Ryzen 7 2700 Eight-Core Processor AuthenticAMD GNU/Linux

As a vim user, and someone who rarely uses the arrow keys, it would be great to be able to assign the up/down functionality to j/k.

**Comment by cjoshmartin** [comment]
I just ran `fuck`, and it already has support for this feature

**Comment by bearcatsandor** [comment]
Ugh. I donno why i missed that. Probably because I'm in a neovim terminal and there was a delay of a second due to my keybindings

Thank you!
