### ISSUE TITLE
Add no swearing mode

### ISSUE THREAD

**Issue by KevinSnyderCodes** [nvbn/thefuck#1070]
There should be a way to set up an alias that uses PG language. Something like `frick` or `frig`. And maybe remove any swear words from stdout while we're at it.

After all, you wouldn't run that command on your mother's computer, would you?

**Comment by Rom1deTroyes** [comment]
I think your request will lead to a #401 "Unauthorized response", like issues #866 and #801 :-$

# tl;dr
You can use any thing you want for the alias with :
```
eval "$(thefuck --alias frig)"
```

**Comment by scorphus** [comment]
Please feel totally free to fork and rename the project replacing as much of the content as you see fit 🙂The license is permissive enough, just adhere to it.
