### ISSUE TITLE
pyenv is supported, rbenv, nodenv and goenv not supported

### ISSUE THREAD

**Issue by BenjaminLiuPenrose** [nvbn/thefuck#1074]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

 The Fuck 3.30 using Python 3.7.4 and Bash 4.4.19(2)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

   Windows 10

How to reproduce the bug:

    rbenv install
    nodenv install
    goenv install

Anything else you think is relevant:

    Maybe a more modification on pyenv support to make it extendable.

**Comment by gkodosis** [comment]
I can try to make a unique rule handling env installations  :v:
