### ISSUE TITLE
I want fuck for git push

### ISSUE THREAD

**Issue by shinriyo** [nvbn/thefuck#1085]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.28 using Python 3.7.2 and Fish Shell 3.0.2

Your system (Debian 7, ArchLinux, Windows, etc.):

    macOS 10.15.4

How to reproduce the bug:

    not bug. it is feature

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```
> git push
fatal: The current branch feature/something has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature/something
```

If the bug only appears with a specific application, the output of that application and its version:

    same

Anything else you think is relevant:

```
> git push
fatal: The current branch feature/something has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature/something

> fuck
git push --set-upstream origin feature/something
```

**Comment by scorphus** [comment]
Already covered by the `git_push` rule. [RTM](https://github.com/nvbn/thefuck#how-it-works):
> `git_push` – adds `--set-upstream origin $branch` to previous failed `git push`;
