### ISSUE TITLE
Missing dependency on python3-distutils

### ISSUE THREAD

**Issue by NatoBoram** [nvbn/thefuck#1089]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

> The Fuck 3.29 using Python 3.8.2 and Bash 5.0.16(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

> Ubuntu 20.04 LTS x86_64 

How to reproduce the bug:

> 1. `sudo apt install thefuck`
> 2. Add `eval $(thefuck --alias)` to `~/.bash_aliases`

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

> ```log
> Traceback (most recent call last):
>   File "/usr/bin/thefuck", line 9, in <module>
>     from thefuck.entrypoints.main import main
>   File "/usr/share/thefuck/thefuck/entrypoints/main.py", line 2, in <module>
>     from ..system import init_output
>   File "/usr/share/thefuck/thefuck/system/__init__.py", line 7, in <module>
>     from .unix import *  # noqa: F401,F403
>   File "/usr/share/thefuck/thefuck/system/unix.py", line 6, in <module>
>     from distutils.spawn import find_executable
> ModuleNotFoundError: No module named 'distutils.spawn'
> ```

If the bug only appears with a specific application, the output of that application and its version:

> ```yaml
> Package: thefuck
> Version: 3.29-0.1
> Priority: optional
> Section: universe/python
> Origin: Ubuntu
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Original-Maintainer: Alessio Treglia <alessio@debian.org>
> Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> Installed-Size: 316 kB
> Depends: python3-colorama, python3-decorator, python3-psutil, python3-pyte, python3-six, python3:any, python3-pkg-resources
> Homepage: https://github.com/nvbn/thefuck
> Download-Size: 57.4 kB
> APT-Manual-Installed: yes
> APT-Sources: http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
> Description: spelling corrector of console commands
>  The Fuck attempts to fix user's command line mistakes, by
>  composing new commands applying a series of matching rules.
>  It supports various shells, such as bash, fish, tcsh, and
>  zsh.
>  .
>  The 'sudo' matching rule has been disabled for users' safety.
> ```

Anything else you think is relevant:

**Comment by scorphus** [comment]
This is a bug on the Ubuntu package. Please watch https://bugs.launchpad.net/ubuntu/+source/thefuck/+bug/1875178 for progress and further discussion.

**Comment by scorphus** [comment]
[That bug description](https://bugs.launchpad.net/ubuntu/+source/thefuck/+bug/1875178) offers a temporary solution:

`apt install python3-distutils`

**Comment by nwgat** [comment]
just ran into this on Ubuntu 24.10
`apt install python3-distutils` dont work
