### ISSUE TITLE
Rename the project to thefudge

### ISSUE THREAD

**Issue by blacklistisnotracist** [nvbn/thefuck#1105]
the"fuck" can be offensive for some people. We might need to rename it something like `thefudge` before someone gets fucked and goes viral on the social media

**Comment by Rom1deTroyes** [comment]
Please, can you can read #1070 #401 #866 and #801 ... And surely close this one ? :-)

**Comment by blacklistisnotracist** [comment]
Cool cool. alias works for everyone!
