### ISSUE TITLE
Always have to run the command and "fuck" twice

### ISSUE THREAD

**Issue by turfaa** [nvbn/thefuck#1108]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.30 using Python 3.8.3 and Fish Shell 3.0.2

Your system (Debian 7, ArchLinux, Windows, etc.):

    MacOS Catalina (10.15.5)

How to reproduce the bug:

    Run a typo command, then run "fuck"
![image](https://user-images.githubusercontent.com/21698471/85816674-97ef9c80-b79e-11ea-854a-c86f286ea191.png)

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

   No output in the first fuck

If the bug only appears with a specific application, the output of that application and its version:

    It appears every time

Anything else you think is relevant:

    No

**Comment by divykj** [comment]
Could you try running `THEFUCK_DEBUG=true fuck` for both first and second times and paste both the outputs here.

**Comment by turfaa** [comment]
Something magical happens. 

The issue was still happening a few minutes ago. Then I ran `THEFUCK_DEBUG=true fuck`, and the issue is completely gone.
