### ISSUE TITLE
settings.py is empty after installation

### ISSUE THREAD

**Issue by sheershoff** [nvbn/thefuck#111]
Please add content to settings.py for those who do not know python, so they can edit it.

**Comment by SanketDG** [comment]
:+1: Yup. The parameters are specified in the readme, but not the format. How are they read and written?

**Comment by scorphus** [comment]
I'm starting to amend this issue, I'll soon create a pull-request.

**Comment by scorphus** [comment]
Please check #119. And sorry for all noise above. :relaxed:
