### ISSUE TITLE
Python 3.8 error with brew version - error while loading shared libraries: libpython3.8.so.1.0

### ISSUE THREAD

**Issue by adamdodev** [nvbn/thefuck#1110]
**The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0 and Bash 4.4.12(1)-release`):**

Unable to run `thefuck` command, but here's the output of `brew info thefuck`:

```
thefuck: stable 3.30 (bottled), HEAD
Programatically correct mistyped console commands
https://github.com/nvbn/thefuck
/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.30_1 (850 files, 7.7MB) *
  Poured from bottle on 2020-07-06 at 11:22:47
From: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/thefuck.rb
==> Dependencies
Required: python@3.8 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Add the following to your .bash_profile, .bashrc or .zshrc:

  eval $(thefuck --alias)

For other shells, check https://github.com/nvbn/thefuck/wiki/Shell-aliases
==> Analytics
install: 252 (30 days), 744 (90 days), 2,212 (365 days)
install-on-request: 252 (30 days), 744 (90 days), 2,209 (365 days)
build-error: 0 (30 days)
```

**Your system (Debian 7, ArchLinux, Windows, etc.):**

Ubuntu 18.04.4 LTS

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

Homebrew 2.4.3-91-gf72328d
Homebrew/linuxbrew-core (git revision ea4a0e; last commit 2020-07-05)
Homebrew/homebrew-cask (git revision 1f8cc; last commit 2020-07-06)

**How to reproduce the bug:**

After `brew upgrade` a number of brew-installed tools (including thefuck) errored with `libpython3.8.so.1.0` errors, e.g.

```
/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.30_1/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

For other tools, a `brew reinstall X` fixed the issue, thefuck is the only one still showing the error.

**The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):**

All `thefuck` commands error with the following

```
/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.30_1/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**If the bug only appears with a specific application, the output of that application and its version:**

N/A

**Anything else you think is relevant:**

Reinstalled both `python@3.8` and `thefuck` with `brew reinstall X` with no luck.

**Comment by scorphus** [comment]
Please follow Homebrew/linuxbrew-core#20174.
