### ISSUE TITLE
Do you kiss your mother with that mouth?

### ISSUE THREAD

**Issue by dmwelch** [nvbn/thefuck#1128]
Okay, yes, the title is a bit tongue-in-cheek but hear me out- 

First, typing `*uck` in my terminal throughout the day just ruins my attitude and my work satisfaction is tenuous as it is.  

On top of that, working from home in the days of COVID, the LAST thing I want my kids telling my wife is "But I saw Daddy type it on HIS computer!!!" when we get an email requesting a parent-teacher conference...

Also, sharing this with co-workers or management - forget about it.  Advocating it to leadership as a "suggested tool" would immediately turn them off before even knowing what it does unfortunately, which sucks because the project is awesome and more ppl should be using it!

All this amounts to a burden of adoption just because of the project name.  This may be "too late" for this project but maybe not?  There are a lot of projects that have rebranded later in their life - it's worth considering. 😄

**Comment by norkko** [comment]
fuck no

**Comment by nvbn** [comment]
You can setup a less offensive alias - https://github.com/nvbn/thefuck#manual-installation

**Comment by dopdahl16** [comment]
I would second setting up a less explicit alias for personal use. Maybe "oops".
As for using this tool in a workplace setting, it may be worth acknowledging that it has an explicit name and just moving on. I don't think that in many workplaces, people would create enough of a stink to rule out using thefuck, especially if you require the use of an alias and just send that alias over to people in their .bashrc or .bash_aliases
