### ISSUE TITLE
Why is gucview corrected to gview?

### ISSUE THREAD

**Issue by amenk** [nvbn/thefuck#113]
me@home:~$ gucview
No command 'gucview' found, did you mean:
 Command 'guvcview' from package 'guvcview' (universe)
gucview: command not found
me@home:~$ fuck
gview
Gtk-Message: Failed to load module "overlay-scrollbar"

**Comment by nvbn** [comment]
Because `difflib.get_close_matches` thinks is a closest match from all available binaries.

In the future `no_command` rule will look in a shell history, so result of the `fuck` will be more accurate.

**Comment by amenk** [comment]
Okay, I was thinking is parses the "did you mean" output from Ubuntu itself.
