### ISSUE TITLE
Install on MacOS without homebrew possible.

### ISSUE THREAD

**Issue by janpauldahlke** [nvbn/thefuck#1137]
Hi Guys,

i am coming via Blog articles and want to test it. My question is. Can i make the install without homebrew? I try to avoid this.

**Comment by janpauldahlke** [comment]
Label it question and close after answer pls.

ty for your time in the project.

**Comment by scorphus** [comment]
_Quoting [Installation](https://github.com/nvbn/thefuck#installation)_
> install *The Fuck*  by using `pip`:
> 
> ```bash
> pip install thefuck
> ```
