### ISSUE TITLE
thefuck crashes if the command is run twice after clearing command history

### ISSUE THREAD

**Issue by AlmondRumble11** [nvbn/thefuck#1141]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.30 using Python 3.8.5 and Bash 5.0.17(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

    Ubuntu 20.04.1 LTS

How to reproduce the bug:

   "$history -c", then "$fuck", then "$fuck"

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

     After first fuck-command
    bash: fc: history specification out of range
    DEBUG: Run with settings: {'alter_history': True,
    debug': True,
    env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
    exclude_rules': [],
    history_limit': None,
    instant_mode': False,
    no_colors': False,
    num_close_matches': 3,
    priority': {},
    repeat': False,
    require_confirmation': True,
    rules': [<const: All rules enabled>],
    slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
    user_dir': PosixPath('/home/jesse/.config/thefuck'),
    wait_command': 3,
    wait_slow_command': 15}
    DEBUG: Empty command, nothing to do
    DEBUG: Total took: 0:00:00.000207

    After second fuck-command
    DEBUG: Run with settings: {'alter_history': True,
    debug': True,
    env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
    exclude_rules': [],
    history_limit': None,
    instant_mode': False,
    no_colors': False,
    num_close_matches': 3,
    priority': {},
    repeat': False,
    require_confirmation': True,
    rules': [<const: All rules enabled>],
    slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
    user_dir': PosixPath('/home/jesse/.config/thefuck'),
    wait_command': 3,
    wait_slow_command': 15}
    DEBUG: Total took: 0:00:00.018500
    Traceback (most recent call last):
    File "/usr/local/bin/thefuck", line 8, in <module>
    sys.exit(main())
    File "/usr/local/lib/python3.8/dist-packages/thefuck/entrypoints/main.py", line 31, in main
    fix_command(known_args)
    File "/usr/local/lib/python3.8/dist-packages/thefuck/entrypoints/fix_command.py", line 36, in fix_command
    command = types.Command.from_raw_script(raw_command)
    File "/usr/local/lib/python3.8/dist-packages/thefuck/types.py", line 77, in from_raw_script
    script = format_raw_script(raw_script)
    File "/usr/local/lib/python3.8/dist-packages/thefuck/utils.py", line 335, in format_raw_script
    script = ' '.join(raw_script)
    TypeError: can only join an iterable

If the bug only appears with a specific application, the output of that application and its version:

    Also on Mint

Anything else you think is relevant:

    FILL THIS IN

**Comment by divykj** [comment]
It was a pretty trivial bug, thanks for reporting 🙌
