### ISSUE TITLE
Not Displaying Parser Suggestion(s)

### ISSUE THREAD

**Issue by fr33roam3r** [nvbn/thefuck#1148]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.30 using Python 3.9.0 and Bash 5.0.17(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

    Linux Mint 20

How to reproduce the bug:

    Unknown. 

I tried looking through the `README.md` on the GitHub page to see if there is a setting I needed to configure to see the parser suggestions, but I couldn't find anything I had to configure for it to show up. However, when I do use the command `fuck`, it does provide a suggestion then... It just appears to be different from the `.gifs` on the documentation.

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

[thefuck.txt](https://github.com/nvbn/thefuck/files/5624911/thefuck.txt)

**Comment by scorphus** [comment]
Are you sure the `fuck` function is properly defined? What is the output of `type fuck`?

**Comment by fr33roam3r** [comment]
```shell
fuck is a function
fuck () 
{ 
    TF_PYTHONIOENCODING=$PYTHONIOENCODING;
    export TF_SHELL=bash;
    export TF_ALIAS=fuck;
    export TF_SHELL_ALIASES=$(alias);
    export TF_HISTORY=$(fc -ln -10);
    export PYTHONIOENCODING=utf-8;
    TF_CMD=$(
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER "$@"
                ) && eval "$TF_CMD";
    unset TF_HISTORY;
    export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
    history -s $TF_CMD
}
```

**Comment by scorphus** [comment]
Hm, I missed the _“It just appears to be different from the .gifs on the documentation”_ part. That's quite expected. Those GIFs were created a while ago, and since then not updated.

**Comment by scorphus** [comment]
Sorry, I'm not sure I understand. Could you please try to describe your issue more clearly?

**Comment by fr33roam3r** [comment]
Sure! When a mistake is made while `thefuck` is running on my terminal, it is not pointed out with a suggested correction for the typo.

**Comment by scorphus** [comment]
Ok. Could you please provide steps to reproduce your issue? Or maybe a screenshot of the steps in which the mistake is made, then `fuck` is called with no suggestions provided (i.e. `No fucks given`)

For example:

```
$ this_is_an_unknown_command
bash: this_is_an_unknown_command: command not found
$ fuck
No fucks given
```

**Comment by fr33roam3r** [comment]
In the terminal I make a mistake, **but it does not offer any correction** _until_ I type `fuck`.
```
freeroamer@nexus:~/Desktop$ pyton
bash: pyton: command not found
freeroamer@nexus:~/Desktop$ fuck
python [enter/↑/↓/ctrl+c]
Python 2.7.18 (default, Aug  4 2020, 11:16:42) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
[error.txt](https://github.com/nvbn/thefuck/files/5712586/nofucksgiven.txt)

**Comment by scorphus** [comment]
That's the expected behavior. Wha else would you expect?

**Comment by fr33roam3r** [comment]
It's missing the "Did you mean..." ![image](https://user-images.githubusercontent.com/46826941/102621595-cb87ff80-410d-11eb-9e1b-1cce4f3a3719.jpeg)

**Comment by scorphus** [comment]
It never shows it. That's part of the error message.

**Comment by fr33roam3r** [comment]
I guess you were right about the `gif` then - about it not being up date.

**Comment by scorphus** [comment]
Hey! I guess I got what you mean. That "Did you mean" thing comes from the `command-not-found` package on Ubuntu. You can activate that by just installing it with `apt install -y command-not-found`.

**Comment by fr33roam3r** [comment]
Ohhh!!!! Thank you so much for the info! This should totally be an optional setting for the code.
