### ISSUE TITLE
Give a fuck about ModuleNotFoundError

### ISSUE THREAD

**Issue by mmatrosov** [nvbn/thefuck#1149]
Those who have ever tried to run moderately complicated python scripts are familiar with this kind of errors:

    ModuleNotFoundError: No module named 'more_itertools'

It would be nice if `fuck` was able to fix this with `pip install`.

**Comment by divykj** [comment]
Seems to be a nice idea, maybe I'll try to make a PR on this!

Thank you for the Issue 👍🏻

**Comment by divykj** [comment]
However, upon some thinking, there are some python modules which have a different package name on PyPI and expose different module name for import.

Any ideas on how to handle that?

**Comment by mmatrosov** [comment]
Hmm, quick googling showed there is indeed no simple way to find the package name given a module name. I'd suggest adding a config like this:

```
{
  "module_name1": "package_name1",
  "module_name2": "package_name2",
  "module_name3": ["package_name3.1", "package_name3.2"],
  ...
}
```

If the missing module is specified in the config, then suggest installing the corresponding package from the config (or suggest to select on of the specified packages, if there are several). If the missing module is not specified in the config, then suggest installing the package with the same name.

What do you think?

**Comment by divykj** [comment]
I think maintaining such a config (which in itself is not a trivial task) for a single rule, should not come under thefuck's umbrella of responsibilities. IMO, a basic rule for the modules with the same package name should be the only thing thefuck should handle.

Thoughts, @scorphus?

**Comment by scorphus** [comment]
> some python modules which have a different package name on PyPI and expose different module name for import

I'd say most modules are called the same on PyPI. The rule would then work for the majority of them. It's only a shame it won't work for things like `PIL`, `dateutil`, `ffmpeg`, etc.

**Comment by mmatrosov** [comment]
That's why I suggest having a small supplimentary config.

**Comment by divykj** [comment]
I don't like the idea of a supplementary config file.

Thoughts on that @scorphus?

**Comment by scorphus** [comment]
A module=>package dictionary would be nice but I don't think it's even nearly feasible. Moreover, it would be out of the scope of TF.

Is there perhaps any lib out there that has a near-complete dictionary?
