### ISSUE TITLE
passing a Variables as a perameter for multiple scripts

### ISSUE THREAD

**Issue by vamsi-cloud** [nvbn/thefuck#1157]
I am using this mdx  to pull the data .I wanted to pass **WHERE ([Version].[Version 1],[Scenario].[2EA],[Year].[2020])**""" these **condition variables** as perameters to  multiple scripts to perform multiple tasks. Please guide me how to do it
mdx="""
    SELECT
    NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL([Level Type])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Shift Type])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Level Class])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Skills])},0)}    
    *{TM1FILTERBYLEVEL({TM1SUBSETALL([Location])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Emp Category])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Travel Location])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Location Type])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Level])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Month])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Department])},0)}
    
     ON ROWS,
    NON EMPTY {[Measure HC FTE].[FTE (PlanYear)]} ON COLUMNS
    FROM [Input_HC_FTE_Trips_Days]
    WHERE ([Version].[Version 1],[Scenario].[2EA],[Year].[2020])"""

**Comment by scorphus** [comment]
@vamsi-cloud, are you sure you openned this issue in the correct repository?
