### ISSUE TITLE
Cache --aliases automatically or with a --enable-experimental-caching option

### ISSUE THREAD

**Issue by equwal** [nvbn/thefuck#1161]
It takes ~`0.16ms`~ `0.16 Seconds` for every call to `thefuck --alias thing` in my `.bashrc`, which is way too long. It should be instantaneous, and I consider this a bug.

For now I have made a pull request adding a snippet for using a user-level cache, but really that shouldn't be necessary.
~https://github.com/nvbn/thefuck/pull/1160~
See wiki page on it
https://github.com/nvbn/thefuck/wiki/Cache-aliases-Startup

**Comment by hashworks** [comment]
```bash
$ time thefuck --alias

            fuck () {
                [...]
            }

thefuck --alias  0.11s user 0.01s system 99% cpu 0.119 total
```

120ms just for the function.

**Comment by equwal** [comment]
> ```shell
> $ time thefuck --alias
> 
>             fuck () {
>                 [...]
>             }
> 
> thefuck --alias  0.11s user 0.01s system 99% cpu 0.120 total
> ```
> 
> 120ms just for the function.

Yeah, that is how I got the number, though I accidentally wrote "ms" instead of seconds, three orders of magnitude difference.

**Comment by equwal** [comment]
Well, here is how I cache it:

https://github.com/nvbn/thefuck/wiki/Cache-aliases-Startup

I'm still working on getting experimental mode cached, but had to keep restarting my computer when thefuck would crash it.

**Comment by equwal** [comment]
I think a better way to do this would be to allow using multiple arguments to alias instead of having to call thefuck several times.

Also, reducing the amount of stuff imported for the alias command can halve the time (50ms on my machine), and at that point would be essentially instant.

**Comment by hashworks** [comment]
TBH, in relation my whole (rather large) `.zshrc` needs only 110ms. Therefore, I think 50ms are still quite much.

I guess I'll set up a wrapper function so it only calls `thefuck --alias` once I actually want to use it.

**Comment by equwal** [comment]
I have solved the problem of the system 50%; the solution is multiple aliases in a single call to thefuck
```sh
eval $(thefuck --alias a s d f j k l)
```
https://github.com/nvbn/thefuck/pull/1162

**Comment by equwal** [comment]
Turns out you can just `alias whatever=fuck` after running the `--alias` command.

Explained here https://github.com/nvbn/thefuck/pull/1162#issuecomment-768387193

Still, this issue was helpful in looking into the (absurdly?) slow time to execute `thefuck --alias` even on its own.

**Comment by equwal** [comment]
[Wiki page here about multiple aliases, hopefully it helps unsuspecting victims](https://github.com/nvbn/thefuck/wiki/Multiple-aliases)
