### ISSUE TITLE
Updating readme file

### ISSUE THREAD

**Issue by bhav09** [nvbn/thefuck#1173]
Hey maintainers. I have found the repo to be rich in useful content. However, I believe the main readme file can be updated with the tags of the sections so as to increase readability and to help readers jump to a section directly without scrolling that much. I would like to work on this and request you to please assign it to me. Thanks.

**Comment by bhav09** [comment]
@scorphus, thank you very much for assigning me the task.

**Comment by scorphus** [comment]
Fixed by the linked PR.
