### ISSUE TITLE
Error at ubuntu install

### ISSUE THREAD

**Issue by recalderon** [nvbn/thefuck#1176]
When i run `sudo pip3 install thefuck` i got `The folder you are executing pip from can no longer be found.`

**Comment by divykj** [comment]
Hey, this looks like more of a pip issue.

Maybe [this](https://stackoverflow.com/questions/56739226/the-folder-you-are-executing-pip-from-can-no-longer-be-found) will help.
TL;DR: Start a new terminal session. If that doesn't work, log out the user and log back in.

**Comment by recalderon** [comment]
Sorry to bother with this, its working as usual! Thanks for your help!
