### ISSUE TITLE
Computer Glitch

### ISSUE THREAD

**Issue by Electronick79** [nvbn/thefuck#1182]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    FILL THIS IN

Your system (Debian 7, ArchLinux, Windows, etc.):

    FILL THIS IN

How to reproduce the bug:

    FILL THIS IN

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    FILL THIS IN

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

    FILL THIS IN

![image](https://user-images.githubusercontent.com/63924606/113372310-5d6eed80-9336-11eb-912e-816cc2b177f2.png)

![image](https://user-images.githubusercontent.com/63924606/113372328-6c55a000-9336-11eb-9211-8842fd70b70d.png)

![image](https://user-images.githubusercontent.com/63924606/113372408-a757d380-9336-11eb-9091-0cf7af0472eb.png)

**Comment by Electronick79** [comment]
here you are, sitting in front of your computer, getting ready to enjoy the Wonder of the Day. You open your web browser and navigate your way to Wonderopolis. You click the link to read today's Wonder and — beep! blip! buzz! — your browser freezes and then shuts down suddenly.

What's going on here? Is your computer dead? Did it crash? Hopefully, it's just a temporary error in one of your computer's systems that caused a malfunction during data processing…or what computer experts refer to as a glitch.

**Comment by BraindedGamer** [comment]
Is this guy just shitposting?

**Comment by divykj** [comment]
@BraindedGamer

Yes.

**Comment by thaynos** [comment]
imagine shitposting on github. peak retard.

**Comment by neelkarma** [comment]
can this be closed or something?
