### ISSUE TITLE
here you are, sitting in front of your computer, getting ready to enjoy the Wonder of the Day. You open your web browser and navigate your way to Wonderopolis. You click the link to read today's Wonder and — beep! blip! buzz! — your browser freezes and then shuts down suddenly.

### ISSUE THREAD

**Issue by Electronick79** [nvbn/thefuck#1183]
here you are, sitting in front of your computer, getting ready to enjoy the Wonder of the Day. You open your web browser and navigate your way to Wonderopolis. You click the link to read today's Wonder and — beep! blip! buzz! — your browser freezes and then shuts down suddenly.

What's going on here? Is your computer dead? Did it crash? Hopefully, it's just a temporary error in one of your computer's systems that caused a malfunction during data processing…or what computer experts refer to as a glitch.

_Originally posted by @Electronick79 in https://github.com/nvbn/thefuck/issues/1182#issuecomment-812289235_

**Comment by justisGipson** [comment]
can this be closed?
