### ISSUE TITLE
Hi! I wanna make a node version of this, any advices XD

### ISSUE THREAD

**Issue by zzz6519003** [nvbn/thefuck#122]
:beers:

**Comment by nvbn** [comment]
I don't know, maybe - create simple as possible api for writing rules. Probably it'll be hard with async io =)

**Comment by zzz6519003** [comment]
async io? mm....i've seen your code, but haven't noticed that XD

**Comment by nvbn** [comment]
I mean that io in nodejs is async.

**Comment by zzz6519003** [comment]
welcome to node family!
