### ISSUE TITLE
Failed to download resource "gdbm"

### ISSUE THREAD

**Issue by xukefu** [nvbn/thefuck#1225]
**macos**

brew install thefuck

==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/gdbm-1.19.a
#=#=#
curl: (22) The requested URL returned error: 404
Trying a mirror...
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.19.arm64_big_sur.bot
##O#- #
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to homebrew.bintray.com:443
Error: Failed to download resource "gdbm"
Download failed: https://homebrew.bintray.com/bottles/gdbm-1.19.arm64_big_sur.bottle.tar.gz

**Comment by scorphus** [comment]
Hi!

Seems like a problem with your system being able to stablish connections through SSL. Could you please either [look for solutions](https://www.google.com/search?q=brew+LibreSSL+SSL_connect%3A+SSL_ERROR_SYSCALL) or report it to Homebrew?
