### ISSUE TITLE
Feature request: master to main

### ISSUE THREAD

**Issue by lenimartin** [nvbn/thefuck#1234]
Now that github has made the default branch been named `main` instead of `master`, developers in the world waist precious seconds of their live rebasing master, then swear out loud, then type the same command replacing `master` by `main`

AC:
- developer types `git rebase master`
- developer types his swear world instead of saying it
- developer accepts the new proposition to `git rebase main`
- developer smiles

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

The Fuck 3.30 using Python 3.8.10 and ZSH 5.8

Your system (Debian 7, ArchLinux, Windows, etc.):

Ubuntu 20.04

**Comment by scorphus** [comment]
Hi, thanks for the nice suggestion!

This feature in fact has already been added in #1184 – I know, the PR's title has nothing to do with that, but the content has.

Please refer to the [*How it works*](https://github.com/nvbn/thefuck#how-it-works) section of the docs for a list of all available rules.

I'm leaving this open until 3.32 is released.

**Comment by scorphus** [comment]
[3.32](https://github.com/nvbn/thefuck/releases/tag/3.32) is finally out! :tada:
