### ISSUE TITLE
fuck gets killed immediately 

### ISSUE THREAD

**Issue by Aransh** [nvbn/thefuck#1239]
I've been using thefuck for a while now, today it suddenly started getting killed immediately no matter what I do.
Tried reinstalling, tried debugging, tried resetting the configuration directory, nothing worked...

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    [1]    10081 killed     thefuck --version

Your system (Debian 7, ArchLinux, Windows, etc.):

    MacOS Big Sur 11.6

How to reproduce the bug:

    Simply use fuck

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    [1]    10136 killed     fuck

Anything else you think is relevant:

    As I've said, worked fine until today, can't think of anything relevant I could've done...

**Comment by serbInit** [comment]
did you try rebooting ?

it's getting killed instead of exiting itself, so maybe you're out of memory ? Mac OS kills "unused processes" if it thinks memory usage is too high

**Comment by Aransh** [comment]
@serbInit Hey, yes I did try rebooting, also updated to MacOS Monterey since, still the same.
also, I'm using a recent M1 macbook pro, memory/cpu usage in Activity Monitor seems low, and I have no problem opening any other programs...

**Comment by ImranVirani** [comment]
Maybe try reinstalling?

**Comment by Aransh** [comment]
Hey @ImranVirani , completely forgot about this issue honestly.
The issue ended up being Mac storage being almost full, it created all kinds of issues but this was the most apparent one (strange that I only had it with this tool, but understandable).
After clearing it up, everything was working again, closing!
