### ISSUE TITLE
Instructions for use in a corporate environment

### ISSUE THREAD

**Issue by mensly** [nvbn/thefuck#1252]
Corporate environments often don't allow admin access to devices, and might have issues with swearing.

When I'm not at work, I'll do a proper PR to update the readme, but here's some notes for future-me:
```
pip3 install --user thefuck
```

```
⋊> ~ cat ~/Applications/thedang
#!/usr/bin/env python3
from thefuck.main import main
main()
```

```
thedang --alias | sed 's/fuck/dang/g' | sed 's/merge .*/merge/' > ~/.config/fish/functions/dang.fish
```

```
⋊> ~ ehco foo
fish: Unknown command: ehco
⋊> ~ dang
echo foo [enter/↑/↓/ctrl+c]
foo
```

**Comment by scorphus** [comment]
Create a `thedang` symlink and `thefuck --alias dang` whenever you see the need.
