### ISSUE TITLE
Needs rules for TAR

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [nvbn/thefuck#1259]
tar -xsdrffwefwfawefasfd

(Tar is broken, because remembering tar commands is hard)

fuck

*archive magically works.

(Assuming input file, or argument is a file, we likely want to extract it.)
(Assuming input is a folder, we likely want to tar/compress it)

**Comment by akai54** [comment]
Should be closed ?

**Comment by XtremeOwnageDotCom** [comment]
Appears this issue was resolved with these PRs:

https://github.com/nvbn/thefuck/pull/1293
https://github.com/nvbn/thefuck/pull/1266
