### ISSUE TITLE
Fails to recognise DNF's plea for root.

### ISSUE THREAD

**Issue by ryleu** [nvbn/thefuck#1261]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

The Fuck 3.32 using Python 3.10.1 and Fish Shell 3.3.1

Your system (Debian 7, ArchLinux, Windows, etc.):

Fedora 35

How to reproduce the bug:

Try to use `dnf` without sudo and then use thefuck.

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

[thefuck_out.txt](https://github.com/nvbn/thefuck/files/7836491/thefuck_out.txt)

If the bug only appears with a specific application, the output of that application and its version:

It only occurs with DNF.

Anything else you think is relevant:

![image](https://user-images.githubusercontent.com/69326171/148710980-b4c18a2a-aeb9-4f49-bbfe-7673669f6be5.png)

**Comment by scorphus** [comment]
If only DNF opted for a more "universal" error message or at least that would include any of these patterns:

https://github.com/nvbn/thefuck/blob/841e3f9e13f52747c18319b55c77ece8095df306/thefuck/rules/sudo.py#L1-L35

Supporting it might be be done by adding one more pattern, `has to be run with superuser`, to that list.

**Comment by spotted-cat** [comment]
Can I help with this one? I am new to FOSS.

**Comment by ryleu** [comment]
> Can I help with this one? I am new to FOSS.

Absolutely! Just fork the repo, clone your fork, make the edit, commit, and make a pull request from your fork to the main project.

**Comment by spotted-cat** [comment]
I think the issue is solved now?

**Comment by ryleu** [comment]
> I think the issue is solved now?

It is not. This issue will automatically close when the PR is merged.
