### ISSUE TITLE
[Addition] Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [nvbn/thefuck#1271]
The project is currently missing the Code of Conduct which defines standards for how to engage in a community. If you are interested in adding that, then I would want to add a PR with that. 

Please let me know what do you think about that.

**Comment by jech** [comment]
Should the code of conduct forbid swearwords?

**Comment by FahimFBA** [comment]
> Should the code of conduct forbid swearwords?
> 

Please let me add a Pull Request first. Then it would be helpful to discuss that,

**Comment by RafaelKuhn** [comment]
well folks... Linus Torvalds was right

what the fuck man? you're PRing a code of conduct on the fucking thefuck project??
are you actually dysfunctionally retarded?

**Comment by LoganDark** [comment]
> are you actually dysfunctionally retarded?

As described by this project's Code of Conduct this is not an acceptable way to address someone. Apologize immediately and also give me five dollars for taking the time to speak to you about this matter.
