### ISSUE TITLE
There is no && operator in fish

### ISSUE THREAD

**Issue by blaecwen** [nvbn/thefuck#128]
There is no && operator in fish, so cd_mkdir and other rules using chaining does not work. 
";and" should be used in fish instead of &&.
http://superuser.com/questions/446930/chain-fish-commands-via-or
![screenshot from 2015-04-25 12 06 58](https://cloud.githubusercontent.com/assets/8159819/7332342/b279f69a-eb43-11e4-862c-1e8e47caa146.png)

**Comment by nwinkler** [comment]
Is there a way for the program to know which shell is being used?

**Comment by installgen2** [comment]
@nwinkler the variable "$SHELL" should work. It doesn't check what shell is currently running, but it does check what the default shell is (to my understanding at least).

**Comment by nvbn** [comment]
Is it possible to replace `&& ` and `||` on fish side?

**Comment by ScoreUnder** [comment]
It might be more robust to make fish compatibility a command-line switch. Replacing && and || is just asking for trouble (think "perl -e")

**Comment by scorphus** [comment]
Absolutely, a change in thefuck itself to support such a switch is a better approach than replacing occurrences of `&&` and `||`. What do you think, @nvbn? I could work on that should we choose to go this way.

**Comment by nvbn** [comment]
@scorphus I added ability to define `from_shell`, `to_shell` functions for specific stuff, if you can implement fish specific actions in [thefuck/shells.py](https://github.com/nvbn/thefuck/blob/master/thefuck/shells.py), it'll be cool =)

**Comment by scorphus** [comment]
Sure, @nvbn! Count me in!

**Comment by scorphus** [comment]
This issue is addressed by 1b5c935 and can be closed.
