### ISSUE TITLE
It drops the quotes from a string when when it suggests a solution.

### ISSUE THREAD

**Issue by kxrn0** [nvbn/thefuck#1282]
If I fuck up with something like `gti commit -m "fist commit"`, it suggests `git commit -m first commit`, which is obviously wrong, since it drops the fucking quotes and fucks things up even more. Awesome fucking program, but fuck this shit, fr fr no cap bussin.

**Comment by davidegavio** [comment]
I'd like to work on this issue, does anyone know where may I find the incriminated piece of code?

**Comment by BrandonDoesDev** [comment]
@davidegavio If people knew that they'd fix it. Best to look for yourself or just add a feature that makes sure to include the quotes.

**Comment by RVALLER** [comment]
Hey I'm trying to make certain rules to fix issues and I'm not sure what is meant by putting it in the ~/.config/thefuck/rules
Unless I'm just being silly, I don't know where to find ~/.config

**Comment by scorphus** [comment]
Fixed in 5198b34f24ca4bc414a5bf1b0288ee86ea2529a8 (#1292). Thanks, @NikosKakonas and @djh82.
