### ISSUE TITLE
thefuck does not work as a command

### ISSUE THREAD

**Issue by Kronifer** [nvbn/thefuck#1286]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    None, `thefuck` displays as not found.

Your system (Debian 7, ArchLinux, Windows, etc.):

    Raspberry Pi OS Lite

How to reproduce the bug:

    install thefuck using the following: 
    `pip3 install thefuck --user`

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    None

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

    FILL THIS IN

**Comment by Rom1deTroyes** [comment]
You can find where is `thefuck` package with a `pip show` (I really like this one !) :
```sh
❯ pip3 show thefuck
Name: thefuck
[...]
Location: /home/romain/.local/lib/python3.9/site-packages
```

And where is `thefuck` command with :
```sh
command -v thefuck
/home/romain/.local/bin/thefuck
```

At that point, you may use the alias definition as on the readme.md

**Comment by scorphus** [comment]
Hey, @Kronifer. It looks like this SO thread can be helpful in your case: [How do I access packages installed by `pip --user`?](https://stackoverflow.com/questions/38112756/how-do-i-access-packages-installed-by-pip-user "let me google that for you")
