### ISSUE TITLE
fuck this and fuck that

### ISSUE THREAD

**Issue by crawfordcomeaux** [nvbn/thefuck#13]
Thoughts on adding these features?
# fuck this
- `fuck this <rule name> [hard] [<match rules>] <command spec>`
- Adds &lt;rule name>.py to rules dir with match/command args
- Somehow determines match rules if not provided
- Prompts for confirmation after outputting generated file name & code
- 'hard' argument skips confirmation
# fuck that
- `fuck that <rule name> [hard] [<match rule>]`
- To be used after running correct command
- argument functionality same as with "fuck this ..."
- command is generated from previously executed command
### Things to think about
- How to specify a rule/command without typing Python on command line
  - Grammar for defining where to match (script/stdout/stderr), what to match, and logical combinations
  - Grammar for command or just take command string?
  - easier to just accept Python from command line?
- Automatically call 'fuck' after 'fuck this'?
- Ditch the args except for rule name & open default editor with generated boilerplate rule with script/stdout/stderr included in comments at top of file?

**Comment by aimonb** [comment]
Big +1 from me.. This is first thing our team thought about.

**Comment by aimonb** [comment]
I would imagine we could design a simple algorithm that compares the last command with the correct command given as an argument and auto generate a regex and rule that matches. This would make it so the user only has to tell fuck about the correct command and not a whole rule. If the new rule matches an existing rules command it can append the new rule.

**Comment by scorphus** [comment]
Closing this one for now.
