### ISSUE TITLE
[Feature request] Recognise and offer fixes for missing `git clone` when given a url or SSH ending in .git

### ISSUE THREAD

**Issue by MiguelGuthridge** [nvbn/thefuck#1300]
It would be neat if a fix was required when I pasted a `git` URL intending to clone it, but forgot to add the `git clone` to the start. There's a fix for when `git clone` is present twice, so I think it's reasonable to have one for when it's never present.

If someone can point me to a getting started page so I can find my way around the project and learn the basics, I'm happy to create an implementation and PR for this myself.

**Comment by NikosKakonas** [comment]
The main function of the project is in the file thefuck/entrypoints/main. However, I suggest you not to try to understand what the whole project do. I think that the easiest way is to try and create your own rules or improve some of the already existed. This approach helped me a lot. I am also new to the project. I have tried to do some PR and that was something usefull for me.
 
You can see how to create your own rules here: https://github.com/nvbn/thefuck#creating-your-own-rules

**Comment by MiguelGuthridge** [comment]
Yep, I'm working on one right now: #1302

**Comment by MiguelGuthridge** [comment]
Fixed in #1302
