### ISSUE TITLE
Not a real issue, why the name thefuck

### ISSUE THREAD

**Issue by cyberbloke** [nvbn/thefuck#1303]
Just curious why the name thefuck, there are billions of other decent names you could have used ??
please acknowledge this message...and please do respond, as I'm seriously curious about such a name ...

!-- If you have any issue with The Fuck, sorry about that, but we will do what we
can to fix that. Actually, maybe we already have, so first thing to do is to
update The Fuck and see if the bug is still there. -->

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    FILL THIS IN

Your system (Debian 7, ArchLinux, Windows, etc.):

    FILL THIS IN

How to reproduce the bug:

    FILL THIS IN

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    FILL THIS IN

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

    FILL THIS IN

**Comment by EthanWill059** [comment]
Not a real issue no, the name is humour clearly

**Comment by cyberbloke** [comment]
Thank you for your response..I understand and now get the humor part too..
With warm regards !!!

**Comment by djh82** [comment]
Did you notice the first line of the README?

"The Fuck is a magnificent app, inspired by a [@liamosaur](https://twitter.com/liamosaur/) [tweet](https://twitter.com/liamosaur/status/506975850596536320), that corrects errors in previous console commands."
