### ISSUE TITLE
Command "fuck" not found

### ISSUE THREAD

**Issue by TimSousa1** [nvbn/thefuck#1340]
I'm on `The Fuck 3.29 using Python 3.10.6 and Bash 5.1.16(1)-release` (Linuxmint) and for some reason the `fuck` command is "not found" when typing it in the terminal. Any suggestions? 
Thanks in advance!

**Comment by tamaki03** [comment]
Same 
> ubuntu 22.04 - wayland
> shell : zsh 

zsh: command not found: fuck

**Comment by tamaki03** [comment]
This command work with me 
> export PATH="$PATH:$HOME/.local/bin"
add it in your shell rc

**Comment by TimSousa1** [comment]
That fixed the issue! Thanks!
