### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Jeremy-Run** [nvbn/thefuck#1405]
I use Mac, so I exec the command `brew install thefuck` in terminal. but I get an error: 
```
Error: No such file or directory @ rb_sysopen - /Users/a/Library/Caches/Homebrew/downloads/3d4b9070cbc8071b95e9a28d78ea75caca9a32d6390eec8f914e21c832dcb179--ca-certificates-2023-01-10.all.bottle.tar.gz
```
I dont know how to get the tar.gz file, who can help me?
Thank you very much!

**Comment by chenrui333** [comment]
@Jeremy-Run 👋  that looks like a cache file, i think you can just rerun with `brew reinstall thefuck` to see if it works for you.

**Comment by SadiaSabrina** [comment]
Fuck yourself

**Comment by Jeremy-Run** [comment]
> @Jeremy-Run 👋 that looks like a cache file, i think you can just rerun with `brew reinstall thefuck` to see if it works for you.

@chenrui333 Thanks for your reply, unfortunately, it also can't work.😭

**Comment by chenrui333** [comment]
can you also submit a homebrew-core report? thanks!

**Comment by Jeremy-Run** [comment]
![image](https://github.com/nvbn/thefuck/assets/43458116/bda56530-01b5-4a86-8800-9808130df2e6)

Thanks, probably because my version of the system is too old, but I don't want to up it.
