### ISSUE TITLE
Support for Windows CMD

### ISSUE THREAD

**Issue by BenjaminKobjolke** [nvbn/thefuck#1425]
When I run "fuck" on windows cmd I get
"Seems like fuck alias isn't configured!"

But the help does not show how to configure thefuck for windows cmd, only for powershell.

The latest commit shows that there is support for windows cmd
https://github.com/nvbn/thefuck/commit/3cd187a3bb47351890ac7308464e1a2780507220

But I guess since the latest release is from January and the commit is from July a version that supports windows cmd wasn't released yet.

---

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

thefuck 3.32 for windows

Your system (Debian 7, ArchLinux, Windows, etc.):

Windows 11 CMD

How to reproduce the bug:

simply run fuck

**Comment by BinaryBitBytes** [comment]
# Terminal (CMD) vs. Shell (Powershell) vs BASH (GitBash)
-----------------------------------------
> ## Addressing Your Prompt
>>  ```
>> When I run "fuck" on windows cmd I get "Seems like fuck alias isn't configured!"
>> But the help does not show how to configure thefuck for windows cmd, only for powershell.
>> ```
----------------------------------------------

> ## <mark>Terminal (CMD)</mark>
>> - The terminal does not store the session in memory  globally without making environment variables where as the shell does store the session data as objects globally. The  <ins>__*terminal (CMD) only outputs data in characters.*__</ins>. Therefore the terminal cant store the instance of the commands result after execution.
----------------------------------------------

> ## <mark>Shell (PowerShell)</mark>
>> - The <ins>__*Shell (PowerShell) the state in memory will be stored throughout the session as objects instead of characters</ins>*__; until the session is closed. 
--------------------------------------------

> ## <mark>BASH (Bourne-Again SHell) [GitBash]</mark>
>> - So also a concept that should be considered is BASH. <ins>__*Being as a shell can store memory throughout the session BASH (Bourne-Again SHell) which is similar to treating data as text but instead of plain text it uses structures.*__</ins>
--------------------------------------------

> I am familiar with these concepts but I just wanted to address your Git Issue with some support. Hopefully it helps. Also Below I will provide a resource i used to fact check my understanding of explaining to your the reason why you could prompt the Git Issue.
--------------------------------------------

> ## References
>> ### What is ______ ?
>>> | 1. [Terminal](https://www.gartner.com/en/information-technology/glossary/terminal) | 2. [CMD](https://askubuntu.com/questions/506510/what-is-the-difference-between-terminal-console-shell-and-command-line) | 3. [Shell](https://linuxcommand.org/lc3_lts0010.php) | 4. [PowerShell](https://www.spiceworks.com/tech/devops/articles/what-is-powershell/) | 5. [Bash](https://www.gnu.org/software/bash/manual/html_node/What-is-Bash_003f.html#:~:text=1.1%20What%20is%20Bash%3F,Labs%20Research%20version%20of%20Unix.) |
>> ### **Comparison Chart**
>>> - [CMD v. PowerShell v. Bash Table](https://www.servertribe.com/difference-between-cmd-vs-powershell-vs-bash/#:~:text=Powershell%20is%20a%20task%2Dbased,in%20the%20form%20of%20characters.)
>>>> ![image](https://github.com/nvbn/thefuck/assets/94703967/69910b1d-ae84-4c6e-a611-f182544b993b)

**Comment by BenjaminKobjolke** [comment]
Sorry but I am not sure how your posts helps my issue.

**Comment by BenjaminKobjolke** [comment]
Thanks for the info!
