### ISSUE TITLE
/.zshrc:1: command not found: thefuck

### ISSUE THREAD

**Issue by sussyboiiii** [nvbn/thefuck#1427]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

The Fuck 3.32 using Python 3.10.13 and ZSH 5.9

Your system (Debian 7, ArchLinux, Windows, etc.):

MacOS 14

How to reproduce the bug:

install thefuck using brew or pip then update ~/.zshrc source it, restart the terminal then it wont work and when running fuck it tells me to source again

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

doesnt do anything here

If the bug only appears with a specific application, the output of that application and its version:

terminal on macos

Anything else you think is relevant:

    FILL THIS IN

**Comment by DarkDenims** [comment]
not sure if it's the same issue with me, but you can try to add this in your .zshrc file and tell me if it works:
`#thefuck
export PATH=$HOME/.local/bin:$PATH
eval "$(thefuck --alias --shell sh)"`

**Comment by DarkDenims** [comment]
not sure if it's the same issue with me since even after i installed it either with brew or pip and the command fuck still isn't found but you can try to add this in your .zshrc file and hopefully it fixes it:

`export PATH=$HOME/.local/bin:$PATH`
`eval "$(thefuck --alias --shell sh)"`

**Comment by sussyboiiii** [comment]
Hello, thank you for your recommendation, but it didnt fix my problem unfortunatley!

**Comment by sussyboiiii** [comment]
Install with brew.
