### ISSUE TITLE
Thefuck with Python 3.12.x

### ISSUE THREAD

**Issue by M0RC** [nvbn/thefuck#1446]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    thefuck 3.32 (latest on pip), python 3.12.3, bash 5.2.26(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

    Manjaro 24.0, but same issue on Ubuntu 24.04 and Fedora 40. The problem seems to come from python 3.12 and the imp library

How to reproduce the bug:

    Run fuck command with python 3.12

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    
![image](https://github.com/nvbn/thefuck/assets/23026811/8026e04f-b75a-4df6-b322-9ca45e84d312)

If the bug only appears with a specific application, the output of that application and its version:

    No

Anything else you think is relevant:

    Imp library removed on Python 3.12?

**Comment by joshuai96** [comment]
Technically its fixed by #1248, if `importlib` is installed. But this has not been released yet :/

**Comment by M0RC** [comment]
Thanks for your reply. I hope a release will be published soon.

**Comment by joshuai96** [comment]
You can clone the project and install via `pip install .` to get it running now.
