### ISSUE TITLE
No support for python 3.12

### ISSUE THREAD

**Issue by Coding4Hours** [nvbn/thefuck#1456]
the fuck does not work with python 3.12 because it uses imp can you give it support for python 3.12?

**Comment by syntaxboybe** [comment]
if 3.12 has no imp then the only solution is to downgrade from 3.12 ---> 3.11

**Comment by Coding4Hours** [comment]
bruh cant they use importlib or something

**Comment by syntaxboybe** [comment]
i think we will do it manaually

**Comment by syntaxboybe** [comment]
see here 0420442

**Comment by gpchn** [comment]
this repo is dead, i think...

**Comment by gpchn** [comment]
last commit is 7 month ago, to fix README.md.

**Comment by syntaxboybe** [comment]
> last commit is 7 month ago, to fix README.md.

yeah i think so

**Comment by MZachary** [comment]
i ran into an issue with python3.12 not having distutils, not smart enough to know if imp also solves that issue. otherwise 3.11.9 worked

**Comment by pulsedemon** [comment]
working for me on my mac with python 3.12.4

**Comment by NWPU66** [comment]
same problem in Windows with Python 3.12.7.

**Comment by syntaxboybe** [comment]
> same problem in Windows with Python 3.12.7.

just simply downgrade python version in order to use it
