### ISSUE TITLE
`ecoh test; fuck` causes an infinite loop.

### ISSUE THREAD

**Issue by eduardog3000** [nvbn/thefuck#147]

**Comment by pranav15197** [comment]
Would it work if we would split the args based on the ';' , create a list of commands instead of just one and correct them and then execute them;
in this case, we'll get 2 commands ecoh test and fuck, former will be corrected to echo test and latter would be ignored

**Comment by neuton** [comment]
It's somewhat similar to https://github.com/nvbn/thefuck/issues/129 .
So it actually seems to be a more general problem of naive "double-fuck" check currently implemented.

**Comment by neuton** [comment]
Splitting based on ';' will work for this special case but won't work, say, for "`ecoh test && fuck`".

**Comment by ja5h** [comment]
How about this: 
**We parse the command for `fuck` and `thefuck` and replace it with an empty string before matching?**

It should be able to solve the problem caused by a stray `fuck` or `thefuck`.

**Comment by neuton** [comment]
Well, removing "fuck" and "thefuck" from a command string may simply break the command in a various ways.
Not sure, but it seems that a proper parser should be at least as complicated as the bash parser.
Also, a more general case of the problem includes situations with aliases, environment variables (and maybe some other cases, like scripts invocation or smth) and situations when "fuck" is written wrong and corrected by itself.

**Comment by eduardog3000** [comment]
@ja5h `ecoh fuck; fuck`

**Comment by eduardog3000** [comment]
Also, `ecoh a; fuck; fuck` can't be stopped with ctrl-c.

**Comment by ThatTomPerson** [comment]
Ok I don't do all that much bash programming but if you are running the commands in a subshell couldn't you just something like `alias fuck=""` before hand

**Comment by neuton** [comment]
@ThatTomPerson 
well, that seems to be somewhat a dirty hack and will, at best, unpredictably break the command

**Comment by nvbn** [comment]
Looks fixed:
```
➜ echo test;fuck
test
No fucks given
```

**Comment by eduardog3000** [comment]
@nvbn You tested it wrong, it should be *ecoh*, not *echo*, the point is if you have `;fuck` after something that `fuck` would correct, you get an infinite loop.

Try `ecoh test; fuck; fuck`.

**Comment by nvbn** [comment]
@eduardog3000 Oh, so I reopen it.

**Comment by eduardog3000** [comment]
Doesn't seem to be a problem anymore, `ecoh test; fuck` just does `No fucks given` and `ecoh test; fuck; fuck` puts you in a loop of suggesting `echo test; fuck` that can be broken with ctrl+c.

#837 is somewhat related, a little more extensive, and being worked on.
