### ISSUE TITLE
Fuck. Can't get this to install.

### ISSUE THREAD

**Issue by arvindravi** [nvbn/thefuck#15]
I get this ugly error while trying to install it on OS X 10.10.3.

Error:

![screen shot 2015-04-18 at 10 44 53 am](https://cloud.githubusercontent.com/assets/859832/7214106/fabd5582-e5b7-11e4-9136-9b30fc016677.png)

Log:

![screen shot 2015-04-18 at 10 44 30 am](https://cloud.githubusercontent.com/assets/859832/7214108/00f3a3b6-e5b8-11e4-8267-2a1785840914.png)

Any idea whats going on?

**Comment by Astalaseven** [comment]
It looks like a SSL error with pypi.python.org, not with the package itself. Can you download some other package from pypi?

**Comment by felipevolpone** [comment]
Hey @arvindravi, have you tried do this?

```shellscript
git clone git@github.com:nvbn/thefuck.git
cd thefuck/
python setup install
```

**Comment by arvindravi** [comment]
Still can't get it to work with `pip`. Tried with `easy_install` and it worked like a charm! 

@felipevolpone, That worked too. Thanks! Except the command was `python setup.py install`

@Astalaseven: The issue is definitely with Pypi (or my setup?), I couldn't install other packages too with pip, and ended up with the same error.

Closing this as its not the package's issue.
