### ISSUE TITLE
Idea: 'fuck' after 'cd <dir_name>' first checks for available directories for misspelt names

### ISSUE THREAD

**Issue by ja5h** [nvbn/thefuck#151]
When using "cd <dir_name>" in the command line, 'fuck' automatically creates the directory with the exact name specified. This may sometimes cause irritative behaviour if I am trying to open a directory and misspell its name. Though not too serious an issue, **it will surely enhance the usability of the application to predict that I have misspelt an existing directory name.**

This is what is the normal flow of 'fuck':

> jash@Jash:~/mydir$ ls
> dummy
> jash@Jash:~/mydir$ cd dumm
> bash: cd: dumm: No such file or directory
> jash@Jash:~/mydir$ fuck
> mkdir -p dumm && cd dumm
> jash@Jash:~/mydir/dumm$ 

Wouldn't it be great to have fuck predict that I have made a misspelling and suggest opening the right directory for me?

*(PS: I am a student and new to OSS. Be kind enough to forgive me if I make novice mistakes.)*

**Comment by pranav15197** [comment]
The problem seems to be with the history class, as on commenting out the following in the get_command function the issue disappears
```  
#if script == 'fuck' or script == history.last_script:
#    script = history.last_fixed_script or history.last_script
```

**Comment by ja5h** [comment]
I think you misunderstood my point. 

The command works fine as it should (Except perhaps for #152 that I found while messing around with it.)

The thing I was suggesting was **why not let it see my sub-directory names and try to find a match first before creating a new one?**

Also the code you suggested does not affect the above output in any way (at least on my computer.)

**Comment by pranav15197** [comment]
oh my bad, that comment was meant for #152

**Comment by ja5h** [comment]
Happens, I will check it out.

**Comment by nvbn** [comment]
Currently works like you described:
```bash
➜  cd dir 
No such file or directory: dir
➜  fuck
mkdir -p dir && cd dir [enter/ctrl+c]
➜  cd ..
➜  cd dirr
No such file or directory: dirr
➜  fuck
cd "/tmp/dir" [enter/ctrl+c]
```
