### ISSUE TITLE
sl_ls doesn't work when sl is valid joke command - expected?

### ISSUE THREAD

**Issue by Clpsplug** [nvbn/thefuck#153]
So I tried `sl` instead of `ls` before entering `fuck`. But then I realised that I actually had *valid* `sl` command (which activates a steam locomotive running through your console window as a joke. You can get one via HomeBrew.)   
In this case trying `fuck` actually 'didn't give any fuck.' is this expected action?

**Comment by ja5h** [comment]
Can you please post a screenshot or something to elaborate on it? What was the expected output and what did you get?

**Comment by Clpsplug** [comment]
I thought typing `sl` before `fuck` would correct my mistake, even if I have `sl` as a valid command.
This is what `sl` looks like when it gets executed. `sl` is a joke command which is meant to *'cure your bad habit of mistyping,'* as the man page says.
![sl](http://i.gyazo.com/116967a959371004e658d18a5f1f103c.png)

Right after that I tried `fuck`. I thought it would run `ls` for me, but
what I got is this. **No fuck given.**
![terminal output](http://i.gyazo.com/3908525cdbc8e73dbe609d6767cd9584.png)

**Comment by ja5h** [comment]
Interestingly in my case even when I do not have "sl" installed, it does not show me the output as "ls".

Instead:
![screenshot from 2015-05-01 20 36 06](https://cloud.githubusercontent.com/assets/5393353/7432009/b88c30a4-f041-11e4-92b5-4d552e3c18e4.png)

I think this is certainly an issue.

**Comment by Clpsplug** [comment]
Wow! I didn't see that coming.

**Comment by ja5h** [comment]
I found it! The reason is that in the code the rules are traversed in a specific order in which apt-get rule comes before ls. 

So when it sees something that can potentially be an apt-get, it evaluates it like that since in our case the repo is available as 'sl'.

**Comment by Clpsplug** [comment]
OK, seeing your testing I tested `thefuck` by killing `sl` temporarily cause Mac haven't got `apt-get`. No avail, `thefuck` didn't get it and went wrong like this... `wsdl`? Seriously?
![wsdl?!?](http://i.gyazo.com/b9a147d4eabfd741db6ebfe94181d23b.png)

**Comment by ja5h** [comment]
I still think it is because of the order in which the rules are loaded.

Since "sl_ls" is close to the bottom of the list, chances are that some of the higher order rules may trigger because of it. 

IDEA: Some mechanism needs to be present to find the best match rather than the first match.

**Comment by Clpsplug** [comment]
Would you mind me asking for clarification since I'm not that familiar with python.
Does `thefuck` give no fuck when the last command you type is right one? Or does it always 'correct me' when the last command matches any of the rules?

**Comment by pranav15197** [comment]
From what I could understand by reading the code,it guesses the right command by looking through the stderr that your wrong command generates, so if your command is right and doesnt give an error, no fuck is given

**Comment by ja5h** [comment]
It always corrects you as long as it finds a rule.

And what rule it uses depends on what is the first rule it finds.

In main.py's get_rules() method in the for loop it is sorting the bundle. When I removed that the order of the rules must have been affected. 

To simplify:
Suppose the rules are taken one at a time in an alphabetical fashion. Since 'a' comes before 's', apt-get.py will be evaluated before sl_ls.py. This means 'sl' never reaches sl_ls.py since apt-get was found first and since the first rule is satisfied it does not go any further.

What pranav says is right but only partially. The stderr is only used in some cases to find a match. For example in sl_ls.py the script directly uses the command rather than stderr.

**Comment by Clpsplug** [comment]
OK, but in that case why did `fuck` didn't give any fuck in my first problem? When I have `sl`, no fuck was given. However, when I killed `sl`, `thefuck` suggested `wsdr`. If what you're saying is the case `thefuck` would have suggested `wsdr` no matter what.

**Comment by ja5h** [comment]
I updated my explanation to be more simplified and clearer based on my understanding of the code.

**Comment by Clpsplug** [comment]
Crystal clear, thanks :+1:

**Comment by ja5h** [comment]
Thanks to you for pointing the bug out. Today is my first day in open source and I am already learning so much. :)

**Comment by ja5h** [comment]
Created a new issue that addresses a more general problem than this one - about the ordering thing that we discussed.

**Comment by ja5h** [comment]
I believe this issue is fixed!
