### ISSUE TITLE
Ordering of rules may need to be more well defined than simply 'sorted'

### ISSUE THREAD

**Issue by ja5h** [nvbn/thefuck#154]
This was an issue discovered while discussing #153.

I feel it was a part of a larger issue about how the ordering of rules affects the way some commands are interpreted.

In general, the program takes the first match, not the best match and hence very often it may have different effects in different scenarios (as discovered and discussed by @clpsplug and me in #153).

However the effects discussed therein are a part of a more general problem and hence I created a separate issue about it.

**Here is where I think the problem lies:**
In the method get_rules():
![image](https://cloud.githubusercontent.com/assets/5393353/7433365/1be71d1a-f04e-11e4-9c09-80b3b126283f.png)

In the statement:
![image](https://cloud.githubusercontent.com/assets/5393353/7433382/42653044-f04e-11e4-8012-b0911ae5548c.png)

Instead of using the sorted list of rules, we need a better approach that can select rules based on relevance and not alphabetical order.

**Comment by nvbn** [comment]
Yep, I'll add `priority` for the rules in nearest time.

**Comment by ja5h** [comment]
That should take care of it. 

However, may I suggest allowing the priority to also be user defined. Through the 'settings' or similar file.

For example, different users may have different needs, and being able to set the priorities would definitely be a good feature.

**Comment by nvbn** [comment]
`priority` attribute was added to the rules, and `priority` (`THEFUCK_PRIORITY`) ws added to settings for overriding rules priorities.
