### ISSUE TITLE
terminal get stuck when no previous commands are given.

### ISSUE THREAD

**Issue by miaekim** [nvbn/thefuck#16]
I installed this and relaunched. Then I act like title.

     $  fuck

The terminal got stuck.

I quitted the terminal, and relaunched twice.

    $  fuck
    No fuck given

It worked well. 

I am using OS X 10.10.3 + iterm(zsh) + python 2.7.6

**Comment by hojgr** [comment]
Happend to me too, bash, Linux Mint (kernel - 3.13.0-24-generic), python 2.7.6

In new terminal it works (`Can't fuck twice`) but it is maybe because i've tried a command in another terminal.

**Comment by playinggod** [comment]
Same for me when i use fuck after wrong python command (python for example).

OS X 10.10.3, iterm(fish), python 2.7.9

**Comment by nvbn** [comment]
Now fixed.
