### ISSUE TITLE
Idea: let thefuck learn from your fuckups

### ISSUE THREAD

**Issue by underscorejho** [nvbn/thefuck#163]
It would be nice if, instead of hard-coding possible wrong commands so much, there was some sort of `add_fuckup` command. Then in the future, there would be a rule or something that acted as a rule that watched for that fuckup.

For instance:

Instead of hard-coding the `cd..` fuckup, when you fuck up for the first time...

    -$ cd..
    cd..: command not found

and get...

    -$ fuck
    no fucks given

you have the option to...

    -$ fuck --add_fuckup
    thefuck added fuckup cd.. on cd

... or something like that.

**Comment by nwinkler** [comment]
How would it know what to do? How would it know to run `cd ..` instead of `cd..` in this case?

**Comment by underscorejho** [comment]
A dictionary maybe? Where the key is the fuckup and the value is the correct command. Probably saved locally somewhere. 

I'm really more interested in seeing if this is an idea people would be interested in. If so, then I can certainly do more research into the most effective ways to implement it. It just seems like a lot of hassle to have to manually enter rules for possible errors.

**Comment by uGuardian** [comment]
Couldn't you make it also that if you use fuck and it doesn't come up with something, you could reenter the command correctly and then use the add fuckup command to add the most recent command as a correction so you wouldn't have to manually hard-code the explicit correction?

**Comment by nwinkler** [comment]
That sounds like a reasonable approach! It would need some fiddling with the command parameters so e.g. learning that the `foo/bar/baz` part in `mkdir foo/bar/baz` is the dynamic part, so when you run `mkdir this/is/great` and you get the similar error message to the first command, it will know what to do.

Many of the rules are built in the following fashion:

* Apply regex match on `command.script`, `command.stdout` and `command.stderr`.
* Replace/transform part of `command.script` to fix the issue, e.g. prepending `sudo` or adding a parameter (`-p` in the `mkdir` case).

I agree that there should be a moderately easy way to define these without programming the rules...

**Comment by underscorejho** [comment]
Sweet. 

Ok. So on this feature-idea here we would want:

* local fuckup learning using an `add_fuckup` command (or `addfuckup`.. or `newfu`... or something)
* confirmation that it's learning the right fuckup/command pair (but this could be optional)
* probably some `learned_fuckups` rule that handles these new learned fuckups
* ... other things?

**Comment by nwinkler** [comment]
A way to share learned fuckups?

The learned fuckups should be stored in the local `~/.thefuck` folder.

**Comment by underscorejho** [comment]
I'll put that on the wishlist. That'd be sweet to be able to collect everyone's collective fuckups and 'learn' from them.

Oh and a way to remove a fuckup if for some reason you don't want it anymore.
