### ISSUE TITLE
Missing space between man and diff

### ISSUE THREAD

**Issue by dionyziz** [nvbn/thefuck#168]
dionyziz@descartes ~/workspace % mandiff
zsh: command not found: mandiff
dionyziz@descartes ~/workspace % fuck
diff
diff: missing operand after 'diff'
diff: Try 'diff --help' for more information.

**Comment by SanketDG** [comment]
:+1: Good catch.

**Comment by nvbn** [comment]
Rule was added by @SanketDG in 1.38.
