### ISSUE TITLE
What about of correcting history

### ISSUE THREAD

**Issue by a-x-** [nvbn/thefuck#174]
Let's fix mistypes in history after success run `fuck`
for rerun commands in the future as well as they typed correct

Is It Cool?

**Comment by nvbn** [comment]
It's already implemented:
```bash
➜ git brnch
git: 'brnch' is not a git command. See 'git --help'.

Did you mean this?
	branch
➜  fuck
git branch [enter/ctrl+c]
* master
➜ fc -ln -3
git brnch
fuck
git branch
```

**Comment by a-x-** [comment]
and not working...

**Comment by a-x-** [comment]
```
gitt status
fuck
...
```
then type `<up><up>` and get source mistaken `gitt status`

**Comment by nvbn** [comment]
What shell you use?
What version of thefuck?
Are you use latest version of the alias?

**Comment by a-x-** [comment]
bash
latest (installed recently)
latest (installed recently :)

**Comment by ja5h** [comment]
+1 a-x- 

The thing is reproduced on my shell as well. Would be a useful feature if implemented.

**Comment by a-x-** [comment]
Hmm, i check my alias now and surprised: it's obsolete: `$(thefuck $(fc -ln -1))`

**Comment by ja5h** [comment]
History of previous shell commands is not updated:

![screenshot from 2015-05-11 18 09 31](https://cloud.githubusercontent.com/assets/5393353/7564938/21b03a48-f809-11e4-9dfa-0cc08949ee73.png)


But it would be great if it would be updated so that we could use <up> key to use the previous commands.

**Comment by a-x-** [comment]
I update alias and installation now and caused new issue with history: vanishing!

**Comment by a-x-** [comment]
1)
```sh
ssh $server_domain
```
2)
```sh
history 2
```
```
ls
exit
```
3)
```sh
gitt
fuck
```
```
git
...
```
4)
`<up>`
```
exit
```

**Comment by nvbn** [comment]
Is it reproduces with current version?

**Comment by a-x-** [comment]
Yeah! Thx you!
