### ISSUE TITLE
Installation probably causes an Exception

### ISSUE THREAD

**Issue by ja5h** [nvbn/thefuck#176]
This is something that I found recently.

I use 'bashit' and tried using 'git clone' followed by the developer installation instructions.

*Detailed process as follows:*
1. Bashit installed successfully.
2. git clone: thefuck was downloaded as expected.
3. Installed requirements succesfully.
4. python setup.py develop: Did the installation. No errors reported.
5. added alias line to '.bashrc'
6. Restarted shell session.

However I expect if the installation was successful, the fuck command would work properly.

But an exception was thrown:
>Traceback (most recent call last):
> File "/usr/local/bin/thefuck", line 9, in <module>
>   load_entry_point('thefuck==1.38', 'console_scripts', 'thefuck')()
> File "/home/jash/Github/thefuck/thefuck/main.py", line 129, in main
>   command = get_command(settings, sys.argv)
> File "/home/jash/Github/thefuck/thefuck/main.py", line 81, in get_command
>   script = shells.from_shell(script)
> File "/home/jash/Github/thefuck/thefuck/shells.py", line 106, in from_shell
>  return _get_shell().from_shell(command)
> File "/home/jash/Github/thefuck/thefuck/shells.py", line 28, in from_shell
>   return self._expand_aliases(command_script)
>  File "/home/jash/Github/thefuck/thefuck/shells.py", line 19, in _expand_aliases
>   aliases = self._get_aliases()
> File "/home/jash/Github/thefuck/thefuck/shells.py", line 62, in _get_aliases
>   for alias in proc.stdout.read().decode('utf-8').split('\n')
> File "/home/jash/Github/thefuck/thefuck/shells.py", line 63, in <genexpr>
>   if alias)
> File "/home/jash/Github/thefuck/thefuck/shells.py", line 53, in _parse_alias
>   name, value = alias.replace('alias ', '', 1).split('=', 1)
> ValueError: need more than 1 value to unpack

Is it a problem or am I doing something wrong?

**Comment by nvbn** [comment]
Try to upgrade to 1.39, probably fixed.

**Comment by ja5h** [comment]
Solved, thanks.

Turns out it was due to false alias checking caused by some warnings in bash-it.

Great job fixing it. @nvbn :)
