### ISSUE TITLE
Bug: 'thefuck' messes up 'history' on executing 'fuck'

### ISSUE THREAD

**Issue by ja5h** [nvbn/thefuck#180]
Here is what happens when I use the 'history' command followed by 'fuck':
![screenshot from 2015-05-11 18 13 08](https://cloud.githubusercontent.com/assets/5393353/7564975/91d7e1a4-f809-11e4-8cf7-1735194d1188.png)

The output expected is "No fuck given" since 'history' is a valid command.

This could possibly have to do with priorities as discussed in #154 (Just a hunch).

**Comment by ja5h** [comment]
Should we write a rule for the history command seperately?

**Comment by ja5h** [comment]
I have an idea (but I am still thinking of how to implement it).

What if we try to implement a function that checks if the previous command executed is having an exit code of 0 i.e. it executed successfully? If the command executed successfully we simply avoid 'thefuck' rules and print 'No fuck given'.

This will also help resolve the infinite loop problem in #147. Since the command will execute successfully once, 'thefuck' will stop in the second iteration itself. Thus leading to avoidance of an infinite loop.

We could use an environment variable like `$?` for this (at least this works in bash) as it stores the value of exit code of previous command.

**Comment by underscorejho** [comment]
Is that possible? That sounds like a more valid way of checking for console typos than to immediately check every rule.

**Comment by nvbn** [comment]
The way of handling history was changed in previous releases.
