### ISSUE TITLE
&& operator PowerShell

### ISSUE THREAD

**Issue by Vennik** [nvbn/thefuck#182]
With the following 2 commands it will fail:
`git checkout fbskldflds`
`fuck`

**Comment by scorphus** [comment]
@Vennik I am extending thefuck's support to other shells, such as Fish and PowerShell. What is the corresponding `&&` operator (`AND`, for instance) in PowerShell?

**Comment by Vennik** [comment]
This will work:
http://stackoverflow.com/questions/563600/can-i-get-to-work-in-powershell

**Comment by scorphus** [comment]
Good enough. Thank you!

What do you think about contributing code to the project? Would you be interested in improving thefuck's support to PowerShell?

**Comment by Vennik** [comment]
Yea that will be interesting. I'll take a look.

**Comment by scorphus** [comment]
Great! This is what I've been doing regarding Fish Shell:

https://github.com/scorphus/thefuck/commit/018ea864318112789c0324a0c035f847b528245b 

It's a work in progress (WIP) and there's some aspects of it I still want to change or improve. As soon as I have some free time I'll try and do so.

**Comment by nvbn** [comment]
Fixed in previous releases.
