### ISSUE TITLE
thefuck-alias writes to stderr

### ISSUE THREAD

**Issue by and-dmitry** [nvbn/thefuck#184]
thefuck-alias seems to write to stderr instead of stdout, so the command from README does not change `.bashrc`:

```
$ thefuck-alias >> ~/.bashrc

alias fuck='eval $(thefuck $(fc -ln -1))'
```

Of course one could just type `$ thefuck-alias 2>> ~/.bashrc` but it doesn't feel right.

**Comment by SanketDG** [comment]
I implemented `thefuck-alias` and I am pretty sure it works. It simply prints out in the terminal, so it should go to to `stdout`.

**Comment by SanketDG** [comment]
Thanks for pointing that out! I had implemented `thefuck-alias` and I must have missed it through.

**Comment by SanketDG** [comment]
Um, yeah, it is because it was being returned through a function. Will work okay after #185 is merged.

**Comment by nvbn** [comment]
Currently it writes to stdout:
```bash
➜  thefuck-alias > out
➜  cat out

TF_ALIAS=fuck alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

```
