### ISSUE TITLE
Alias for TCSH

### ISSUE THREAD

**Issue by HughMacdonald** [nvbn/thefuck#189]
This is kind of an issue, kind of a solution...

This appears to work as an alias for TCSH:

    alias fuck 'set fuckedCmd=`history -h 2 | head -n 1` && eval `thefuck ${fuckedCmd}`'

**Comment by nvbn** [comment]
In which file it should be?

**Comment by HughMacdonald** [comment]
It looks like proper tcsh support is more involved, and needs changes made to shells.py

I've done a fork, and I'll look at getting a pull request together

**Comment by nvbn** [comment]
Ok, cool =)

**Comment by HughMacdonald** [comment]
Hmm - the one thing I can't get working is re-writing of the tcsh history. Even though loads of places mention ~/.history, this doesn't seem to be the active history file. Other than that, it's all working, though

**Comment by HughMacdonald** [comment]
I'll put in a pull request - you can grab or not as you'd like
