### ISSUE TITLE
Installation Documentation is Wrong

### ISSUE THREAD

**Issue by dylankarr** [nvbn/thefuck#195]
The installation page on the wiki says to run the follow command to install on Mac OS X:

```
brew install thefuck
```

But this is response when the command is run:

```
Error: No available formula for thefuck
Searching formulae...
Searching taps...
```

**Comment by dunn** [comment]
When did you last run `brew update`? What's the output of `brew doctor`?

**Comment by dylankarr** [comment]
Oops. Now I feel stupid.

**Comment by dunn** [comment]
No, I think Homebrew could be better about reminding people to update regularly!
