### ISSUE TITLE
I've been using fuck since the first release, since 1.16 it has not worked for me.

### ISSUE THREAD

**Issue by detonation** [nvbn/thefuck#207]
I keep updating every few days trying to see if it gets fixed, but it hasn't worked for me since 1.14?

It gives errors similar to the newest version: 

Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.main import main
  File "/usr/local/lib/python3.2/dist-packages/thefuck/main.py", line 10, in <module>
    from . import logs, conf, types, shells
  File "/usr/local/lib/python3.2/dist-packages/thefuck/logs.py", line 16
    u'{warn}[WARN] {title}:{reset}\n{trace}'
                                           ^
SyntaxError: invalid syntax

It's been that way since 1.16 update.. I kind of miss it. I had even written tons of rules, but trying to get it working I moved them all out, deleted the local config/rules folder, etc. Still no-go. Any ideas?

**Comment by QuantumQweef** [comment]
I just starting using thefuck not too long ago and have noticed active development here on gh, but unfortunately, this has never worked for me :/

**Comment by mcarton** [comment]
`thefuck` supports Python 2.7, 3.3 and 3.4. You are using Python 3.2 which does not support the `u''` form of string literals (it was a Python 2 syntax, removed in Python 3 because it was useless (Python 3 strings are always unicode) and re-added in Python 3.3 for portability with Python 2).
You should upgrade your Python version.

**Comment by detonation** [comment]
Hi, this is on my rpi2. I have python 2.7 and 3.2 which is the newest via
apt on raspbian. How do I make it use 2.7?

**Comment by nvbn** [comment]
@dannion you should run something like:
```bash
sudo pip3 uninstall thefuck
sudo pip2 install thefuck
```

**Comment by scorphus** [comment]
@detonation Did it work for you?
