### ISSUE TITLE
no_command rule does not know about shell functions/aliases

### ISSUE THREAD

**Issue by devkev** [nvbn/thefuck#209]
As a result, it can offer inappropriate/uesless suggestions - since the shell will execute aliases/functions ahead of commands, it's highly likely that *that's* what the user actually wanted.

**Comment by scorphus** [comment]
Yeah, that's the next improvement I'll propose! As soon as the [latest improvements to shell](https://github.com/nvbn/thefuck/pull/206) are merged.

**Comment by scorphus** [comment]
Awesome, @nvbn! I'll examine it more closely and support Fish functions if they're not supported yet.

**Comment by scorphus** [comment]
UPDATE: support to Fish functions is on the way... :wink:

**Comment by devkev** [comment]
This code spawns a new shell and gets the aliases from it.  This is fine for the common case of stuff defined in shell startup scripts, but not for any subsequently defined things.  Unfortunately I don't think it's generally possible for a sub-process to interrogate the parent shell as to the aliases it has (unless they were to be passed in somehow by the `fuck` alias).

Similarly, exported functions can easily be found in the sub-process environment, but this isn't the case for non-exported functions.  Again, the approach of spawning a new shell and seeing what functions it has will probably suffice, although it will miss some things.

**Comment by scorphus** [comment]
Please check #215

**Comment by nvbn** [comment]
Currently the rule supports aliases.
