### ISSUE TITLE
Running fuck just after nano freezes the shell

### ISSUE THREAD

**Issue by theneva** [nvbn/thefuck#21]
`$ nano whateverfile`, quitting Nano, and immediately running `fuck` freezes the entire shell (zsh with ohmyzsh) on OSX 10.10 (developer preview FWIW – I never bothered to install the stable version).

![image](https://cloud.githubusercontent.com/assets/1404650/7215072/7cd12e14-e5c6-11e4-8dfa-72b7034d28fb.png)

**Comment by dennisdegreef** [comment]
`Ctrl+D` returns the shell context, claiming `^DNo fuck given`.

**Comment by theneva** [comment]
Well, sure, but it still seems like a bug. I guess it doesn't really freeze the *shell*, though.

**Comment by nvbn** [comment]
Is it repeats with 1.11+?

**Comment by playinggod** [comment]
On 1.11 it freezes for 5 seconds and gives such output:

>No fuck given
             ⏎

OS X 10.10.3, fish shell

**Comment by theneva** [comment]
Seems fixed to me!
