### ISSUE TITLE
correct 'open' command on Mac to open browser

### ISSUE THREAD

**Issue by zag2art** [nvbn/thefuck#210]
```bash
zag2art@laptop:~/workfiles/docclean$ open github.com
The file /Users/zag2art/workfiles/docclean/github.com does not exist.
Perhaps you meant 'http://github.com'?
zag2art@laptop:~/workfiles/docclean$ fuck
No fuck given
```
Can someone add the case into rules? It should fire `open http://github.com` in my case. Sorry, don't know python.

**Comment by scorphus** [comment]
This issue is fixed by https://github.com/nvbn/thefuck/commit/d3146aa0aca57522820f5bdb0a22f5b248de407e and can be closed.
