### ISSUE TITLE
Cannot install on mac using brew

### ISSUE THREAD

**Issue by jonibatista** [nvbn/thefuck#213]
The `brew install thefuck`is not working here. 

There isn't any formula found for **thefuck** (`brew search thefuck`).

**Comment by DomT4** [comment]
Make sure your Homebrew is up-to-date.

**Comment by evils** [comment]
```
brew update && brew install thefuck
```

Should help you

**Comment by scorphus** [comment]
@jonibatista ping, any update on this?

**Comment by jonibatista** [comment]
It's working fine for me now :)

Sorry for taking so long to replay @scorphus

**Comment by SanketDG** [comment]
@jonibatista If your issue has been resolved, you can close this issue. :)
