### ISSUE TITLE
thefuck doesn't work with an alias that starts with zsh shell keyword

### ISSUE THREAD

**Issue by emptyaitch** [nvbn/thefuck#222]
I have the following alias in my .zshrc:

alias mkdir='nocorrect mkdir -p'

`thefuck mkdir /nopermissions` uses the no_command rule, because running it through /bin/sh outputs "command not found" for nocorrect (a zsh keyword)

**Comment by scorphus** [comment]
This is related to #262 and its fix should apply to this as well. I'll soon open a pull request.
