### ISSUE TITLE
cd_mkdir rule on OSX does not chain correctly

### ISSUE THREAD

**Issue by thurstonsand** [nvbn/thefuck#235]
when running
"cd asdf"
"fuck"  
  
command "mkdir -p asdf && cd asdf" creates folders asdf, &&, and cd.
Running the command manually acts as intended, so it is specifically thefuck that is causing behavior

**Comment by scorphus** [comment]
Hello, @thurstonsand. What shell do you use? What version of thefuck is installed?

Thanks.

**Comment by thurstonsand** [comment]
I am on OSX, GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)

**Comment by thurstonsand** [comment]
v1.46 for thefuck

**Comment by scorphus** [comment]
That's odd. What does your alias look like?

**Comment by thurstonsand** [comment]
alias fuck='$(thefuck $(fc -ln -1))'

**Comment by scorphus** [comment]
How does it behave if you set the alias as the following?
```bash
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
```
`eval` being the main difference here.

**Comment by scorphus** [comment]
Ah, I forgot to mention, that alias is exactly what the command `thefuck-alias` gives you :wink:

**Comment by thurstonsand** [comment]
Yep that fixed things. Thanks for the help! Did my alias use to be what thefuck used, because I'm pretty sure I copied it into my bashrc file on install

**Comment by scorphus** [comment]
@thurstonsand I'm glad it works! Can you please close this issue? Thanks.

**Comment by thurstonsand** [comment]
oh sorry didn't realize that was on me
