### ISSUE TITLE
`thefuck/thefuck/rules/no_command.py` is not cross-platform

### ISSUE THREAD

**Issue by skyhighwings** [nvbn/thefuck#24]
[`thefuck/thefuck/rules/no_command.py`](https://github.com/nvbn/thefuck/blob/master/thefuck/rules/no_command.py) blindly looks for `/usr/lib/command-not-found` which does not exist on Windows, OS X, or a great many Linux distributions (Debian, for example).

I'd like to suggest a more cross-platform method of finding the correct command:
 - enumerate the list of executables (almost certainly by walking `$PATH` [or running `hash` if you have a `$SHELL` instance])
  - This would be a great chance to also run `alias` in `$SHELL` and get the list of aliases, too.
 - find the lowest Levenshtein distance from `original_command` amongst the list
 - return it

This should make this glorious project even more useful to all the sysadmins on SpecialSnowflakeCustomLinuxDistro and maybe even those stuck on Windows.

**Comment by nvbn** [comment]
There's a settings `command_not_found` for path to `command-not-found`.

**Comment by skyhighwings** [comment]
Are you suggesting that instead of a properly generic method, the correct path is instead simply using `command-not-found`?

**Comment by academo** [comment]
I think this is related to https://github.com/nvbn/thefuck/issues/2 and https://github.com/nvbn/thefuck/issues/23

**Comment by academo** [comment]
@skyhighwings  @nvbn  I found an implementation of command not found https://github.com/bfontaine/homebrew-command-not-found but it is not actually trying to correct command names but only suggesting to install packages you don't have if you write the right name.

**Comment by skyhighwings** [comment]
@academo yes, it is related to those :-)

I'd be willing to write a Levenshtein-based command finder later, but I don't know Python nearly as well as I do other languages.

**Comment by academo** [comment]
@skyhighwings I think you can write them in other languages and then run it into python I don't know python either.

**Comment by rperce** [comment]
Ah ha! This is perhaps why it doesn't work on Arch Linux.

**Comment by skyhighwings** [comment]
@rperce that is precisely why it doesn't work on Arch, actually!

**Comment by cdipaolo** [comment]
I'd love to do this, but I won't be able to do it until this coming weekend. Lot's of work going on. If the timing is a problem let me know and somebody else can take it. 

#### Heres the implementation I think would work best. Suggestions would be welcome:

1. do a $PATH walk and store all executable binaries on a CSV file with a timestamp.
    - include ```alias``` names in CSV list
2. on ```fuck```, check if the timestamp is older than some config variable (default 7 days.)
3. if it is older, then rewalk the $PATH.
4. if current, calculate the minimum Lavenstein distance from the CSV list of commands 
    - if, while running through the commands, the current minimum is 1 insertion/deletion/modification, then return that command
5. either ask the user or just run the command


![jpeg image-be3727156eaf-1](https://cloud.githubusercontent.com/assets/9327606/7221422/351cbea6-e69f-11e4-98ab-5777eea9f45d.jpeg)

**Comment by nvbn** [comment]
@cdipaolo, cool idea, thanks. I've implemented something similar, but a bit simpler.

Should be crossplatform in 1.18+.

**Comment by skyhighwings** [comment]
:+1:
