### ISSUE TITLE
Dependencies on psutils and python-psutil are not present in install procedures

### ISSUE THREAD

**Issue by igorsantos07** [nvbn/thefuck#242]
I've just installed the latest release of Linux Mint, and when running `sudo pip install thefuck` it gave me an error, that fiddling with I discovered I needed to install `psutils` and `python-psutil` through `apt-get`. After that I uninstalled thefuck and installed again, and it went fine.

Not submitting a PR since I'm not sure if this should be added to the README, wiki, or both (or neither?).

**Comment by scorphus** [comment]
This one is somehow related to #220.

**Comment by pradyunsg** [comment]
No, it is not.

#220 is about the usage of sudo with pip.

This is about the wrong/incomplete dependencies of the package, probably in the Ubuntu's repositories.
