### ISSUE TITLE
Console feedback in examples

### ISSUE THREAD

**Issue by bartonfriedland** [nvbn/thefuck#248]
In the examples from the readme, the console offers feedback, such as:

```
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```
and

```
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

      git push --set-upstream origin master
```

As far as I can see, these do not come from this package. Which package provides this feedback?

Thanks,

Barton

**Comment by SanketDG** [comment]
@bartonfriedland The first one happens, when you try to install something using `apt-get` without sudo permission in Debian/Ubuntu based distros.

The second one comes from [git](https://git-scm.com/), which is a [distributed version control system](http://en.wikipedia.org/wiki/Distributed_revision_control).

**Comment by bartonfriedland** [comment]
Thanks for that @SanketDG. When I type "puthon", since I use zsh, I get 

```
zsh: command not found: puthon
```

but I do not get 

```
No command 'puthon' found, did you mean:
 Command 'python' from package 'python-minimal' (main)
 Command 'python' from package 'python3' (main)
```

Where do those additional messages come from?

**Comment by SanketDG** [comment]
Strange, even I do not get these. They probably appear when they are not installed. In our cases, it's installed. Although I am not sure about this.

**Comment by bartonfriedland** [comment]
Well, that's somewhat reassuring. I thought there was some package out there that gave all this feedback.

**Comment by mlk** [comment]
It is part of the ubuntu command-not-found package.

https://launchpad.net/ubuntu/+source/command-not-found

**Comment by SanketDG** [comment]
@bartonfriedland Looks like this issue can be closed.

**Comment by bartonfriedland** [comment]
For OS X, this package is also available as https://github.com/Homebrew/homebrew-command-not-found. Thanks, @mlk!
