### ISSUE TITLE
Infinite loop when excuting itself

### ISSUE THREAD

**Issue by Harry-Chen** [nvbn/thefuck#258]
When I run something like 'fack' and use thefuck, it will go into an infinite loop of running 'fuck'.
And when I try to use Ctrl+C to terminate the command, it will cause lots of Python exceptions.
Like this.
![qq 20150619210451](https://cloud.githubusercontent.com/assets/2819727/8253960/0af0df60-16c7-11e5-9e4d-6015810aea23.png)
![qq 20150619210510](https://cloud.githubusercontent.com/assets/2819727/8253961/0b0f5fee-16c7-11e5-9feb-25cc080d96f0.png)

**Comment by scorphus** [comment]
Thanks for reporting, @Harry-Chen. This problem is solved in master and will be available in the next, upcoming release.

**Comment by Harry-Chen** [comment]
Thanks for the reply.
