### ISSUE TITLE
The Fuck, fuck is not working with zsh

### ISSUE THREAD

**Issue by nekoexmachina** [nvbn/thefuck#26]
http://i.imgur.com/4hUFqBe.png

**Comment by nekoexmachina** [comment]
Other options that should've been corrected:
neko@takinolap ‹ master › : ~/src/thefuck
[0] % pacman -S kde
error: you cannot perform this operation unless you are root.

neko@takinolap ‹ master › : ~/src/thefuck
[1] % thefuck      
echo No fuck given

etc.

Nothing except for "no fuck given" yet.

**Comment by vikstrous** [comment]
Read the README.

You need this in your .zshrc:
```
alias fuck='$(thefuck $(fc -ln -1))'
```

The command you want to run is `fuck`, not `thefuck`.

**Comment by nekoexmachina** [comment]
Okay, sorry mr visktrous. Still no luck:
```
neko@takinolap : ~
[0] % pacman -S kde
error: you cannot perform this operation unless you are root.

neko@takinolap : ~
[1] % fuck
No fuck given

neko@takinolap : ~
[0] % which fuck
fuck: aliased to $(thefuck $(fc -ln -1))

neko@takinolap : ~
[0] % lls
zsh: command not found: lls

neko@takinolap : ~
[127] % fuck
No fuck given

neko@takinolap : ~
[0] % puton
zsh: command not found: puton

neko@takinolap : ~
[127] % fuck
No fuck given

neko@takinolap : ~
[0] % puthon
zsh: command not found: puthon

neko@takinolap : ~
[127] % fuck
No fuck given
```
