### ISSUE TITLE
Fuck not working on linux

### ISSUE THREAD

**Issue by zakiaziz** [nvbn/thefuck#260]
I've installed it into my mac and works just fine. But running it on a linux shell I've SSH'd into returns this:

[user@machine]$ git statis
git: 'statis' is not a git command. See 'git --help'.

Did you mean this?
	status
[user@machine]$ fuck
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: colorama

**Comment by SanketDG** [comment]
How did you install it?

**Comment by zakiaziz** [comment]
`sudo pip install thefuck`

then `vi ~/.bashrc` and added this line: `alias fuck='eval $(thefuck $(fc -ln -1)); history -r'`

**Comment by SanketDG** [comment]
What OS are you on?

**Comment by SanketDG** [comment]
You can try `pip install --upgrade colorama` and then see if it works.

**Comment by zakiaziz** [comment]
My OS info: centos-release-6-6.el6.centos.12.2.x86_64

`pip install --upgrade colorama` did not solve the issue for me

**Comment by nvbn** [comment]
App requires python 2.7+ or 3.3+.
Python 2.6 isn't supported.

**Comment by zakiaziz** [comment]
Thanks @nvbn
