### ISSUE TITLE
Doesn't work at all on Fedora 21

### ISSUE THREAD

**Issue by tjhorner** [nvbn/thefuck#266]
When I misspell a command or use git incorrectly, it doesn't correct it.

![image](https://cloud.githubusercontent.com/assets/2646487/8424184/58a86b9c-1eab-11e5-8414-4155bf47b43f.png)

**Comment by bugaevc** [comment]
You should add alias `fuck='something thefuck something'` and then use just `fuck`, see README fot more details

**Comment by tjhorner** [comment]
I do have an alias as `fuck`, that doesn't work either.

**Comment by bugaevc** [comment]
Make sure your alias is set up exactly as [this page](https://github.com/nvbn/thefuck/wiki/Shell-aliases) recommends.
