### ISSUE TITLE
Add mercurial (hg) support

### ISSUE THREAD

**Issue by seyfer** [nvbn/thefuck#269]
Example

```
hg branchch
hg: unknown command 'branchch'
(did you mean one of branch, branches?)
```

```
fuck
No fuck given
```

Expected
```
hg branch
```

**Comment by scorphus** [comment]
I once tried to add support to Mercurial, but it turned out its error messages were not that useful. But new 3.4 version improves on that. So, I'll dig this one. Thanks for spotting it, @seyfer! :+1:

**Comment by scorphus** [comment]
WIP @ [mercurial](/scorphus/thefuck/tree/mercurial)
