### ISSUE TITLE
What's the default priority?

### ISSUE THREAD

**Issue by mathifonseca** [nvbn/thefuck#270]
I'm trying to define a new rule, but one of the defaults always gets in the middle. I tried setting the priority of my rule as 1 (even 0), but nothing works. The only workaround is lowering the priority of the default one in the global settings.

**Comment by bugaevc** [comment]
`DEFAULT_PRIORITY = 1000`
Found [here](https://github.com/nvbn/thefuck/blob/master/thefuck/conf.py#L25), used [here](https://github.com/nvbn/thefuck/blob/master/thefuck/main.py#L30)

**Comment by mathifonseca** [comment]
Yes, I've seen that lines, but I think they aren't working for custom rules.

The default rule `ls_lah.py` doesn't have a priority defined, so it should be 1000, right?

My custom rule has this: `priority = 10`

That should mean that my rule has a higher priority, but that's not what's happening. 

However, if I change the priorities in the `settings.py` file, it works correctly:

`priority = {'grails': 100, 'ls_lah': 9999}`

**Comment by mcarton** [comment]
How do you use priorities?
They definitely work, for example I set the priority in the [DRY rule](https://github.com/nvbn/thefuck/blob/master/thefuck/rules/dry.py) and I get:
```
% cd cd foo
cd: string not in pwd: cd
% fuck
cd foo [enter/ctrl+c]
```
If priority is not set in that rule I get:
```
% cd cd foo
cd: string not in pwd: cd
% fuck
mkdir -p cd toto && cd cd toto [enter/ctrl+c]
```
Which is the `cd_mkdir` rule.

**Comment by mathifonseca** [comment]
This is my `match` function, with `priority = 10`:

```python
def match(command, settings):
    return re.search('command not found: [grails]', command.stderr.lower())

...

priority = 10
```

But it conflicts with the `ls_lah` match:

```python
def match(command, settings):
    return 'ls' in command.script and not ('ls -' in command.script)
```

It only takes mine when I set the priorities in `settings.py`

**Comment by nvbn** [comment]
I tested with a dummy rule:
```python
def match(command, settings):
    return True


def get_new_command(command, settings):
    return 'echo works'

priority = 10
```
And it works:
```bash
➜ git brnch
git: 'brnch' is not a git command. See 'git --help'.

Did you mean this?
	branch
➜ fuck
echo works [enter/ctrl+c]
works
```
What's in your `settings.py`?

**Comment by mathifonseca** [comment]
Mhm... it seems the bug has been fixed magically, because I reinstalled thefuck and now it works as expected.

Here are some tests:

```
➜  garils run-app
zsh: command not found: garils
➜  fuck
grails run-app [enter/ctrl+c]
➜  gails run-app
zsh: command not found: garils
➜  fuck
grails run-app [enter/ctrl+c]
➜  gralis run-app
zsh: command not found: gralis
➜  fuck
grails run-app [enter/ctrl+c]
```
