### ISSUE TITLE
[n1c @ yard]->pacman -S binutils

### ISSUE THREAD

**Issue by 0x2F** [nvbn/thefuck#271]
=)

[09:52 AM] - { ~/tmp }
[n1c @ yard]->pacman -S binutils
error: you cannot perform this operation unless you are root.
[09:52 AM] - { ~/tmp }
[n1c @ yard]->fuck
ls -lah -S binutils
ls: cannot access binutils: No such file or directory
[09:52 AM] - { ~/tmp }
[n1c @ yard]->

**Comment by scorphus** [comment]
Thanks for reporting it, @0x2F :+1:
