### ISSUE TITLE
Running alias

### ISSUE THREAD

**Issue by fzerorubigd** [nvbn/thefuck#28]
I create a simple rule for my own usage here : https://gist.github.com/fzerorubigd/c8b53fa3231f28f40092 

Some time, I type command in another keyboard layout, (as you can see, persian) and I want to use fuck to fix that (I already build a command not found handler, but fuck is better :) ) 
the problem is, if I use an alias, then the result is detected, but it can not execute it : 
```
$ alias tst=ls
$ فسف 
zsh: command not found: فسف
$ fuck
tst
zsh: command not found: tst
```

I use zsh 5.0.7 and python 3.4.3 (Archlinux) with thefuck from comunity (and also tested against the master branch and the pip version)

**Comment by nvbn** [comment]
It's almost not possible to work with aliases.

But you can add your layout to https://github.com/nvbn/thefuck/blob/master/thefuck/rules/switch_lang.py#L5

**Comment by fzerorubigd** [comment]
Thanks, I am sure there is no switch lang when I write that rule :) .
