### ISSUE TITLE
"fuck" seems to hang until I press CTRL+C, then it works

### ISSUE THREAD

**Issue by MadaraUchiha** [nvbn/thefuck#280]
Whenever I use `fuck`, it seems to freeze indefinitely. I press CTRL+C to interrupt and then it seems to "wake up" and do whatever it was it was supposed to do.

```
> $ git push
fatal: The current branch mybranch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin mybranch

> $ fuck # Now it hangs
^C
git push --set-upstream origin feature/DEV-4186-spring-config-location-doesnt-apply
```

Not sure what is causing this. I'm running zsh (with oh-my-zsh) on Ubuntu 15.04. I have another laptop running on the exact same configuration which does not produce this phenomenon.

How can I start debugging this?

**Comment by scorphus** [comment]
As I suspect another rule is making it hangs, I'd suggest you placing a breakpoint in the `get_matched_rule()` method of `main.py` and see if you find out which one it is. A good read depending on your experience debugging python programs: https://blog.safaribooksonline.com/2014/11/18/intro-python-debugger/

**Comment by nvbn** [comment]
Something like this should print debug information in 1.49+:
```
export THEFUCK_DEBUG=true
git push
fuck
```

**Comment by MadaraUchiha** [comment]
It seems to have solved itself in one of the updates since I've opened this
ticket. Thanks :)
