### ISSUE TITLE
brew does not show the latest thefuck

### ISSUE THREAD

**Issue by unluisco** [nvbn/thefuck#286]
![1 unluisco macbook-pro-de-luis-alfredo zsh 2015-07-12 13-37-02](https://cloud.githubusercontent.com/assets/6332263/8639299/5e28020e-289b-11e5-9e98-2dd1caec6bb4.png)

**Comment by jdoerrie** [comment]
Not an issue:

```bash
$ brew info thefuck
thefuck: stable 1.48 (bottled), HEAD
Programatically correct mistyped console commands
https://github.com/nvbn/thefuck
/usr/local/Cellar/thefuck/1.48 (186 files, 1.2M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/thefuck.rb
==> Caveats
Add the following to your .bash_profile or .zshrc:
  bash: alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
  zsh: alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

  Other shells: https://github.com/nvbn/thefuck/wiki/Shell-aliases
```

Maybe you need to run `brew update`?

**Comment by unluisco** [comment]
I was doing everything to install version 1.47 but nothing worked, has now worked well installation, thanks

PS: For that reason it is necessary to add that line in my .zshrc?

**Comment by jdoerrie** [comment]
Yes, you should add 
```bash 
alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
```
 to your .zshrc in order to be able to use `fuck` to correct your commands.

**Comment by nvbn** [comment]
Is this issue can be closed?

**Comment by unluisco** [comment]
if, although it seems that brew manually update it, because it tells me that 1.48 is the latest version

**Comment by jdoerrie** [comment]
Yes, this issue can be closed, it wasn't an issue to begin with. Homebrew is simply lacking behind:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/thefuck.rb

**Comment by DomT4** [comment]
If someone wants to submit a PR to update the formula, that'd be welcome!

**Comment by scorphus** [comment]
Done: https://github.com/Homebrew/homebrew/pull/41997

Thanks, @DomT4

**Comment by nvbn** [comment]
Thanks, @scorphus

**Comment by scorphus** [comment]
My pleasure!

**Comment by scorphus** [comment]
The Homebrew `thefuck` formula is up-to-date!
