### ISSUE TITLE
OSX: "ImportError: No module named pathlib"

### ISSUE THREAD

**Issue by alexmwu** [nvbn/thefuck#287]
Hi, I'm trying to install and I get this error:

```
$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.main import main
  File "/Library/Python/2.7/site-packages/thefuck/main.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

I tried updating setup by following the instructions in #218.
Running OSX 10.10.4, Python 2.7.6, and pip 7.1.0.
Any ideas?

**Comment by AbdoulNdiaye** [comment]
I tried 
```sh

**Comment by jonathan-villemot** [comment]
:+1:  Worked for me too.

**Comment by paulagent** [comment]
Worked for me too. thx

**Comment by alexmwu** [comment]
Oh well, that makes a lot of sense. It works now, thanks a lot!

**Comment by Aaron3154518** [comment]
What is "pip" in sudo pip install pathlib?

**Comment by m0caa** [comment]
> I tried
> 
> ```shell
> sudo pip install pathlib
> ```
> 
> and it works for me :)

THANK YOU

**Comment by dopdahl16** [comment]
Should `pathlib` be added as a dependency in the documentation?

**Comment by ShyamSundarAgwl** [comment]
I tried but it didn't worked.
Can you help me with any other solution?

**Comment by PKQRAA** [comment]
> ```shell
> sudo pip install pathlib
> ```

ImportError: No module named utils.console
