### ISSUE TITLE
Should be able to use a dry run option

### ISSUE THREAD

**Issue by jdahern** [nvbn/thefuck#3]
So that I know what will be ran

fuck --dry-run

**Comment by LaMi-** [comment]
Maybe try https://github.com/nvbn/thefuck/issues/1#issuecomment-94062948

**Comment by braco** [comment]
Yeah, it would be nice to have a "run command" [Y/n]: prompt before executing. I would not use this without some confirmation. So many bad things can happen in shell.

**Comment by braco** [comment]
https://github.com/nvbn/thefuck/pull/7

**Comment by Cassum** [comment]
By the way, this would solve an alias problem (with another $(..) in .bashrc)
