### ISSUE TITLE
"' is not a git command." Using Cygwin on Windows 7

### ISSUE THREAD

**Issue by LoLei** [nvbn/thefuck#300]
![image](https://cloud.githubusercontent.com/assets/9076894/8795640/dab1ad30-2f8e-11e5-9019-09ea2ac94978.png)

Happening with all git commands, could not think of another command to test.

---

EDIT: I'm not using Windows anymore, but I''ll leave this open, as it seems other people have the same problem.

**Comment by erykpiast** [comment]
anyone could help with this? it makes me sad :(

**Comment by RedX2501** [comment]
@LoLei How did you manage to install psutil under cygwin?

**Comment by LoLei** [comment]
@RedX2501 Sorry, I can't remember, and I'm not using Windows anymore.

**Comment by RichardBradley** [comment]
See https://github.com/SnoringFrog/thefuck-cygwin
