### ISSUE TITLE
no_command rule doesn't know about dynamically defined aliases/functions

### ISSUE THREAD

**Issue by devkev** [nvbn/thefuck#305]
If you define an alias `foo` on the command line by doing

```
alias foo="echo foo"
```

then this won't be a suggestion for a typo like `fooo`.  Similarly for a function

```
function foo { echo foo; }
```

This is counter intuitive when the following works just fine (assuming `$HOME/bin` is in your `$PATH`)

```
echo echo foo > $HOME/bin/foo
chmod +x $HOME/bin/foo
```

Fixing this is basically impossible with thefuck's current design (which is "spawn a new shell and see what alias/functions it has").  Supporting this use case would require substantial help from the alias to be able to know these things about the current shell environment, and then possibly also assistance for actually running the alias/function.

See also https://github.com/nvbn/thefuck/issues/209#issuecomment-104093437.

**Comment by scorphus** [comment]
Works for aliases. For functions please follow #675.
