### ISSUE TITLE
dkms autoinstall

### ISSUE THREAD

**Issue by 0x2F** [nvbn/thefuck#308]
[n1c @ yard]->dkms autoinstall
Error! You must be root to use this command.
[09:02 AM] - { ~ }
[n1c @ yard]->fuck
No fuck given

**Comment by mcarton** [comment]
[*must be root* is present](https://github.com/nvbn/thefuck/blob/master/thefuck/rules/sudo.py#L13) in the `sudo` rule so it already works:
```latex
% dkms autoinstall
Error! You must be root to use this command.
% fuck
sudo dkms autoinstall [enter/ctrl+c]
```
Maybe you have not upgraded `thefuck` for a while?

**Comment by 0x2F** [comment]
Yup, upgrade fixed the issue, sorry for reporting it :)
