### ISSUE TITLE
No description appears on pypi page.

### ISSUE THREAD

**Issue by SanketDG** [nvbn/thefuck#311]
Currently, [https://pypi.python.org/pypi/thefuck](https://pypi.python.org/pypi/thefuck)'s description remains empty. There is two possible ways to fix that (i.e. to display README there):

- Create `[metadata]` in setup.cfg #312 
- Convert README.md to README.rst so that it displays automatically.

@nvbn thoughts?

**Comment by nvbn** [comment]
I added convertation from md to rst with pandoc.

**Comment by SanketDG** [comment]
Wow, that's another approach entirely. Thanks. Just a small note, on the [page](https://pypi.python.org/pypi/thefuck) it looks like it failed to parse the first link.
