### ISSUE TITLE
Support other languages/locales than English

### ISSUE THREAD

**Issue by tuxayo** [nvbn/thefuck#32]
I was searching why it was no giving a fuck when I was trying to use it.
Then I saw this PR:
https://github.com/nvbn/thefuck/pull/30/files

It seems that thefuck is checking for hard coded errors messages so obviously it can't work with other languages than English and the current approach can't allow it.

Any idea how to detect permission errors in a language agnostic way?
For git it should be possible to use the last line of the ouput which contains only the corrected command and nothing language specific.

**Comment by vikstrous** [comment]
I think it would be cool to use strace for detecting permission issues. It's still a heuristic, but it might be better.

Example:

```
> strace cat /etc/shadow 2>&1 | grep EACCES
open("/etc/shadow", O_RDONLY)           = -1 EACCES (Permission denied)
```

**Comment by tuxayo** [comment]
Good idea.
Can someone try with apt? With pacman it can't see EACCES with strace.

**Comment by vikstrous** [comment]
Yeah, I looked through the pacman strace and there's really nothing useful there. I wonder how it knows that you are not root. In any case, another possibility is to check that the command starts with `pacman` and returns `1`.

**Comment by nvbn** [comment]
Is it repeats with 1.11+?

**Comment by AmarOk1412** [comment]
To complete this issue. I suggest to translate the "fuck" alias. Indeed, for example, in french, "putain" can be a better alias.
Can we translate the "fuck" alias in other languages?

**Comment by Dugucloud** [comment]
Currently thefuck actually supports other languages. Because it is executed in environment with LANG=C, that means it only has to detect English strings in multilingual environment.

@AmarOk1412 It's quite simple, just add your own alias to your shell's configuration (e. g. `~/.bashrc`):
```alias putain='fuck'```
I have used `tmd` (stands for *ta ma de* in Chinese) as an alias to fuck, it works well.

**Comment by AmarOk1412** [comment]
@Dugucloud. Yeap I know. I was just thinking about an automatic alias based on the computer language :). But it's not a very good idea.

**Comment by nvbn** [comment]
@AmarOk1412 anyone can use use whatever they want for an alias.

**Comment by tuxayo** [comment]
> Is it repeats with 1.11+?
@nvbn What does this means, I didn't understood.

> Because it is executed in environment with LANG=C
@Dugucloud Where did you found that? I have to change manually my local back to english to make thefuck work

**Comment by kingwood2112** [comment]
Hey

**Comment by nvbn** [comment]
@tuxayo I mean that you need to upgrade `thefuck`:
```bash
sudo pip install thefuck --upgrade
```
