### ISSUE TITLE
doesn't seem to work with more complex commands with non-standard shells

### ISSUE THREAD

**Issue by vikstrous** [nvbn/thefuck#33]
I'm using fish shell.

This works:

```
> pacman -S python
error: you cannot perform this operation unless you are root.
> fuck
sudo pacman -S python
[sudo] password for v:
```

This fails:

```
> pacman -S (echo python)
error: you cannot perform this operation unless you are root.
> fuck
No fuck given 
```

I suspect it's trying to execute it with bash to get the output https://github.com/nvbn/thefuck/blob/235b31e176405cf8f58349580def4db198251909/thefuck/main.py#L60

Is there a way to make sure it executes with the correct shell?

**Comment by Dugucloud** [comment]
Currently, the fuck uses Python's Popen with shell=True, and it uses /bin/sh by default. If your grammar is incompatible with sh, it may cause problems.

I think one of the reason to use /bin/sh only is to have a unified output to deal with. see #98 .

There should have a magnificent way to deal with it. Hmm...

**Comment by scorphus** [comment]
Closing this one for now.
