### ISSUE TITLE
Add command options (--version, --help, --update/--upgrade)

### ISSUE THREAD

**Issue by waldyrious** [nvbn/thefuck#330]
And perhaps a manpage too, even if it only says "Please use fuck --help for documentation"

**Comment by waldyrious** [comment]
possibly using [docopt](http://docopt.org/)?

**Comment by SanketDG** [comment]
Command options can't be used in `thefuck`

**Comment by scorphus** [comment]
Yeah, that's because of TheFuck's design itself. Take `thefuck pip intall --update ipdb` for instance.

**Comment by scorphus** [comment]
However, I think a manpage is a good idea. How willing are you to contribute with this, @waldyrious?

**Comment by waldyrious** [comment]
Well, I never created a manpage and I have a vague idea that it involves a weird format and something ending in "-roff". If you give me some pointers to quickly get up to speed (for someone with zero experience in this), and an example manpage, I'd gladly contribute one for `thefuck`. Otherwise, I suspect someone else could put this together much more efficiently.

As for the content of the manpage, what could be there? If usage has no variations, and is simply "fuck" every time, perhaps authorship / contribution / bug report information, plus maybe installing / upgrading info? And maybe some usage examples and their output? Again, a sample manpage would be useful.

**Comment by waldyrious** [comment]
That said, would it really be impossible for the invocation `thefuck --option` to be recognized and dealt with appropriately? Even if not using the usual mechanism for command line options, it would be a great help in usability.

**Comment by mcarton** [comment]
I agree that every command should at least have `-h`, `-v` and a man page.
I started working on [the CLI](https://github.com/mcarton/thefuck/tree/330-cli) and [the man page](https://github.com/mcarton/thefuck/tree/330).

The CLI breaks compatibility with current aliases as it now needs `--fix`:
```latex
% thefuck --alias FUCK
TF_ALIAS=FUCK alias FUCK='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
% thefuck --fix vom
vim [enter/↑/↓/ctrl+c]
Aborted
% thefuck --help
usage: thefuck
               (--alias [NAME] | --fix CMD [CMD ...] | --help | --rules | --version)

Magnificent app which corrects your previous console command

optional arguments:
  --alias [NAME], -a [NAME]
                        output an example of alias for the current shell
  --fix CMD [CMD ...], -f CMD [CMD ...]
                        fix the given command
  --help, -h            show this help message and exit
  --rules, -r           list available rules
  --version, -v         show program's version number and exit
% thefuck --rules  
Enabled rules:
	 brew_install
	 brew_unknown_command
	 brew_upgrade
	 cargo
	 cargo_no_command
	 cd_correction
	 […]
% thefuck --version   
2.6
```
I did not use docopt as it seems a little overkill for such a simple CLI and I don't know if the `--fix` flag is possible with it.

As for the man page, it uses `pandoc` (you do *not* want to write groff files yourself):
```python
pypandoc.convert('MANUAL.1.md', 'man', outputfile='man1/thefuck.1', extra_args=['-s'])
```
or directly:
```sh
pandoc -s -t man MANUAL.1.md -o man1/thefuck.1
```
But I have no idea who to specify that in the `setup.py` file in order to install it (eg. in `/usr/[local/]share/man/man1` on linux or wherever other platform put these files).

**Comment by waldyrious** [comment]
Thanks for doing this, @mcarton. Looking at your commits, I'm now positive that it'd have taken me a long time to gather enough expertise to produce that myself :smile: that said, I'll help in whatever way I can. I've already added a few minor suggestions to some commits.

**Comment by mcarton** [comment]
Thanks, I've made the help message clearer according to your comments. Is it better?

**Comment by nvbn** [comment]
I added support for `--version`, `--help`, `--alias [name]`, if none of them passed as a first argument (`sys.argv[1]`), app works like before. So backward compatibility wasn't broken.

**Comment by nvbn** [comment]
Already implemented.
