### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by nvbn** [nvbn/thefuck#346]
I've added installation script that can be used like:

``` bash
wget -O - https://raw.githubusercontent.com/nvbn/thefuck/master/install.sh | sh -
```

I've tested it only on Ubuntu, so if someone can test it on other platforms and add other platforms support (now only supports Ubuntu and OS X), it will be cool =)

**Comment by anshuman73** [comment]
Hi, Is there anything more to work on this issue ?
I think this would practically be solved after pip and homebrew support
