### ISSUE TITLE
apt install when command not found

### ISSUE THREAD

**Issue by marsjaninzmarsa** [nvbn/thefuck#349]
```
marsjan@lena » thefuck -v
The Fuck 2.8
marsjan@lena » gnome-tweak-tool
The program 'gnome-tweak-tool' is currently not installed.  To run 'gnome-tweak-tool' please ask your administrator to install the package 'gnome-tweak-tool'                    
gnome-tweak-tool: command not found
marsjan@lena » fuck
gnome-web-photo [enter/↑/↓/ctrl+c]
```

I wanna see `apt install gnome-tweak-tool` against `gnome-web-photo`.

**Comment by mlk** [comment]
Which platform are you using? I've not since "apt install" before, only "apt-get install".

**Comment by marsjaninzmarsa** [comment]
Debian 8, in new Ubuntu it's also working.
It can be `apt-get`, no difference for me, just less typing. :smile:

**Comment by mcarton** [comment]
Yes, Debian now has `apt`, `apt-get` and `aptitude`. Not confusing at all.
Isn't `apt install gnome-tweak-tool` also proposed ? (using the arrow keys)

**Comment by NDevox** [comment]
Which one is the most common? I only use `apt-get`. So in my mind that is the one that should be used.

**Comment by marsjaninzmarsa** [comment]
@mcarton: isn't.
@NDevox: `apt-get` should be preferred, because `apt` and `apt-get` works the same and `apt-get` works also in older systems. `apt` is preferred by me only because it's 4 keys to type less, and if I don't must write it at all it's no difference for me. :smiley:

**Comment by mcarton** [comment]
"it also works also on older systems" is a terrible reason.
We would never use anything new if we'd blindly follow that.

**Comment by marsjaninzmarsa** [comment]
@mcarton but `apt` is nothing really new, it's only shortcut wrapper for `apt-get`...

**Comment by nvbn** [comment]
You should install `python-commandnotfound` / `python3-commandnotfound` for `apt-get` rule.

**Comment by mcarton** [comment]
@nvbn the install script could do that on Debian/ubuntu.

**Comment by nvbn** [comment]
@mcarton yep =)

**Comment by mcarton** [comment]
That was fast :)
