### ISSUE TITLE
Instead correcting shows usage tip

### ISSUE THREAD

**Issue by scythargon** [nvbn/thefuck#356]
Ubuntu 15.04, tried both pip and pip3 (after removed pip version), got:

```
argon@vervet:jr-content$ aptget install lal
No command 'aptget' found, did you mean:
 Command 'apt-get' from package 'apt' (main)
aptget: command not found
argon@vervet:jr-content$ thefuck
usage: The Fuck [-h] [-v] [-a] [command [command ...]]
```

**Comment by scorphus** [comment]
Oh, you forgot to setup your shell. You need an alias (or function) in order for it to work.

Try and follow the [manual installation](https://github.com/nvbn/thefuck#manual-installation) instructions.

**Comment by nvbn** [comment]
In 3.0 when alias isn't configured it shows useful message:
```bash
🔧  fuck
Seems like fuck alias isn't configured!
Please put eval $(thefuck --alias) in your ~/.zshrc.
More details - https://github.com/nvbn/thefuck#manual-installation
```

**Comment by scorphus** [comment]
Docs and useful message seem to be enough.
