### ISSUE TITLE
Add rules_exclude setting

### ISSUE THREAD

**Issue by hcgraf** [nvbn/thefuck#357]
It would be nice if one could exclude certain rules in the settings.py file.
I didn't find a way of doing so, other than listing all the default rules (except for my excluded rules) in the "rules" array (settings.py) or THEFUCK_RULES variable.

Suggestion: add something like rules_exclude or THEFUCK_RULES_EXCLUDE.

**Comment by nvbn** [comment]
`exclude_rules` and `THEFUCK_EXCLUDE_RULES` were added in 3.0.
