### ISSUE TITLE
Shell history polution

### ISSUE THREAD

**Issue by washtubs** [nvbn/thefuck#376]
I haven't used this, but I just thought maybe this is not such a good idea because it's going to make traversing shell history really irritating. Does this do anything to get around that, or are there any workarounds?

If not, I know in zsh you can just populate the command line with whatever you want using LBUFFER and RBUFFER. What if you made it an option to type "fuck" then hit ctrl-F (for "fuck"), and it would just replace your command line with the correction, and if there's multiple candidates cycle through them by hitting ctrl-F again. That also lets you edit the correction however you want as well.

**Comment by nvbn** [comment]
You should try thefuck plugin for oh-my-zsh - https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/thefuck, it's almost doing what you want.
