### ISSUE TITLE
install.sh tries to install python on OS X

### ISSUE THREAD

**Issue by jordan314** [nvbn/thefuck#377]
when I ran the wget install.sh command it tried installing python in El Capitan and failed. Just running `sudo pip install thefuck` worked fine. Thanks for this script!

**Comment by josephfrazier** [comment]
Sorry you had trouble (and for the delay in response)! I'm closing this now that `install.sh` is deprecated (see https://github.com/nvbn/thefuck/commit/15bcd7f03f758a01f2db400ff1194b29a43d37f3).
