### ISSUE TITLE
OS X terminal bug

### ISSUE THREAD

**Issue by wielski** [nvbn/thefuck#381]
Is it normal?
https://www.dropbox.com/s/f5tc4yujynn45nh/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-10-12%2015.49.50.png?dl=0

**Comment by DominikAngerer** [comment]
Yes it is :+1: 
btw. no it isn't :)

**Comment by mcarton** [comment]
No it's not, but we'd need more information:
- output of `thefuck --version`;
- export `THEFUCK_DEBUG=true`, reproduce the bug and paste the output here;
- how to reproduce the bug.

**Comment by jucor** [comment]
Problem reproduced here:  
![image](https://cloud.githubusercontent.com/assets/660037/11629495/760e8c52-9cf0-11e5-94ba-df05dbc963f2.png)

Steps to reproduce:
1. run a vim command, e.g. 'vim test'
1. exit vim (that's :wq for the emacsers out here), back to the shell
3. call `fuck`

Result:
* See screenshot
* No local echo anymore at the prompt
* No line returns
* Need to call `reset` to put the term back into proper shape

Result expected
* Having a working prompt

Using
*  iTerm 2, Build 2.1.4
* `thefuck --version` gives: `The Fuck 3.2 using Python 2.7.10`
* debug output (messed up because of the bug ruining the output)
``
jucor@jucor-macbookpro:~$ export THEFUCK_DEBUG=true
jucor@jucor-macbookpro:~$ vim test
jucor@jucor-macbookpro:~$ fuck
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x102093160>],
 'user_dir': PosixPath('/Users/jucor/.config/thefuck'),
 'wait_command': 3}
DEBUG: Execution timed out!
                           DEBUG: Call: vim test; with env: {'_': '/Users/jucor/homebrew/bin/thefuck', 'HOMEBREW_GITHUB_API_TOKEN': '560f7141b9d6ceeabc2be6b82735b19c28555a2a', '__CF_USER_TEXT_ENCODING': '0x39A9A:0x0:0x0', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'ITERM_PROFILE': 'Default', 'CPATH': '/Users/jucor/homebrew/include:', 'LOGNAME': 'jucor', 'USER': 'jucor', 'HOME': '/Users/jucor', 'PATH': '/Users/jucor/anaconda/bin:/Users/jucor/usr/bin:/Users/jucor/homebrew/bin:/Users/jucor/.luarocks/bin:/Users/jucor/torch/bin:/Applications/RStudio.app/Contents/MacOS:/Users/jucor/homebrew/bin:/Users/jucor/bin:/Users/jucor/homebrew/sbin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin', 'CMAKE_PREFIX_PATH': '/Users/jucor/homebrew:', 'DISPLAY': '/private/tmp/com.apple.launchd.0qGUiO5f2h/org.macosforge.xquartz:0', 'TERM_PROGRAM': 'iTerm.app', 'LANG': 'C', 'THEFUCK_DEBUG': 'true', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'COLORFGBG': '7;0', 'STOW_DIR': '/Users/jucor/usr/stow', 'SHLVL': '1', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w0t0p0', 'GIT_TRACE': '1', 'EDITOR': '/usr/bin/vim', 'LUA_PATH': '/Users/jucor/.luarocks/share/lua/5.1/?/init.lua;/Users/jucor/Software/Whetlab-Lua-Client/?.lua;;./?/init.lua;?.lua;;', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.jI2YrAMvKV/Listeners', 'PYTHONPATH': '/Users/jucor/homebrew/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages:/Users/jucor/homebrew/Cellar/thefuck/3.2/libexec/vendor/lib/python2.7/site-packages', 'XPC_SERVICE_NAME': '0', 'LUA_CPATH': '/Users/jucor/.luarocks/lib/lua/5.1/?.so;;', 'RSTUDIO_WHICH_R': '/Users/jucor/homebrew/bin/R', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.RxHxbAJNKA/Render', 'PKG_CONFIG_PATH': '/Users/jucor/homebrew/lib/pkgconfig:', 'LC_ALL': 'C', 'TMPDIR': '/var/folders/00/1sn6h000h01000cxqpysvccm0076mt/T/', 'LUA_HISTORY': '/Users/jucor/.luahist', 'BASH_FUNC_luarocks_update_all%%': '() {  function _luarocks_update () \n { \n local tree="$1";\n local prefix="$2";\n ${prefix} sh -c "luarocks list --porcelain --tree=${tree}       | awk \'{print \\$1}\'       | xargs -n1 luarocks install --tree=${tree}"\n };\n echo \'Updating global rocks...\';\n _luarocks_update "/usr" "sudo";\n echo \'\';\n echo \'Updating local rocks...\';\n _luarocks_update "$HOME/usr"\n}', 'HISTCONTROL': 'ignoreboth', 'PWD': '/Users/jucor', 'VERSIONER_PYTHON_VERSION': '2.7'}; took: 0:00:03.027775
                                                                    DEBUG: Importing rule: apt_get; took: 0:00:00.000335
                                        DEBUG: Importing rule: apt_get_search; took: 0:00:00.000356
                   DEBUG: Importing rule: brew_install; took: 0:00:00.000425
                                                                            DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000100
                                                             DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000044
                                      DEBUG: Importing rule: cargo; took: 0:00:00.000041
        DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000221
                                                                     DEBUG: Importing rule: cd_correction; took: 0:00:00.001093
                                               DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000304
                    DEBUG: Importing rule: cd_parent; took: 0:00:00.000042
                                                                          DEBUG: Importing rule: composer_not_command; took: 0:00:00.000188
                                                           DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000315
                                             DEBUG: Importing rule: cpp11; took: 0:00:00.000185
               DEBUG: Importing rule: dirty_untar; took: 0:00:00.001527
                                                                       DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000283
                                               DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000056
                              DEBUG: Importing rule: django_south_merge; took: 0:00:00.000050
             DEBUG: Importing rule: docker_not_command; took: 0:00:00.000508
                                                                            DEBUG: Importing rule: dry; took: 0:00:00.000042
                                            DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000250
                      DEBUG: Importing rule: fix_file; took: 0:00:00.002057
                                                                           DEBUG: Importing rule: git_add; took: 0:00:00.000438
                                               DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000204
                             DEBUG: Importing rule: git_branch_list; took: 0:00:00.000187
         DEBUG: Importing rule: git_checkout; took: 0:00:00.000229
                                                                  DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000233
                                              DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000229
                        DEBUG: Importing rule: git_not_command; took: 0:00:00.000198
    DEBUG: Importing rule: git_pull; took: 0:00:00.000309
                                                         DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000241
                                    DEBUG: Importing rule: git_push; took: 0:00:00.000226
         DEBUG: Importing rule: git_push_force; took: 0:00:00.000229
                                                                    DEBUG: Importing rule: git_push_pull; took: 0:00:00.000227
                                              DEBUG: Importing rule: git_stash; took: 0:00:00.000212
                    DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000233
                                                                               DEBUG: Importing rule: go_run; took: 0:00:00.000215
                                                  DEBUG: Importing rule: grep_recursive; took: 0:00:00.000212
                             DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000230
       DEBUG: Importing rule: has_exists_script; took: 0:00:00.000219
                                                                     DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000208
                                                    DEBUG: Importing rule: history; took: 0:00:00.000185
                        DEBUG: Importing rule: java; took: 0:00:00.000186
                                                                         DEBUG: Importing rule: javac; took: 0:00:00.000185
                                           DEBUG: Importing rule: lein_not_task; took: 0:00:00.000306
                     DEBUG: Importing rule: ls_lah; took: 0:00:00.000182
                                                                        DEBUG: Importing rule: man; took: 0:00:00.000218
                                        DEBUG: Importing rule: man_no_space; took: 0:00:00.000043
                 DEBUG: Importing rule: mercurial; took: 0:00:00.000188
                                                                       DEBUG: Importing rule: mkdir_p; took: 0:00:00.000181
                                           DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000175
                      DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000185
              DEBUG: Importing rule: no_command; took: 0:00:00.000190
                                                                     DEBUG: Importing rule: no_such_file; took: 0:00:00.000073
                                              DEBUG: Importing rule: open; took: 0:00:00.000180
               DEBUG: Importing rule: pacman; took: 0:00:00.000419
                                                                  DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000090
                                               DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000314
                               DEBUG: Importing rule: python_command; took: 0:00:00.000191
          DEBUG: Importing rule: python_execute; took: 0:00:00.000180
                                                                     DEBUG: Importing rule: quotation_marks; took: 0:00:00.000041
                                                 DEBUG: Importing rule: rm_dir; took: 0:00:00.000196
                    DEBUG: Importing rule: rm_root; took: 0:00:00.000186
                                                                        DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000182
                                                       DEBUG: Importing rule: sl_ls; took: 0:00:00.000039
                         DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000189
     DEBUG: Importing rule: sudo; took: 0:00:00.000120
                                                      DEBUG: Importing rule: switch_lang; took: 0:00:00.000064
                              DEBUG: Importing rule: systemctl; took: 0:00:00.000304
    DEBUG: Importing rule: test.py; took: 0:00:00.000038
                                                        DEBUG: Importing rule: tmux; took: 0:00:00.000183
                         DEBUG: Importing rule: touch; took: 0:00:00.000178
                                                                           DEBUG: Importing rule: tsuru_login; took: 0:00:00.000187
                                                   DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000177
                                 DEBUG: Importing rule: unknown_command; took: 0:00:00.000044
             DEBUG: Importing rule: vagrant_up; took: 0:00:00.000177
                                                                    DEBUG: Importing rule: whois; took: 0:00:00.000236
                                      DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000416
           No fucks given
                         DEBUG: Total took: 0:00:03.055213
                                                          jucor@jucor-macbookpro:~$
``

**Comment by parulgarg123** [comment]
I don't think this should be a valid Bug
