### ISSUE TITLE
prevent partial execution of install.sh

### ISSUE THREAD

**Issue by krousey** [nvbn/thefuck#382]
When installing with

```console
> wget -O - https://raw.githubusercontent.com/nvbn/thefuck/master/install.sh | sh - && $0
```

It's possible that you only get part of the script and execution halts part way through. You should wrap the main installation code in a function and then call that function at the end. That way, if a partial download occurs, you only get an error of an incomplete function definition, not a half-way completed install.

Probably should also avoid naming the function with something that has a command as a prefix to avoid it executing that command in the event of a partial download. E.g. not

```sh
reboot_install () {
  ...
}
reboot_install
```

If it stops at either underscore, ...

**Comment by nvbn** [comment]
Fixed in 3.2.
