### ISSUE TITLE
Rename tool to f

### ISSUE THREAD

**Issue by kim0** [nvbn/thefuck#401]
Rational:
=====
* The new name will help the tool get better adoption
* The new name can be officially short for "fix", while we old timers all know what it really stands for :)
* f is a one letter name that is easy and fast to type, and about impossible to get wrong

**Comment by mcarton** [comment]
As explained in the README, you can use whatever you want as the alias:
```bash
eval "$(thefuck --alias)"
# You can use whatever you want as an alias, like for Mondays:
eval "$(thefuck --alias FUCK)"
```
Or, in your case :smile::
```bash
eval "$(thefuck --alias f)"
```

**Comment by dedanna1029** [comment]
WHY do you want to change the name of the whole project when you can change it to suit your own needs??? The name is part of its appeal! Do you something against the f word??? For shame.

**Comment by Celti** [comment]
When you can't actually say "fuck" and are saying "the f word" instead, perhaps he has a point?

**Comment by icovada** [comment]
We're not playing "marketing department" here. This software is open source. We don't have a target audience nor do we have any need to push its use in more serious corporate environments, or to kids learning how to sysadmin.

I must admit that for me, most of the appeal of this software is in its name. A more polite but much much less cathartic "fix" instead of "FUUUUUUCK" wouldn't just be as stupidly funny.

You don't like it? Fork it, can call it "fix". I stand by "fuck"

**Comment by nvbn** [comment]
I think current name is ok =)
Also `f` isn't a good name for the project, it isn't googleable.

As @mcarton mention, you can use `f` alias if you want:
```bash
eval "$(thefuck --alias f)"
```

**Comment by mcarton** [comment]
What I fucking like about the fucking English language is that you can fucking use the fucking word “fuck” almost anywhere you fucking want.

> You don't like it? Fork it, can call it "fix". I stand by "fuck"

Look at the forks, that's already been done (as [fix](https://github.com/John-Appleseed/fix), as [dafuq](https://github.com/kambanwait/DAFUQ), etc.), although these forks are usually not maintained afterwards… fuck.

**Comment by dedanna1029** [comment]
@Celti I can say anything I fucking want, the U.S. is still a somewhat free country last I checked. I said it that way for yours and @kim0 's benefit, but after that smart-ass remark I don't think I will any more.

Thank you @icovada ! I think both the package and name are brill! :+1:

**Comment by mcarton** [comment]
As a non-native English speaker, I find “fuck” is such a common English word that it's not a problem to use it in such circumstances. The name is funny, easy to remember, easy to type, not as likely to be typed by a cat sleeping on your keyboard as `f` would and it expresses your feeling at the moment you'd use it. It's a good name.
And come on, why would you care being polite to your terminal?

---
*Warning, the following could shock U.S. citizens:*
> I can say anything I fucking want, the U.S. is still a somewhat free country last I checked.

Actually, no, you can't. I'll let you [search for it](https://duckduckgo.com/?q=first+amemdment+offensive+speech) as this is not the place to discuss about it. Also the Internet is not the U.S., there are some other countries in the world that can access it.

**Comment by dedanna1029** [comment]
O rly? That's why three other people in this thread used it as well? No make that four. One has it in their code. Don't like it? Don't use it or alias it.

**Comment by dedanna1029** [comment]
@mcarton From your own search:
"Nevertheless, the court’s free speech jurisprudence does not allow government-sanctioned punishment of speech solely because the message may be offensive. Rather, it allows regulation of speech only if there are objective indications of harm, such as threats, fraud or violence. The court protects offensive speech because speech on matters of public concern is valuable even when it is delivered in an offensive manner and because punishing offensive speech can lead to censorship of unpopular views. In doing so, the court has implicitly recognized the inherent tensions created by our psychological responses to offensive speech and the importance we place on the free exchange of ideas."

http://www.apa.org/monitor/2011/01/jn.aspx

**Comment by krisztianfekete** [comment]
I think the project name is OK - it describes the situation when the command applies (utter astonishment).  Even the command name `thefuck` is OK!

However on the *command line* the default alias name `fuck` is intended to be used as a verb, which I do not find appropriate.
The situation is, that **I made a mistake** and **I am asking for easy help**!
I would prefer saying "please, fix it for me".

I would prefer if the default, documented alias name would be the magic word `please`.

Please, reconsider this issue!

**Comment by nvbn** [comment]
> However on the command line the default alias name fuck is intended to be used as a verb, which I do not find appropriate.
> I would prefer if the default, documented alias name would be the magic word please.

Default alias will stay `fuck`, just use another alias:
```bash
eval "$(thefuck --alias please)"
```

**Comment by mcarton** [comment]
> However on the command line the default alias name fuck is intended to be used as a verb, which I do not find appropriate.

That's an interjection, not a verb, so *fuck* is appropriate.

**Comment by thechief389** [comment]
There are the people that are okay with it. And then there are the people that will get offended, not want to use the software, and possibly start flame wars.

**Comment by ronanamsterdam** [comment]
people get offended too much these days and there workaround or just don't use the tool

**Comment by mattgrande** [comment]
@ronanamsterdam - There's no need to bump a three year old, closed, ticket just to complain about how offended people are.

**Comment by bjornicus** [comment]
> I think current name is ok =)
> Also `f` isn't a good name for the project, it isn't googleable.

I mean, you're right, but try googling 'fuck', you aren't going to find it that way either...

(obviously 'theFuck' does turn up the expected result)

**Comment by steaksauce-** [comment]
> > I think current name is ok =)
> > Also `f` isn't a good name for the project, it isn't googleable.
> 
> I mean, you're right, but try googling 'fuck', you aren't going to find it that way either...
> 
> (obviously 'theFuck' does turn up the expected result)

Well, `thefuck` is actually the name of the tool (maybe so that it can be Googleable?) - it's just that if one follows the installation guide, an alias is set to call it `fuck` instead.
