### ISSUE TITLE
Ugly warning while selecting command

### ISSUE THREAD

**Issue by Kwaadpepper** [nvbn/thefuck#404]
```The Fuck 3.2 using Python 2.7.10```
```Kubuntu 15.10```
In **.bashrc** ```alias fuck='eval "$(eval $(thefuck $(fc -ln -1)))"'```
In **.zshrc** ```eval $(thefuck --alias)```
So with bash, and zsh

I tried thefuck with the **ubuntu  repo version**, which happened to be fixed recently, i tried with **the last updated version of thefuck**

In the first example i ran: ```sudo aptget update``` then  ```fuck``` then type <kbd>↑</kbd> (up arow) on both **zsh** and **bash**

    $ fuck
    sudo apt-get update [enter/↑/↓/ctrl+c]/usr/local/lib/python2.7/dist-packages/thefuck/rules/history.py:24: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal and line.split(' ')[0] in executables]
    sudo plget update [enter/↑/↓/ctrl+c]
    Aborted

The debug version http://paste.ubuntu.com/13282061/

It seems to happen on any command, i tried with ```sulb``` instead of ```subl```

**Comment by mcarton** [comment]
That's yet another problem with Unicode and Python 2. If you can, use The Fuck with Python 3 (eg. install it with `pip3 install thefuck`), the problem will likely be gone. @scorphus: if you still want to fix that :smile:

BTW: you can use `eval "$(thefuck --alias)"` within **.bachrc** too, that way if the alias ever get updated, you'd automatically use the new one.

**Comment by Kwaadpepper** [comment]
I just got ```python3-pip``` and done ```pip3 install thefuck```
I got errors on install which i give you in these link (second is the debug file)
http://paste.ubuntu.com/13282680/
http://paste.ubuntu.com/13282685/

Running thefuck gives

    Traceback (most recent call last):
      File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.main import main
      File "/usr/local/lib/python3.5/dist-packages/thefuck/main.py", line 6, in <module>
    from . import logs, types, shells
      File "/usr/local/lib/python3.5/dist-packages/thefuck/types.py", line 6, in <module>
    from psutil import Process, TimeoutExpired
    ImportError: No module named 'psutil'

It was missing psutil and decorator, which i installed.
And finally i got this **thefuck** error

http://paste.ubuntu.com/13282783/

Sorry i think this may be bad news, or hopefully i'm missing another dependency ?

**Comment by mcarton** [comment]
This is not an error with The Fuck but pip. It seems it is not able to install `psutils` when some dependencies (here probably *python3-dev*) are not met but it fails to report that and fails ungracefully. On Ubuntu you could install *python3-psutil* before you install The Fuck.

**Comment by Kwaadpepper** [comment]
Well indeed i removed thefuck and reinstall without errors.
However i still got this bug (same as my last link on previous comment): 
http://paste.ubuntu.com/13282990/

I just tried getting thefuck from repo, and having ```eval "$(thefuck --alias)"``` with repo version 2.5.6-1, running with python2 made a **fork bomb** - just so you know -
So i ran ```wget -O - https://raw.githubusercontent.com/nvbn/thefuck/master/install.sh | sh - && $0``` as in Readme and back from start point of course.

So ultimately again, using pip3, i got this error http://paste.ubuntu.com/13282990/

**Comment by mcarton** [comment]
Do you have a `~/.cache/thefuck` file? Do you still get the same error if you remove it and run The Fuck again?

**Comment by Kwaadpepper** [comment]
Indeed i tried deleting it and still same issue
here it is 
https://www.freethepepper.com/owncloud/index.php/s/F6XQd9xperIt1Qw

**Comment by mcarton** [comment]
Nice :smile:
So that last problem was because Python 2 and Python 3 shelves are not compatible (how convenient) and your file was a Python 2 shelf. I'll do something about that.

**Comment by scorphus** [comment]
@mcarton wrote:
> That's yet another problem with Unicode and Python 2. If you can, use The Fuck with Python 3 (eg. install it with pip3 install thefuck), the problem will likely be gone. @scorphus: if you still want to fix that :smile:

I'm on it, as free time allows me :smiley:

**Comment by mcarton** [comment]
> I'm on it, as free time allows me :smiley: 

No problem, I just wanted to cc you that as you've shown interest for fixing Unicode problems.
