### ISSUE TITLE
Random error in install script

### ISSUE THREAD

**Issue by AlphaT3ch** [nvbn/thefuck#438]
Setting up libapt-pkg-perl (0.1.29+b3) ...

Setting up liblist-moreutils-perl (0.33-2+b1) ...

Setting up libregexp-assemble-perl (0.35-8) ...

Setting up apt-file (2.5.4) ...

The system-wide cache is empty. You may want to run 'apt-file update' as root to update the cache. You can also run 'apt-file update' as normal user to use a cache in the user's home directory.

Setting up python-gdb (2.7.8-2) ...

Setting up command-not-found (0.2.38-1) ...

You need to run 'update-command-not-found' as root to update the cache.

Setting up libpython-dev:armhf (2.7.9-1) ...

Setting up python2.7-dev (2.7.9-2) ...

Setting up python-dev (2.7.9-1) ...

sh: 18: [[: not found

**Comment by mcarton** [comment]
`[[` is a bashism. `[` should work as well here.

**Comment by AlphaT3ch** [comment]
Ah, since it's not my project I didn't feel like checking the script, etc. I just submitted this as an error for a heads up, but the install went through anyways.

**Comment by nvbn** [comment]
We no longer use install script.
