### ISSUE TITLE
Windows - ImportError: No module named dbm

### ISSUE THREAD

**Issue by vidarkongsli** [nvbn/thefuck#439]
I have installed thefuck with pip using Python 2.7.11 in Windows. When running `thefuck` from Powershell, I get the error message `ImportError: No module named dbm`. Any ideas?

**Comment by mcarton** [comment]
Hurfm, Git blames that on me.
The python doc does describe `dbm` as *Interfaces to Unix “databases”* but also mention:
> If none of these modules is installed, the slow-but-simple implementation in module dbm.dumb will be used.

Looks like this is not true on windows then.
I don’t have a Windows to check and fix it. Could someone else take care of that?

@scorphus *gdbm* might be missing on Windows too then.
@vidarkongsli as a temporary fix, if you dare, you can remove lines 1 and 19-22 and replace lines 226-234 of *thefuck/utils.py* with
```py
        except:
            pass
```
as you probably don’t care about Python 2 to Python 3 compatibility.

**Comment by scorphus** [comment]
@vidarkongsli: ping :smiley: Any updates on this, sir?

In the meanwhile, @mcarton, I'll try and fire up a Windows box an see what I get.

**Comment by vidarkongsli** [comment]
@scorphus I was able to edi the `utils.py` file to make it run. But the program crashed later on with a completely different error. :-/

**Comment by MymyKuo** [comment]
I also have the same issue. Is there any updates on this issue?

Thanks a lot.

**Comment by tyrcho** [comment]
Same issue for me, seems to work with previous version :

```
pip.exe install 'thefuck==3.2'
```

**Comment by scorphus** [comment]
> In the meanwhile […] I'll try and fire up a Windows box an see what I get

Ah, for the record, I've done that and assured it works.
