### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by bardov** [nvbn/thefuck#442]
I've seen an issue with a similar problem, but I checked the alias (below) and it does have utf-8 

<danb> danb@ubuntu-danb src $ ls /tnp
ls: cannot access /tnp: No such file or directory
<danb> danb@ubuntu-danb src $ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 79, in main
    fix_command()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 31, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/ui.py", line 83, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 43: ordinal not in range(128)
<danb> danb@ubuntu-danb src $ echo $PYTHONIOENCODING

<kaveret.x1015ol-danb> danb@ubuntu-danb src $ thefuck --alias
TF_ALIAS=fuck alias fuck='PYTHONIOENCODING=utf-8 eval $(thefuck $(fc -ln -1)); history -r'

**Comment by bardov** [comment]
I've also seen it is possible to get it to work with python3. 
I have python3 installed, but between the issue that tells how to set it up with python3 and the main installation instructions, I fail to figure out how to get it to install properly.

I'd appreciate a concise how-to install thefuck on a system that has both python2 and python3 (so that it will work only using the python3 route)

**Comment by mcarton** [comment]
Reinstalling it with Python 3 should be as simple as `pip2 uninstall thefuck && pip3 install thefuck`. The alias is the same.

**Comment by bardov** [comment]
Not that simple. Obviously this concise instruction is missing *something*

danb@ubuntu-danb ~ $ pip2 uninstall thefuck && pip3 install thefuck
Cannot uninstall requirement thefuck, not installed
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by scorphus** [comment]
Perhaps recent solution to #433 solves this problem too. I see @bardov's alias is a bit *outdated* – which is expected as there's still no new release with the fix. Nevertheless, a bash alias should read like this:

```bash
bash-4.3$ thefuck --alias
alias fuck='eval $(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 thefuck $(fc -ln -1)); history -r'
```

ps.: there's always a thought in my mind whenever I brush against issues like this: how about we keep the default encoding in the settings? We could even have an *if python2* statement there. I'm gonna open a pull request :cake:

**Comment by nvbn** [comment]
We have `PYTHONIOENCODING=utf-8` in alias for a while, so I guess issue is obsolete.
