### ISSUE TITLE
apt-get tests fail on fresh install

### ISSUE THREAD

**Issue by enochtsang** [nvbn/thefuck#448]
The Fuck 3.3 using Python 3.4.3 (This is the command output, I have a fresh clone of the repo for this issue)
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Ubuntu 14.04

On a fresh clone, running `python3 -m pytest` fails a few of the apt-get tests. The following asserts fail:

``` python
assert cmdnf_mock.CommandNotFound.called # line 28
assert get_new_command(command) == new_command # line 47
assert get_new_command(command) == new_command # line 66
```

This is in `tests/rules/test_apt_get.py`  

I ran the Developing instructions 

``` bash
pip install -r requirements.txt
python setup.py develop
```

Varying amounts of tests fail (1, 3, 5, or 7) everytime I run the tests, but they always point to the same 3 asserts failing.

**Comment by nvbn** [comment]
Test was changed a while ago, now everything should work.
