### ISSUE TITLE
Fuck alias for fish

### ISSUE THREAD

**Issue by larsgrefer** [nvbn/thefuck#449]
`~> fuck` says:
>```
Seems like fuck alias isn't configured!
Please put eval thefuck --alias in your ~/.config/fish/config.fish.
More details - https://github.com/nvbn/thefuck#manual-installation
```

but https://github.com/nvbn/thefuck/wiki/Shell-aliases says:

>Add this function to config.fish:
```fish
eval (thefuck --alias | tr '\n' ';')
```

What should I add to my `config.fish`? 
- `eval thefuck --alias`

or
- `eval (thefuck --alias | tr '\n' ';')`

**Comment by scorphus** [comment]
Hello, @larsgrefer. Thanks for reporting this discrepancy. I'll fix it.

In the meantime, please add `eval (thefuck --alias | tr '\n' ';')` to your `config.fish`

If by any chance you use [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish), you can just install the [thefuck](https://github.com/oh-my-fish/plugin-thefuck) plugin.

```
 $ omf install thefuck
```

**Comment by larsgrefer** [comment]
I think
```fish
user@host ~> fuck
Seems like fuck alias isn't configured!
Please put eval thefuck --alias in your ~/.config/fish/config.fish.
More details - https://github.com/nvbn/thefuck#manual-installation
user@host ~> fuck
```

should suggest:
```fish
echo "eval (thefuck --alias | tr '\n' ';')" >> ~/.config/fish/config.fish
```
