### ISSUE TITLE
please add support for command line argument "no"

### ISSUE THREAD

**Issue by dnwts** [nvbn/thefuck#451]
This one besides being funny actually has a point! :)

```
> mv /one/file.txt /two
[file moved]
> fuck no
executing 'mv /two/file.txt /one'
[file moved back]
```

As you see, it would try not to fix the previous command, but to undo it (if possible). This could be very useful against various `git` commands, file moving, `apt-get` (just because why not) and i'm sure you can imagine much more :) i see quite some value here, what do you think?

**Comment by mariusbaciu** [comment]
:+1:

**Comment by DragosRadu** [comment]
:+1:

**Comment by mcarton** [comment]
That’s not possible in general. E.g. maybe there there was a file `/two/file.txt` and your `mv /one/file.txt /two` erased it. There is no reasonable way to know there was a file there and to get it back.
What you propose would almost always be a partial fix and work on very few commands. I expect that to be more frustrating than useful.

**Comment by dnwts** [comment]
Ok, the file move example wasn't best picked as an example, but it could work for other commands :)

**Comment by dnwts** [comment]
Oh, for file moving, `fuck` could check for the confirmation prompt or the use of `-f` or `--force` and advise against performing the undo. It may do so kinda like this:

```
> fuck no
You're screwed, i cannot undo that.
```

**Comment by nvbn** [comment]
Nice idea, but I guess it hardly can be implemented without some fs-level support of snapshots.

**Comment by dnwts** [comment]
Thanks @nvbn, and the idea wasn't limited to fs-level commands, that's the beauty of it i think. It could be reverting a `git` command, an `apt-get` installation, etc. I'm sure you have a much broader imagination you can use to find other cool use-cases for such a feature :)

**Comment by nvbn** [comment]
@dnwts I mean somethig like this:
```
ls
# snapshot 1 created implicitly
rm myfile
# snapshot 2 created
fuck no
# rollback to snapshot 1
git commit -am test
# snapshot 3 created
git branch -D test
# snapshot 4 created
fuck no
# rollback to snapshot
```

It'll be more generic and not so hard to implement with fs-level snapshots (btrfs, zfs).

**Comment by Kurtoid** [comment]
But it could slow down a lot of commands

On Mon, Feb 1, 2016, 8:50 AM Vladimir Iakovlev <notifications@github.com>
wrote:

> @dnwts <https://github.com/dnwts> I mean somethig like this:
>
> ls
> # snapshot 1 created implicitly
> rm myfile
> # snapshot 2 created
> fuck no
> # rollback to snapshot 1
> git commit -am test
> # snapshot 3 created
> git branch -D test
> # snapshot 4 created
> fuck no
> # rollback to snapshot
>
> It'll be more generic and not so hard to implement with fs-level snapshots
> (btrfs, zfs).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvbn/thefuck/issues/451#issuecomment-177978774>.
>
-- 

~Kurt

**Comment by Kurtoid** [comment]
And use a lot of memory

On Mon, Feb 1, 2016, 9:04 AM Kurt Wilson <kurt4wilson@gmail.com> wrote:

> But it could slow down a lot of commands
>
> On Mon, Feb 1, 2016, 8:50 AM Vladimir Iakovlev <notifications@github.com>
> wrote:
>
>> @dnwts <https://github.com/dnwts> I mean somethig like this:
>>
>> ls
>> # snapshot 1 created implicitly
>> rm myfile
>> # snapshot 2 created
>> fuck no
>> # rollback to snapshot 1
>> git commit -am test
>> # snapshot 3 created
>> git branch -D test
>> # snapshot 4 created
>> fuck no
>> # rollback to snapshot
>>
>> It'll be more generic and not so hard to implement with fs-level
>> snapshots (btrfs, zfs).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nvbn/thefuck/issues/451#issuecomment-177978774>.
>>
> --
>
> ~Kurt
>
-- 

~Kurt

**Comment by nvbn** [comment]
@Kurtoid, as fast as I know, btrfs snapshots are lightweight and fast. But I can be wrong.

And implementation shouldn't be that straightforward, there should be gc for old snapshots and ton of other things.

And I guess it should be a separate project =)

**Comment by dnwts** [comment]
Thank you for your time @nvbn! I wasn't insisting on a generic implementation because i imagined it might slow the system too much or use a ton of disk space, but what you're saying sounds really awesome! 
Of course, it would imply a trade of *some* performance/disk space to basically get an "undo" feature, but who knows? Some may find it very useful ("undo in terminal" yields quite a number of relevant results in google).
Anyway, i agree, it should be the topic for another project, i just thought it would sound really cool in this context (pretty much intuitive :D) you can reopen the issue if it sticks with you :)
