### ISSUE TITLE
apt-get vs apt-cache

### ISSUE THREAD

**Issue by Kurtoid** [nvbn/thefuck#454]
could `apt-get search` be corrected as `apt-cache search`?

**Comment by mcarton** [comment]
Isn’t that exactly what the *apt_get_search* rule does?

**Comment by Kurtoid** [comment]
the only suggestion i get is `apt-get clean`

**Comment by mcarton** [comment]
Here is what I get:
```
% thefuck --version
The Fuck 3.3 using Python 3.4.2
% apt-get search
E: Invalid operation search
zsh: exit 100   apt-get search
% fuck
apt-cache search [enter/↑/↓/ctrl+c]
```
Are you up-to-date? If you’ve installed The Fuck with pip, you can update it with `pip install --upgrade thefuck`.

**Comment by nvbn** [comment]
Fixed in previous releases.
