### ISSUE TITLE
Instructions on complete uninstallation?

### ISSUE THREAD

**Issue by keanegit** [nvbn/thefuck#455]
Hello,

I do not use any of the supported package managers, so I used the wget command to install fuck. (I didn't realize that it was going to install pip as part of that command, but I guess I should have been paying more attention.)

Anyway, I decided that it's not for me, and removed the line about configuring it from my .bashrc and ran pip uninstall thefuck (or something similar) to uninstall it, which seemed to run successfully. I also removed the "thefuck" directory from my .config folder.

Unfortunately, now every time I open a terminal or access the console I immediately get the message "-bash: thefuck: command not found", so there is still something looking for thefuck every time I use a console. Any idea how to remove this behavior? There doesn't seem to be much included in the readme about uninstallation

**Comment by keanegit** [comment]
Wow, sorry about that. It was still referenced in .bash_profile somewhere. It would still be nice if there were instructions for uninstallation though.

**Comment by adam993** [comment]
I removed thefuck via pip3, and now I get this message whenever I start any terminal instance:

`Command 'thefuck' not found, but can be installed with:

sudo apt install thefuck`

**Comment by Rom1deTroyes** [comment]
@adam993 : It seems that when you open a terminal, your shell tries to launch *thefuck*... have you removed the `eval $(thefuck --alias)` line from your shell config file (.bash_profile, .bashrc, .zshrc) ?

**Comment by adam993** [comment]
> @adam993 : It seems that when you open a terminal, your shell tries to launch _thefuck_... have you removed the `eval $(thefuck --alias)` line from your shell config file (.bash_profile, .bashrc, .zshrc) ?

Thanks, It was in .bashrc
