### ISSUE TITLE
Deletes temporary session history in bash

### ISSUE THREAD

**Issue by udiboy1209** [nvbn/thefuck#463]
bash terminal only writes out to `.bash_history` when one closes the terminal. I don't know for sure but it probably temporarily stores the history for each tab separately somewhere, which is only accessible using the `history` command.

When I run `fuck`, all this temporary history is deleted, not just the last faulty command. Any workaround for this?

Using The Fuck 3.2 with Python 2.7.6 on bash 4.3.11

**Comment by mcarton** [comment]
@nvbn Should I make a PR with https://github.com/nvbn/thefuck/issues/422#issuecomment-170240398 limited to `bash`? I haven’t figured out how to do something similar with `zsh` builtins though.

**Comment by udiboy1209** [comment]
@mcarton I'm trying to build from your source but it keeps giving me this error: 

`error in thefuck setup command: Invalid environment marker: python_version<"3.4"` 

 Doesn't thefuck dev version work with 2.7?

**Comment by scorphus** [comment]
@udiboy1209: you better have `setuptools` upgraded (aka `pip install - U setuptools`) or maybe `pip` too.

**Comment by udiboy1209** [comment]
@scorphus I just removed that line for a temporary fix. I'll try upgrading `setuptools` and `pip`. Thanks!

**Comment by nvbn** [comment]
@mcarton it would be nice =)
