### ISSUE TITLE
Please rename types.py

### ISSUE THREAD

**Issue by kapsh** [nvbn/thefuck#464]
I believe in that all software should be installed with one system package manager so I've tried to create ebuild for my Gentoo to install thefuck instead of suggested `pip install`. 
The normal way to do it is to use eclass named distutils-r1 which, in general, execute `setup.py`. 
But this call fails with trace:
```
 python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 62, in <module>
    import os
  File "/usr/lib64/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/usr/lib64/python2.7/posixpath.py", line 17, in <module>
    import warnings
  File "/usr/lib64/python2.7/warnings.py", line 8, in <module>
    import types
  File "types.py", line 2, in <module>
    from subprocess import Popen, PIPE
  File "/usr/lib64/python2.7/subprocess.py", line 430, in <module>
    import pickle
  File "/usr/lib64/python2.7/pickle.py", line 30, in <module>
    from copy_reg import dispatch_table
  File "/usr/lib64/python2.7/copy_reg.py", line 7, in <module>
    from types import ClassType as _ClassType
ImportError: cannot import name ClassType
```

This is happens because python tries to import `ClassType` from `types.py` in your package instead of `/usr/lib64/python2.7/types.py`. So please rename it, I think fucktypes.py wil be fine in this case. Messing with standard libraries names isn't good.

**Comment by nvbn** [comment]
I guess it's some problem in distutils-r1, because thefuck only provides `thefuck.types` module, not `types`. Does it happen with python 3?

Also `setup.py build` works fine for me, even with python 2:
```bash
thefuck master fuck2 🔧  python --version
Python 2.7.10
thefuck master fuck2 🔧  python setup.py build
running build
running build_py
running egg_info
writing requirements to thefuck.egg-info/requires.txt
writing thefuck.egg-info/PKG-INFO
writing top-level names to thefuck.egg-info/top_level.txt
writing dependency_links to thefuck.egg-info/dependency_links.txt
writing entry points to thefuck.egg-info/entry_points.txt
reading manifest file 'thefuck.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'thefuck.egg-info/SOURCES.txt'
```

**Comment by kapsh** [comment]
Hm, manually running `./setup.py build` works for me too. Maybe I missed something about gentoo distutils. 
Sorry for inconvenience.
