### ISSUE TITLE
Double quotes not preserved with fuck `git commmit`?

### ISSUE THREAD

**Issue by Meekohi** [nvbn/thefuck#466]
Seems like the double-quotes are getting jacked up here?
```
meekohi(zoom-video) ~/aball.web/spin-web-viewer$ git commmit -m "temporarily stashing this to try and understand why performance is so bad"
git: 'commmit' is not a git command. See 'git --help'.

Did you mean this?
	commit
meekohi(zoom-video) ~/aball.web/spin-web-viewer$ fuck
git commit -m "temporarily stashing this to try and understand why performance is so bad" [enter/↑/↓/ctrl+c]
error: pathspec 'stashing' did not match any file(s) known to git.
error: pathspec 'this' did not match any file(s) known to git.
error: pathspec 'to' did not match any file(s) known to git.
error: pathspec 'try' did not match any file(s) known to git.
error: pathspec 'and' did not match any file(s) known to git.
error: pathspec 'understand' did not match any file(s) known to git.
error: pathspec 'why' did not match any file(s) known to git.
error: pathspec 'performance' did not match any file(s) known to git.
error: pathspec 'is' did not match any file(s) known to git.
error: pathspec 'so' did not match any file(s) known to git.
error: pathspec 'bad"' did not match any file(s) known to git.
```

**Comment by mcarton** [comment]
I believe a bug like that was already reported, but I cannot reproduce. What shell are you using? And Python version? And The Fuck version?

**Comment by Meekohi** [comment]
```
GNU bash, version 3.2.57(1)-release
The Fuck 3.3 using Python 2.7.11
```

Weirdly, it doesn't happen with a shorter message like `git commmit -m "shortmessage"`. Both of them are hitting rule `git_not_command`.

**Comment by mcarton** [comment]
Well `git commmit -m "shortmessage"` and `git commmit -m shortmessage` are completely equivalent as far as `git` is concerned. It’s you shell which is supposed to handle the quotes.

From the log above (note the quote in `error: pathspec 'bad"'`) it looks like you’re trying to evaluate `git commit -m "\"temporarily" stashing this to try and understand why performance is so "\"bad"` (or equivalently `git commit -m "\"temporarily" "stashing" "this" … "is" "so" "\"bad"`).

What is the result of `alias fuck`?

**Comment by Meekohi** [comment]
`alias fuck='$(thefuck $(fc -ln -1))'`

**Comment by Meekohi** [comment]
Also this, not sure which you meant:
```
meekohi(master) ~/Sites/meekohi.com$ thefuck --alias
TF_ALIAS=fuck alias fuck='PYTHONIOENCODING=utf-8 eval $(thefuck $(fc -ln -1)); history -r'
```

**Comment by mcarton** [comment]
Ok, I can reproduce. Your alias is old, please change it to `eval $(thefuck --alias)` (not `alias fuck=…`, literally just `eval $(thefuck --alias)`).

**Comment by Meekohi** [comment]
This is what's in `.bash_profile`: `alias fuck='$(thefuck $(fc -ln -1))'`

**Comment by Meekohi** [comment]
VICTORY, new alias works. Thanks!

**Comment by mcarton** [comment]
Yep, that’s the old way, the new way `eval $(thefuck --alias)` also has the advantage to update itself :smile:.

**Comment by Kurtoid** [comment]
Thanks. Worked here too.

On Mon, Feb 22, 2016, 6:02 PM Martin Carton <notifications@github.com>
wrote:

> Yep, that’s the old way, the new way eval $(thefuck --alias) also has the
> advantage to update itself [image: :smile:].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvbn/thefuck/issues/466#issuecomment-187429216>.
>
-- 

~Kurt
