### ISSUE TITLE
Fuck doesn't work on Fedora 22

### ISSUE THREAD

**Issue by kiddick** [nvbn/thefuck#467]
>[@localhost ~] $ pwf
bash: pwf: command not found...
[@localhost ~] $ fuck
pwd [enter/↑/↓/ctrl+c]
[@localhost ~] $ 

Just nothing happens.
I've installed via install script and checked all needed aliases for `bash`. They are ok.
Any ideas?

**Comment by kiddick** [comment]
I've noticed that` `fuck` creates file `args` with something like that `pwf executable /bin/sh [/bin/sh, -c, upwf] pwd`.

**Comment by nvbn** [comment]
Can you post output of `thefuck --version`?

**Comment by kiddick** [comment]
> The Fuck 3.3 using Python 2.7.10

**Comment by scorphus** [comment]
@kiddick: can you please update TheFuck to latest version and see if it works?

**Comment by kiddick** [comment]
@scorphus @nvbn looks ok now.
