### ISSUE TITLE
Can I order pizza here?

### ISSUE THREAD

**Issue by dikiaap** [nvbn/thefuck#468]
I hope you give the best.
I ordered on sindresorhus, but he give me creepy.
https://github.com/sindresorhus/awesome/issues/544

**Comment by scorphus** [comment]
![pizza_41ca9f_1523583](https://cloud.githubusercontent.com/assets/2112697/13268820/56fbe2c8-da63-11e5-8ffc-2c99eafb91ba.jpg)

**Comment by dikiaap** [comment]
nooooooo!!!!!!!

**Comment by nvbn** [comment]
Treefiddy for one.
