### ISSUE TITLE
I prefer my bash alias

### ISSUE THREAD

**Issue by samrocketman** [nvbn/thefuck#47]
alias please='sudo $(history -p !!)'

Just sharing a handy bash alias.

**Comment by kubudi** [comment]
You have a typo.
`please`, what is that mean?

**Comment by ScoreUnder** [comment]
In its current form, that "please" is somewhat buggy:
```
$ alias please='sudo $(history -p !!)'
$ printf '%s\n' testing testing "testing testing"
testing
testing
testing testing
$ please
'testing
''testing
''"testing
''testing"
'$ echo $TERM
rxvt-unicode-256color
$ please
$TERM
```
I recommend you use eval with the substitution quoted instead:
```bash
alias please='eval "sudo $(history -p !!)"'
```
This accurately reproduces the command with sudo prepended.

**Comment by samrocketman** [comment]
Nice, thanks for the feedback.

**Comment by samrocketman** [comment]
@kubudi is sometimes how Americans say fuck out out of disbelief or frustration.

It's also a play on words for "Make me a sandwich, please."  It turns into the [XKCD comic][1] phrase "sudo make me a sandwich."

[1]: https://xkcd.com/149/

**Comment by kubudi** [comment]
Oh now it's clear :)
