### ISSUE TITLE
Thefuck alias resolving seems to be broken as of the new version

### ISSUE THREAD

**Issue by deiga** [nvbn/thefuck#479]
I could have swore that in earlier versions my aliases where interpreted correctly and now in the new version they are not. Here is a gist about my git interaction

https://gist.github.com/deiga/ae2ad8d42e7e7e1587e2

**Comment by scorphus** [comment]
How does your `fuck` alias definition looks like? I mean, what's in your `.zshrc` regarding TheFuck?

What does `alias` output? I Imagine `g` is among these aliases.

**Comment by deiga** [comment]
Aliases: https://gist.github.com/deiga/b6f397e89ed2a7939a3e

And my `.zprofile` includes `eval $(thefuck --alias)`

**Comment by Zarokka** [comment]
I had the same problem with 3.4
but with 3.6 it works fine for me again

**Comment by deiga** [comment]
Yeah, something in newer versions fixed this.
