### ISSUE TITLE
add a fuck

### ISSUE THREAD

**Issue by shahankit** [nvbn/thefuck#48]
I wish to add my own fuck. Any help as to where do I do that and how? Particularly I wish to add fuck for `cd` command whenever directory is not found i automatically creates one using mkdir. I also want to do so when given a parameter to fuck say `fuck hard`

**Comment by shakna-israel** [comment]
[Creating Your Own Rules](https://github.com/nvbn/thefuck/#creating-your-own-rules) is what you're looking for.

**Comment by shahankit** [comment]
Oh thanks sorry for not reading complete doc
