### ISSUE TITLE
Disables terminal keyboard echo upon "No Fucks Given" message.

### ISSUE THREAD

**Issue by mcgrew** [nvbn/thefuck#484]
thefuck turns off keyboard echo after certain commands, such as vim. This also breaks the output alignment of some commands, such as ls. To reproduce: 

* Open a new terminal (tested in xfce-terminal and lxvt)
* vim ~/.bashrc
* quit vim
* fuck
    * prints "No Fucks Given" in red
* type another command. Nothing is printed by keyboard strokes, although the typed command will execute.

**Comment by scorphus** [comment]
Thank you for opening the issue, @mcgrew! :+1:
