### ISSUE TITLE
Correct command not being pushed to fish history

### ISSUE THREAD

**Issue by plttn** [nvbn/thefuck#493]
I'm not entirely sure what's going on, but if I run `puthon`, invoke `fuck` to get `python`, my history output is
```
fuck ##the fuck that I typed to replace puthon with python
foo #previous commands
bar
```
but nothing of the fixed command.

**Comment by scorphus** [comment]
Yeah, 9b260eb moved shell's history responsibility over to the alias but I'm yet to update Fish alias regarding this change. Please bear with me, I might have some free time this week.

**Comment by plttn** [comment]
So i see that #495 added put to history back to Fish, but I'm not seeing any change on 3.9. Do i need to modify my alias?
