### ISSUE TITLE
cd to mkdir

### ISSUE THREAD

**Issue by shahankit** [nvbn/thefuck#50]
I'm trying to create a fuck for `cd: no such file or directory: <directory_name>` which gets converted to mkdir <directory_name>. 
I wrote following for match function but is says `No fuck given`
```
def match(command, settings):
    return ("cd: no such file or directory:" in command.stderr)
```
I tried printing stderr which contains `/bin/sh: 1: cd: can't cd to <directory_name>`. Why is it so and where do I get "cd: no such file or directory:"

**Comment by pottiep** [comment]
Ok baie dankie!☺

Sent from Yahoo Mail on Android

**Comment by shahankit** [comment]
@pottiep what does that mean?

**Comment by aatxe** [comment]
That appears to be some sort of spam?

**Comment by shahankit** [comment]
Whoo the user got deleted altogether : ghost. But still waiting for answer.

**Comment by nvbn** [comment]
@shahankit, python uses `/bin/sh` as a shell for `subprocess.Popen`, you should match for output from `/bin/sh`:
```bash
➜  /bin/sh -c "cd somewhere"
/bin/sh: 1: cd: can't cd to somewhere
```

**Comment by shahankit** [comment]
thanks @nvbn, that solved the issue.
This is my script for cd to mkdir
"""
# Automatically creates a new directory when no such file 
# directory is shown by cd
#
# Example:
# > cd newTemp
# cd: no such file or directory: newTemp

def match(command, settings):
	return ("cd: can't cd to " in command.stderr)


def get_new_command(command, settings):
    return 'mkdir '+command.stderr.rsplit(' ', 1)[1]
"""

**Comment by nwinkler** [comment]
Don't you want to `cd` into the created directory afterwards?

I would also use `mkdir -p` to create any missing directories if you try to do something like this `cd foo/bar/baz`.

**Comment by shahankit** [comment]
@nwinkler thanks nice suggestion. I'll do that.

**Comment by ncrocfer** [comment]
FYI, the `stderr` is the same when a user tries to enter in a file :
```
$ cd /foo/bar.txt
sh: 1: cd: can't cd to /foo/bar.txt
```

Or in a denied directory :
```
$ cd /root/
sh: 1: cd: can't cd to /root/
```

So be careful in your `match()` function to avoid these cases.

**Comment by shahankit** [comment]
@ncrocfer Then what should be used in matcher to avoid files and permission issues?
