### ISSUE TITLE
thefuck not recognizing eval in .bashrc on W10

### ISSUE THREAD

**Issue by dazahn** [nvbn/thefuck#508]
Exactly what it says on the tin. I just updated to the insider version of W10 in order to download the beta of [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about). I installed via pip3 and added
`eval "$(thefuck --alias)"`
to the .bashrc as instructed, however the error
`Seems like fuck alias isn't configured!
Please put eval $(thefuck --alias) in your ~/.bashrc.`
still persists. I understand that this version of Bash is in beta, but I was wondering if it was user error instead of incompatibility.

Thanks for the help in advance!

**Comment by dargueta-work** [comment]
Happening to me on OSX 10.11.4 as well. Tried installing it with Homebrew and via pip, neither works.

**Comment by dazahn** [comment]
Reinstalling fixed the issue
