### ISSUE TITLE
Always corrects to empty git subcommands

### ISSUE THREAD

**Issue by inputfalken** [nvbn/thefuck#509]
`thefuck` shows the right correction but always executes a empty git subcommand.

Actual output:

``` sh
λ Imagine ~ → git commot
git: 'commot' is not a git command. See 'git --help'.

Did you mean this?
        commit
λ Imagine ~ → fuck
git commit [enter/↑/↓/ctrl+c]
' is not a git command. See 'git --help'.
```

Expected output:
`git commit` being executed

This is run on cygwin with zsh.

**Comment by divykj** [comment]
**Buggy Configuration:**
OS: Windows
Terminal: Any *nix shell
Python: Any (Installed on Windows)

When on above configuration, the python uses CRLF for newline, but the shell does not understand CR character. This gives errors while setting the alias and running corrected commands.

Solution can be to prevent \n translation to CRLF when OS is Windows and Shell is not powershell.

If anybody has any idea how to prevent that translation, please do help.
