### ISSUE TITLE
Automatically add sudo to rm command

### ISSUE THREAD

**Issue by nodegin** [nvbn/thefuck#510]
Hi. I am trying to remove a directory/file that me does not have enough privilege to remove, if I adding `sudo` to the command then the directory will be removed successfully. It would be very nice if I can fuck the non-sudo `rm` command up using the thefuck.

<img width="651" alt="2016-05-22 9 26 33" src="https://cloud.githubusercontent.com/assets/8536244/15451621/7fc664f8-1fff-11e6-9365-d06718adb14e.png">

The expected result would be `sudo rm -r waifu2x-converter-cpp`

**Comment by tomoshi0809** [comment]
I guess it is difficult to equip your proposal. In the terminal, you inputted Ctrl + C to the "override" message, but this prevents  the fuck command catch the stderr or stdout (the fuck command depends on the message from the stderr or stdout). I recommend you should reply 'y' to the override message or add -f option to the 'rm' command.

**Comment by MarloweW** [comment]
Also rm command with auto sudo is dangerous.

**Comment by nodegin** [comment]
Understood. So should this issue be closed now?

**Comment by tomoshi0809** [comment]
Yes. I think so.
