### ISSUE TITLE
Fix order of arguments to `ln`

### ISSUE THREAD

**Issue by caesar** [nvbn/thefuck#511]
I have a pathological inability to get the arguments to `ln` in the right order.

For some reason I always think it's `ln -s <origin> <destination>` whereas in fact it is `ln -s <destination> <origin>`.

Can `fuck` fix this?

![screen shot 2016-05-25 at 10 27 28](https://cloud.githubusercontent.com/assets/1566516/15543794/4187cd3c-2264-11e6-81b3-ba74e2958174.png)

**Comment by nvbn** [comment]
> whereas in fact it is ln -s <destination> <origin>

Are you sure?

```
➜  /tmp echo origin > origin
➜  /tmp ln -s origin dest
➜  /tmp cat dest
origin
```

**Comment by caesar** [comment]
@nvbn that's what I mean, but we're using the words *origin* and *destination* the opposite way around. For me the *destination* is the file you're liking *to*, the origin is where you're liking *from*.
Clearly at least some other people think of it your way round, which is why the arguments are in that order I suppose.

Anyway, the point is that I tend to put the arguments the wrong way around. The ideal solution would be for me to learn to do it the right way around, but it hasn't happened yet....
Anyway, that's what `fuck` is for, right? :-D

**Comment by breeze9512** [comment]
I also want this function :)

**Comment by scorphus** [comment]
Any of you willing to code it? I'm happy to coach ☺

**Comment by nvbn** [comment]
Added in 3.10
