### ISSUE TITLE
Question: Is there an alternative to this project....

### ISSUE THREAD

**Issue by sbrl** [nvbn/thefuck#512]
...that doesn't contain bad language?

**Comment by sbrl** [comment]
@mcarton Unfortunately, I don't feel that an alias is enough. As somebody who doesn't swear at all, I'd feel extremely uncomfortable having this kind of language lying around my system.

**Comment by nvbn** [comment]
@sbrl you can fork it and replace all `fuck` in code with `butterfly`, or `rainbow` or whatewer you want.
