### ISSUE TITLE
It doesn't work on Win10 powershell after put alias in $profile

### ISSUE THREAD

**Issue by legendtang** [nvbn/thefuck#536]
I added the following to $profile
```powershell
iex "$(thefuck --alias)"
```

It still told me 
```
Seems like fuck alias isn't configured!
Please put iex "thefuck --alias" in your $profile.
More details - https://github.com/nvbn/thefuck#manual-installation
```

Manually exec `thefuck --alias` command, it shows:

```powershell
function fuck {
    $fuck = $(thefuck (Get-History -Count 1).CommandLine);
    if (-not [string]::IsNullOrWhiteSpace($fuck)) {
        if ($fuck.StartsWith("echo")) { $fuck = $fuck.Substring(5); }
        else { iex "$fuck"; }
    }
}
```

**Comment by legendtang** [comment]
For someone who also encountered this issue, it may probably be that powershell do not allow user to execute scripts on boot by default. You should change the security policy by input `set-ExecutionPolicy RemoteSigned` and re-open your powershell.

**Comment by ddspog** [comment]
I solve this putting this command on a Invoke-TheFuck.alias.ps1 file. I use this [cmder-powershell-powerline-prompt](https://github.com/AmrEldib/cmder-powershell-powerline-prompt) btw, so the file it's in the profile.d folder.

```powershell
# fuck
function Invoke-TheFuck {
    $history = (Get-History -Count 1).CommandLine;
    if (-not [string]::IsNullOrWhiteSpace($history)) {
        $fuck = $(thefuck $args $history);
        if (-not [string]::IsNullOrWhiteSpace($fuck)) {
            if ($fuck.StartsWith("echo")) { $fuck = $fuck.Substring(5); }
            else { Invoke-Expression "$fuck"; }
        }
    }
}

Set-Alias -name "fuck" -value "Invoke-TheFuck"
```

The only problem I have with this, it's that the first run always shows the #673 problem. So, after I restart my cmder Powershell session it's like this:

![image](https://user-images.githubusercontent.com/5065673/33806676-cd6ac484-ddb2-11e7-8822-0f3bfa373287.png)

**Comment by SaileshBK** [comment]
**Edit the profile script:**
**1)** You can edit your profile script using any text editor or PowerShell Integrated Scripting Environment (ISE). To open and edit your profile script, you can use the following command:

notepad $profile

**2)** add command:

iex "$(thefuck --alias)"

**3)** Save and close the profile script and load the profile by using command:

. $profile
