### ISSUE TITLE
Adding sudo works for `aura -Sy` but not `aura -Ay`

### ISSUE THREAD

**Issue by OJFord** [nvbn/thefuck#543]
`fuck` is unable to add `sudo` to an `aura -Ay` command:
```
$ aura -Ay foobar-beta-git  # from AUR
aura >>= You have to use `sudo` for that.
$ fuck
No fucks given
```

But works as expected for `aura -Sy`:
```
$ aura -Sy foobar  # pacman alias
error: you cannot perform this operation unless you are root.
aura >>= Please check your input.
$ fuck
sudo aura -Sy foobar [enter/↑/↓/ctrl+c]
```
It's slightly annoying anyway that the `aura` outut is different in these cases, but is it possible for `thefuck` to work-around? Or is the only way for `aura` to give a stderr message containing "root"?

**Comment by medakk** [comment]
Add the pattern "You have to use `sudo` for that." to [sudo.py](https://github.com/nvbn/thefuck/blob/fa1edd4baef2e37bc8d99dccf1f23e70b6999f9c/thefuck/rules/sudo.py).
