### ISSUE TITLE
Add support for returning multiple new command options in a rule.

### ISSUE THREAD

**Issue by JordonPhillips** [nvbn/thefuck#547]
I was writing a rule for a command that will return multiple possible options like so:

```
[...]

Invalid choice 'ba', maybe you meant:

  * bar
  * baz
```

It's easy enough to get that list and create a list of possible options, but the way rules work right now you can only return a single option. It would be awesome to be able to return all the possibilities for the user to cycle through.

**Comment by nvbn** [comment]
You can return a list of fixed commands, like in [no_command rule](https://github.com/nvbn/thefuck/blob/master/thefuck/rules/no_command.py#L38).

**Comment by JordonPhillips** [comment]
I see, looks like I missed the list[str] bit in the docs too. Thanks!
