### ISSUE TITLE
Coveralls duplicates PR comments

### ISSUE THREAD

**Issue by josephfrazier** [nvbn/thefuck#566]
On pull requests like https://github.com/nvbn/thefuck/pull/563, `coveralls` comments multiple times concerning the same commit. This was a known issue (https://github.com/lemurheavy/coveralls-public/issues/838), but it was closed without being fixed.

After reading through some of the issues linked in the coveralls issue, I found that switching to https://codecov.io/ can fix this, as [it doesn't have the same problem](https://github.com/codecov/support/issues/266#issuecomment-236967117). @nvbn, would you be willing to do this? I've tried it out on [my fork](https://github.com/josephfrazier/thefuck/tree/cf8a06efe3957ebdd37a172d513df000164e40e8), so you can see what the repo looks like. In addition, here's a sample pull request with the codecov comment and status checks: https://github.com/josephfrazier/thefuck/pull/3

If this sounds good to you, I can make a PR once the codecov.io account has been created. Thanks!

EDIT: Here are some more open coveralls issues about this problem:
- https://github.com/lemurheavy/coveralls-public/issues/491
- https://github.com/lemurheavy/coveralls-public/issues/512

**Comment by nvbn** [comment]
Fixed, now we run coveralls only on python 3.6 + linux build.

**Comment by josephfrazier** [comment]
Ah, that works too. Thanks!
