### ISSUE TITLE
Sudo not working with gem

### ISSUE THREAD

**Issue by tusharmakkar08** [nvbn/thefuck#574]
Hey @nvbn 

When I am trying to write `fuck` after `gem`. It doesn't work.
```
tusharmakkar08$ gem install travis
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/tusharmakkar08/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/travis-1.8.2/LICENSE
tusharmakkar08$ fuck
No fucks given
```

Fuck version
```
The Fuck 3.2 using Python 2.7.11
 ```

I am using bash on mac osx. 

I am willing to create a PR if you guys can give me a heads up from where to start.

Thanks.

**Comment by nvbn** [comment]
Fixed in previous releases. 
@tusharmakkar08, try to upgrade thefuck.
