### ISSUE TITLE
how to best write a rule that corrects missing space before subcommand e.g. npminstall, gitclone

### ISSUE THREAD

**Issue by jedwards1211** [nvbn/thefuck#579]
As far as I can tell thefuck is unable to correct `gitclone http://...` or `npminstall some-long-package...`

I'm sure I could easily create individual rules that work only for `npm` or `git` but I'm curious if anyone has any tips how I could make a generic rule that works for a bunch of programs with subcommands.

**Comment by nvbn** [comment]
Nice idea, it's very easy to implement rule like that. Look at the [implementation](https://github.com/nvbn/thefuck/blob/master/thefuck/rules/missing_space_before_subcommand.py) and [tests](https://github.com/nvbn/thefuck/blob/master/tests/rules/test_missing_space_before_subcommand.py).

**Comment by nvbn** [comment]
Added in 3.15.

**Comment by jedwards1211** [comment]
@nvbn awesome, thank you!
