### ISSUE TITLE
Rule to correct wrong SCM invoked (e.g "git diff" in a Hg repository)

### ISSUE THREAD

**Issue by Googulator** [nvbn/thefuck#587]
Currently, there are rules for correcting Git and Mercurial commands. However, a common mistake is not caught: invoking "git diff" in a Hg repository and vice versa.

Similarly, corrections for mixed-up commands like "git graft" or "hg checkout" would be nice (former should correct to "git cherry-pick", latter to "hg update").

**Comment by nvbn** [comment]
Added work in 3.15.
