### ISSUE TITLE
Seems like fuck alias isn't configured! Please put eval $(thefuck --alias) in your ~/.bashrc.

### ISSUE THREAD

**Issue by HesterG** [nvbn/thefuck#590]
After i put eval "$(thefuck --alias FUCK)" into both my ~/.bashrc and ~/.bash_profile, these still pumped out. And i also tried to reopen my terminal after these configurations. Really have no idea how to fix it.

**Comment by jmona789** [comment]
Did you also put `eval "$(thefuck --alias)"` in either of them?

**Comment by HesterG** [comment]
Yes that solves the problem!
