### ISSUE TITLE
New rule for path completion

### ISSUE THREAD

**Issue by luvagarwal** [nvbn/thefuck#591]
I use a utility which auto-completes file paths in my bash commands. For ex:
```
$ cd thefuck
Executing cd ~/gitrepos/forked/thefuck
```
It runs `cd` initially. If it fails, it catches the file name due to which it failed from the error message, substitutes it with complete path and run again.

If it is integrated in `thefuck`, it would look something like:
```
$ cd thefuck
bash: cd: thefuck: No such file or directory
$ fuck
# Execute: cd ~/gitrepos/forked/thefuck
```
It is not limited to `cd`. Any command that takes files / dirs as arguments are aliased with this utility as wrapper. Fuck version of those would look like:
```
$ mv thefuck .
mv: cannot stat 'thefuck': No such file or directory
$ fuck
# Execute: mv ~/gitrepos/forked/thefuck .
```
(Path completion is done on basis of history and locate output)

I use both, thefuck as well as my utility and was looking to integrate them.  I have added a quick test for the functionality [here](https://github.com/luviiit/thefuck/blob/167b82be8dd9eb96c919efe037ab0708b9a2cb20/tests/rules/test_path_complete.py).

My utility is written in bash and I would have to port it in Python. Would love to know your opinion on this before proceeding.

**Comment by nvbn** [comment]
Nice idea, I've added something similar in `path_from_history` rule, it works like:
```bash
➜ cd thefuck
cd: no such file or directory: thefuck
➜ fuck
cd ~/exp/thefuck [enter/↑/↓/ctrl+c]
```

**Comment by nvbn** [comment]
Added in 3.15.
