### ISSUE TITLE
Config path is deprecated

### ISSUE THREAD

**Issue by chrisfinazzo** [nvbn/thefuck#592]
Just hit this error under 3.14 and have since migrated. Might be useful to add something to the README to explain where this change came from - I don't see a recent issue that references it.

Thoughts??

<img width="585" alt="screen shot 2017-01-16 at 6 33 56 pm" src="https://cloud.githubusercontent.com/assets/1534882/22002719/293a0976-dc1c-11e6-8fb7-294fb2dc837c.png">

**Comment by nvbn** [comment]
It was changed more than year ago by #385. You just need to run:
```bash
mv ~/.thefuck ~/.config/
```
