### ISSUE TITLE
bashrc complains thefuck "command not found" 3 times when using scp

### ISSUE THREAD

**Issue by codeofcarson** [nvbn/thefuck#595]
I was copying a key from one box to another in Ubuntu 16.04 (grabbing keys from a mac), and got this. The command still works but I've not ever seen this complaint output. 

```
user@linuxBox:~/.ssh$ scp 198.0.2.154:~/.ssh/some-key-2017-01-24.pub ./some-key-2017-01-24.pub
Password:
/Users/user/.bashrc: line 1: thefuck: command not found
/Users/user/.bashrc: line 2: thefuck: command not found
/Users/user/.bashrc: line 3: thefuck: command not found
some-key-2017-01-24.pub                                         100%  409     0.4KB/s   00:00
```

**Comment by nvbn** [comment]
Strange, I can't reproduce this behavior. Can you show how you configured the alias?

**Comment by codeofcarson** [comment]
Unfortunately I have completely wiped and re-imaged that machine so I can't provide that information. Feel free to close if you haven't seen this issue before.

**Comment by jessetan** [comment]
I also have this when I scp a file to my macOS machine if `eval "$(thefuck --alias)"` is added to `.bashrc`, but not if its added to `.bash_profile`. So perhaps the suggestion of adding it to `.bashrc` should be removed from the instructions.
