### ISSUE TITLE
Arch AUR Package

### ISSUE THREAD

**Issue by jjryan** [nvbn/thefuck#6]
I created an AUR package for Arch Linux. This makes it easy for users to install on Arch. Not sure if you want to add a note to the install section or not.

https://aur.archlinux.org/packages/thefuck-git/

**Comment by felixonmars** [comment]
And I have added thefuck to [community] repository. Enjoy :P

**Comment by SoniEx2** [comment]
You should make it fix running pacman without sudo

**Comment by vikstrous** [comment]
I just tried it. It seems to work. Thanks!
I made a PR for fixing pacman without sudo: #30

**Comment by nvbn** [comment]
Thanks, added to wiki.
