### ISSUE TITLE
`fuck` requires sudo password

### ISSUE THREAD

**Issue by sascha-egerer** [nvbn/thefuck#610]
If i execute `fuck` it asks me for my password. What is the reason for that? I don't want to give root access to the script.

By the way:
fuck is not smart enough to in this case:
```
$ fuck
Password: 
Sorry, try again.
Password: # i typed "fuck" here 
Sorry, try again. # i would suggest that fuck fixes my input
Password:  # i typed "fuck" here 
sudo: 3 incorrect password attempts
```
`</ironic>`

**Comment by nvbn** [comment]
It shouldn't.
What version you use?
What os?

**Comment by sascha-egerer** [comment]
Oh fuck! I had an alias in place that executes the last command as sudo. It was named `fuck`.
