### ISSUE TITLE
Please put eval $(thefuck --alias) in your ~/.zshrc.

### ISSUE THREAD

**Issue by tforgione** [nvbn/thefuck#611]
Hi everyone,

this thing seems amazing. I tried to install it (on ArchLinux, under zsh), and I found quite ironic that when I typed `fuck` in my terminal, he told me

```
Seems like fuck alias isn't configured!
Please put eval $(thefuck --alias) in your ~/.zshrc.
More details - https://github.com/nvbn/thefuck#manual-installation
```

Since I've seen the example with `aptget install` changing to `apt-get install` and then, `sudo apt-get install`, I was quite disappointed that when I typed `fuck` again in the terminal, he didn't automatically add it in my zshrc and sourced it.

**Comment by tforgione** [comment]
(Sorry to have closed and reopened this issue, I thought it was a duplicate of #585 but it was not)

**Comment by stevechae** [comment]
It just means to add `eval $(thefuck --alias)` line to your `.zshrc` and reload your zsh shell. Just run the following and you should be good to go:

```
echo 'eval $(thefuck --alias)' >> ~/.zshrc; exec zsh
````

**Comment by tforgione** [comment]
Yeah but I mean, launching `fuck` a second time could do it by itself since it knows exactly what I'm supposed to do. Wouldn't that be awesome ?

**Comment by nvbn** [comment]
I guess the nicest way would be if first call to fuck would just configure everything automatically.
So it would be like:
```python
➜ fuck
Alias configured successfully. To apply changes please relaunch your shell or just run:
   source ~/.zshrc
```

**Comment by tforgione** [comment]
Yeah, or maybe you'd need to type `fuck` twice before it modifies your zshrc, like so
```
$ fuck
Seems like fuck alias isn't configured!
Please put eval $(thefuck --alias) in your ~/.zshrc.
More details - https://github.com/nvbn/thefuck#manual-installation
$ fuck
Alias configured successfully. To apply changes please relaunch your shell or just run:
   source ~/.zshrc
```

in case someone doesn't want its zshrc to be modified (for example, I have my aliases in a particular file that is sourced from my zshrc and I like to keep it that way).

I think its consistant with the successive corrections shown [in the gif in the readme](https://raw.githubusercontent.com/nvbn/thefuck/master/example.gif).

**Comment by nvbn** [comment]
So I've implemented something like this:
![tty](https://cloud.githubusercontent.com/assets/1114542/23875030/3ffa1d98-0838-11e7-8812-9ac2758ca5fd.gif)
(not released yet)

**Comment by tforgione** [comment]
This rocks so hard

**Comment by nvbn** [comment]
Should work in 3.15.
