### ISSUE TITLE
Not seeing the "did you mean" predictions.

### ISSUE THREAD

**Issue by Radther** [nvbn/thefuck#616]
When I miss type I don't see the "did you mean" message showing me the possible fixes. When I type `fuck` however it still works. 
<img width="682" alt="screen shot 2017-03-21 at 09 38 40" src="https://cloud.githubusercontent.com/assets/5844281/24141279/e423274c-0e1a-11e7-94b9-a2fd0efa34e0.png">

System Details:
- macOS: 10.12.4 (Beta)
- bash shell

Is there something I'm missing?

**Comment by nvbn** [comment]
"Did you mean" prediction isn't function of thefuck. Don't know about bash, but in zsh some https://github.com/robbyrussell/oh-my-zsh plugins can do that.

**Comment by Radther** [comment]
Ahh ok, thanks for clarifying that.
