### ISSUE TITLE
Take Time to Show the result in the first time

### ISSUE THREAD

**Issue by eslammahgoub** [nvbn/thefuck#627]
I'm using The Fuck 3.16 using Python 3.5.2.
my shell zsh on ubuntu
in the first time to get fuck result it take par two second so any reduce for this issue

**Comment by nvbn** [comment]
It's probably an unsolvable problem, because thefuck reruns previous command for getting its output.
If it's a different problem, please post `fuck` output with enabled debug output `export THEFUCK_DEBUG=true`.

**Comment by scorphus** [comment]
Closing for lack of response.
