### ISSUE TITLE
"no fucks given" with alias

### ISSUE THREAD

**Issue by ChrisJefferson** [nvbn/thefuck#635]
I like `thefuck`, but I don't like swearing in my terminal at work (sorry).

I'm happy with the alias option, but I still get the error message `no fucks given`. Would it be possible to change this to something SFW, when `--alias` was used to invoke the command (I don't mind what, and I would guess if someone is aliasing, it's probably to get a SFW program).

**Comment by Nightfirecat** [comment]
> You should place this command in your .bash_profile, .bashrc, .zshrc or other startup script:
>
>     eval $(thefuck --alias)
>     # You can use whatever you want as an alias, like for Mondays:
>     eval $(thefuck --alias FUCK)

I take that to mean that you can enter whatever alias you'd like in your .bash_profile/.bashrc/.zshrc:

```
eval $(thefuck --alias frick)
```

**Comment by jw4js** [comment]
@ChrisJefferson If you want it SFW you can patch it yourself. If you installed via pip, it's at `~/.local/lib/python*/site-packages/thefuck/ui.py` where `*` is the python version. Otherwise you have to find the file yourself. `No fucks given` is at line 72, you can change it to whatever you like.

**Comment by ChrisJefferson** [comment]
@jw4js : Yup, I just `grep`ed the whole source code for fucks, and found that `no fucks given` is the only user-visible one, so I changed it myself. Would a patch which disabled that if an alias was in use be acceptable (I'm not sure how nice it would look, would have to check if argv[0] was `fuck` I imagine).

**Comment by nvbn** [comment]
In 3.17 when alias isn't `fuck` the app prints `Nothing found`.

**Comment by ChrisJefferson** [comment]
Thanks!
