### ISSUE TITLE
ask for the .zsh-theme file in the readme.md

### ISSUE THREAD

**Issue by manoshape** [nvbn/thefuck#639]
what is the .zsh-theme file in the readme.md ? it is so beautiful!!

**Comment by nvbn** [comment]
As I remember it's https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme

And probably it's a default theme in oh-my-zsh.

**Comment by manoshape** [comment]
thanks，very nice of you，i get it！
