### ISSUE TITLE
Extend default rules

### ISSUE THREAD

**Issue by ahrenstein** [nvbn/thefuck#645]
I have an alias in my bash profile called "root" which attempts to SSH into a server as root.
`root server.com` = `ssh root@server.com`

I had copied ssh_known_hosts in my `~/.thefuck/rules/` directory and added root as a command to look for, but after the latest update, even after moving it to `~/.config/thefuck/rules/` it does not give me the option to correct the known host key for my root alias. Instead it just offers reboot, route or nslookup.

How can this be fixed?

Thanks!

**Comment by ahrenstein** [comment]
It seems editing the default rule to include the alias no longer works. So the latest version of thefuck no longer decodes bash aliases into the command aliased to them. Can this be correced?

**Comment by nvbn** [comment]
Can you post your extended rule?

**Comment by nvbn** [comment]
Also, can you try 3.17?, probably fixed.

**Comment by ahrenstein** [comment]
Sure. I basically just copied ssh_known_hosts.py and added "root" to the list of commands to watch for:

~/.config/thefuck/rules/ssh_known_hosts.py
```
import re
from thefuck.utils import for_app

commands = ('ssh', 'scp', 'root')

@for_app(*commands)
def match(command):
    if not command.script:
        return False
    if not command.script.startswith(commands):
        return False

    patterns = (
        r'WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!',
        r'WARNING: POSSIBLE DNS SPOOFING DETECTED!',
        r"Warning: the \S+ host key for '([^']+)' differs from the key for the IP address '([^']+)'",
    )

    return any(re.findall(pattern, command.stderr) for pattern in patterns)

def get_new_command(command):
    return command.script


def side_effect(old_cmd, command):
    offending_pattern = re.compile(
        r'(?:Offending (?:key for IP|\S+ key)|Matching host key) in ([^:]+):(\d+)',
        re.MULTILINE)
    offending = offending_pattern.findall(old_cmd.stderr)
    for filepath, lineno in offending:
        with open(filepath, 'r') as fh:
            lines = fh.readlines()
            del lines[int(lineno) - 1]
        with open(filepath, 'w') as fh:
            fh.writelines(lines)

# Optional:
priority = 5
enabled_by_default = True
```

Bash alias for root in ~/.profile
```
alias root='ssh -A -lroot'
```

**Comment by ahrenstein** [comment]
Also I'm installing thefuck via Homebrew so it doesn't seem to see 3.17 just yet.

**Comment by ahrenstein** [comment]
This appears to have been fixed in the latest version.
