### ISSUE TITLE
error: zsh: command not found: thefuck

### ISSUE THREAD

**Issue by Zane96** [nvbn/thefuck#650]
![Uploading 屏幕快照 2017-05-26 上午12.45.35.png…]()
![Uploading 屏幕快照 2017-05-26 上午12.45.59.png…]()
![2017-05-26 12 47 10](https://cloud.githubusercontent.com/assets/12124524/26460659/e994b220-41ac-11e7-82d2-55e9910cae72.png)

I have already installed python-dev and source .bash_profle;
But I still get command not found

**Comment by Zane96** [comment]
![Uploading 屏幕快照 2017-05-26 上午12.59.46.png…]()
![87d33eda-6788-4117-b2f7-7eefde85a5be](https://cloud.githubusercontent.com/assets/12124524/26461234/0dfb9fb4-41af-11e7-9523-1bc0bb27edda.png)

**Comment by Zane96** [comment]
![2f627934-9d36-4139-b37e-5571ac0a3c53](https://cloud.githubusercontent.com/assets/12124524/26461242/1b9b51aa-41af-11e7-8ce5-3e49e6db3c77.png)

**Comment by Zane96** [comment]
I think all things is ready....but it's not work

**Comment by hakale** [comment]
Same problem here.
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```
use `eval $(thefuck --alias)`. 
Get
`zsh: command not found: fuck`

**Comment by nvbn** [comment]
You can try to reinstall thefuck globally or change your path:
```
export PATH="$PATH:~/.local/bin/"`
```

**Comment by Zane96** [comment]
Thx, the problem has been fixed!!~

**Comment by bl4ckdu5t** [comment]
The solution is to simply make it available to zsh which could also be by moving `eval $(thefuck --alias)` from .bash_profile to your .zshrc and running `source ~/.zshrc`. If problem is fixed you may now close the issue

**Comment by Epse** [comment]
@Zane96 if it's fixed, could you close the issue?

**Comment by Zane96** [comment]
Yes, of course. Thanks

**Comment by caofanCPU** [comment]
Sometimes there're two versions of python about 2.x and 3.x, after installing thefuck, then we can edit .zshrc like this(in my server as example):
> **export PATH="$PATH:/usr/local/python3/bin"**
> **eval "$(thefuck --alias)"**

you can use **pip3 unintall thefuck** to find out where thefuck located

![image](https://user-images.githubusercontent.com/26968137/79107249-a553d800-7da6-11ea-96b1-17ae0d670f47.png)

**Comment by wadimsewo** [comment]
I added "eval $(thefuck --alias)" to my zsh file, but it still doesn't work.
`/Users/wadim/.zshrc:121: command not found: thefuck`

**Comment by zhongjiajie** [comment]
I have the same problem, using Mac and installed with homebrew, the error message is 

```log
command not found: thefuck
```

every time I create new terminal session can see that error message, but when I run `thefuck` it can be found. I fix by put `thefuck` after `homebrew` in `.zshrc`.

```bash
# homebrew
PATH=/opt/homebrew/bin:$PATH
# export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
export HOMEBREW_NO_AUTO_UPDATE=1

# The fuck
export PATH="$PATH:~/.local/bin/"
eval $(thefuck --alias)
```

**Comment by eniel-rodriguez** [comment]
I use Ubuntu 20.04, and it only works by placing the lines practically at the beginning of the .zshrc file:

```
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# The fuck
export PATH="$HOME/.local/bin/:$PATH"
eval $(thefuck --alias)

```

**Comment by ziziyin** [comment]
> You can try to reinstall thefuck globally or change your path:
> 
> ```
> export PATH="$PATH:~/.local/bin/"
> ```

useful
