### ISSUE TITLE
Ubuntu 17.04 normal installation does not work

### ISSUE THREAD

**Issue by pachonk** [nvbn/thefuck#651]
If I install python for pip3, then install with `pip3 install --user thefuck`, the binary is placed into an unknown location outside of my path.

If I run `sudo pip3 install thefuck`, it installs it as expected, but then it's also installed globally.

I believe this relates to #650 and #646

**Comment by nvbn** [comment]
I've updated readme, I guess it would be better to install it globally by default.

**Comment by pachonk** [comment]
Sounds good. Closing this issue.
