### ISSUE TITLE
after uninstall still got "-bash: thefuck: command not found"

### ISSUE THREAD

**Issue by BertieJim** [nvbn/thefuck#656]
Sorry because of some reasons I have to uninstall this very useful and cool command.
I forgot how I install it it's been a while,and I uninstall it with
pip uninstall thefuck
however,everytime I open terminal(this is a Mac),it is like this:
![image](https://cloud.githubusercontent.com/assets/9475685/26779891/cb20383a-4a19-11e7-931a-7d6cd6fc3322.png)

Don't know how to make it disappear
any help will be very welcome

**Comment by BertieJim** [comment]
Is it because during the installing it changed some where in my terminal?
I google it but didn't find any answers.
What can I do?
T T

**Comment by nvbn** [comment]
You need to remove `eval $(thefuck --alias)` from your `.bashrc`.

**Comment by Epse** [comment]
@BertieJim if it's fixed might help if you close the issue
