### ISSUE TITLE
souce ~/.zshrc suggests touch instead of source

### ISSUE THREAD

**Issue by OmgImAlexis** [nvbn/thefuck#665]
```
➜  twistly-api git:(master) ✗ souce ~/.zshrc
zsh: command not found: souce
➜  twistly-api git:(master) ✗ fuck
touch ~/.zshrc [enter/↑/↓/ctrl+c]
```

**Comment by UtkrishtDhankar** [comment]
I cannot replicate the issue with a fresh install. With the debug option set, for me the matched rule that it gets is `no_command`, which fetches close matches of the comand given. It searches the recently used commands in your history, and executables in the usual executable directories.

The only explanation I have is that you recently used `touch`, then the first option that it got from your history was `touch` itself, so it displayed that first. In that case, you should be able to scroll with the arrow keys to get the other commands (including `source`). If that doesn't work, can you try the same thing again, only with the debug options enabled, and confirm that the same rule (`no_command`) is being executed?

**Comment by OmgImAlexis** [comment]
Seems to be working. Not sure what the issue was before.
