### ISSUE TITLE
How to change the word f**k 

### ISSUE THREAD

**Issue by S2606** [nvbn/thefuck#674]
How can we change the word f**k to some other word??

**Comment by scorphus** [comment]
Please refer to the [documentation](https://github.com/nvbn/thefuck#installation):

> You should place this command in your `.bash_profile`, `.bashrc`, `.zshrc` or other startup script:
>
```bash
eval $(thefuck --alias)
# You can use whatever you want as an alias, like for Mondays:
eval $(thefuck --alias FUCK)```
