### ISSUE TITLE
Можно ли реализовать общее правило, исправляющее раскладку клавиатуры?

### ISSUE THREAD

**Issue by klinkin** [nvbn/thefuck#68]
Для примера:
"св юю" --> "cd .."
"ды -дф" --> "ls -la"

Я сделал несколько правил для самых моих популярных опечаток в раскладке. 
Но хочется общее красивое))

**Comment by nvbn** [comment]
В 1.16+ должно работать из коробки.

**Comment by platinumthinker** [comment]
Use kdbb for remember language per windows

**Comment by klinkin** [comment]
@nvbn Агонь, пошел тестить) :beer:

**Comment by klinkin** [comment]
It's works, thx!
