### ISSUE TITLE
thefuck suggests erroneous git command for simple typo in "git push"

### ISSUE THREAD

**Issue by bigbrett** [nvbn/thefuck#681]
thefuck suggests a nonexistent git command as a solution for one of the most commonly used commands: git push

```
brett: $ gi tpush
  gi: command not found
brett: $ fuck
  git tpush [enter/↑/↓/ctrl+c]  <-- there is no git tpush
```

```
brett: $ thefuck --version
The Fuck 3.18 using Python 2.7.12
```

**Comment by BenGitsCode** [comment]
I only came across in reading issues and don't have a solution, here's me getting different output on the same input with`Python 2.7.10`—FWIW in resolving this issue.
<img width="900" alt="image 2017-08-26 at 12 38 41 am public" src="https://user-images.githubusercontent.com/16841950/29738674-99744646-89f7-11e7-9806-839ec8b79839.png">

**Comment by scorphus** [comment]
Works if you double fuck:

```
root@aa8752156600:/# gi tpush
bash: gi: command not found
root@aa8752156600:/# fuck
git tpush [enter/↑/↓/ctrl+c]
git: 'tpush' is not a git command. See 'git --help'.

Did you mean this?
        push
root@aa8752156600:/# fuck
git push [enter/↑/↓/ctrl+c]
fatal: Not a git repository (or any of the parent directories): .git
root@aa8752156600:/#
```
