### ISSUE TITLE
TheFuck doesn't see my zsh aliases :(

### ISSUE THREAD

**Issue by sullyj3** [nvbn/thefuck#69]
Rules in which get_new_command returns a zsh alias result in command not found errors. Example:
```zsh
> alias
[...]
baz='echo "it worked!"'
[...]

> cat .thefuck/rules/aliastest.py
def match(command, settings):
    return (command.script == 'foo')

def get_new_command(command, settings):
    return 'baz'

> foo
zsh: command not found: foo

> fuck
baz
zsh: command not found: baz
```

**Comment by sullyj3** [comment]
I've done some poking around, and the issue seems to be that subprocess.Popen doesn't respect shell aliases. I'll do a bit more research into whether there's any way around this.

**Comment by thiderman** [comment]
Never tried it, but maybe `shell=True` (which is [not recommended](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments)) will make it source the shell rc files and therefore get your aliases?

**Comment by shockone** [comment]
I have a similar situation. Please support aliases. For example, I have `gp` for `git push`, and it does not match the `git_push` rule.

**Comment by nvbn** [comment]
Try 1.33+, aliases should work.

**Comment by shockone** [comment]
@nvbn, awesome, it works!

**Comment by sullyj3** [comment]
(y)
Thanks!

**Comment by MadaraUchiha** [comment]
There appears to be a regression in this regard. I'm seeing this bug again (I saw it when it was first raised, I saw it fixed, and now I see it again).

To reproduce: 
Add `gp` as an alias for `git push`, create a branch and type `gp` to get the upstream error message, then invoke thefuck.

Expected: `git_push` rule invoked, and thefuck offers `git push --set-upstream ....` as alternative.
Actual: thefuck offers `sudo apt-get install pari-gp && gp`.

**Comment by thickpaddy** [comment]
I've just noticed the same regression. I've tested with v1.43 and 3.0 and see the same issue...

```
~/code/foo[master]$ gpr
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

~/code/foo[master]$ fuck
No fuck given
~/code/foo[master]$ type gpr
gpr is aliased to `git pull --rebase'
~/code/foo[master]$ git pull --rebase
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

~/code/foo[master]$ fuck
git branch --set-upstream-to=origin/master master && git pull --rebase
Branch master set up to track remote branch master from origin by rebasing.
Current branch master is up to date.
~/code/foo[master]$
```

**Comment by MadaraUchiha** [comment]
Hey guys, bumping this, can it be reopened? The issue is still very much there.

**Comment by braineo** [comment]
Hi guys, do you see this regression again? I am using 3.18 and it is not seeing my gp alias
