### ISSUE TITLE
The "manual installation" section is gone but still used

### ISSUE THREAD

**Issue by NyanKiyoshi** [nvbn/thefuck#695]
When trying to use `fuck` without the alias configured, it links to a removed section (which was [that](https://github.com/nvbn/thefuck/tree/439287256817b77fd2d88a8601d4f491196f2130#manual-installation)).
```
$ fuck
Seems like fuck alias isn't configured!
More details - https://github.com/nvbn/thefuck#manual-installation
```
The link should probably be replaced link by https://github.com/nvbn/thefuck/wiki/Shell-aliases or https://github.com/nvbn/thefuck#installation.

----

The Fuck 3.23 using Python 3.6.2

Shell: bash
System: Gentoo

**Comment by nvbn** [comment]
@NyanKiyoshi the old link should work from now.

**Comment by scorphus** [comment]
https://github.com/nvbn/thefuck#manual-installation is working again 🎉  Thanks @nvbn
