### ISSUE TITLE
[WARN] Script not found in output log  No fucks given

### ISSUE THREAD

**Issue by Enochenti** [nvbn/thefuck#714]
zsh
macos

If I use instant mode

```
>puthon
zsh: command not found: puthon

>fuck
[WARN] Script not found in output log
No fucks given

>which fuck
fuck () {
	TF_PREVIOUS=$(fc -ln -1 | tail -n 1)
	TF_CMD=$(
                    TF_ALIAS=fuck
                    TF_SHELL_ALIASES=$(alias)
                    PYTHONIOENCODING=utf-8
                    thefuck $TF_PREVIOUS THEFUCK_ARGUMENT_PLACEHOLDER $*
                )  && eval $TF_CMD
	test -n "$TF_CMD" && print -s $TF_CMD
}

>thefuck --version
The Fuck 3.24 using Python 3.6.3
```

If I use normal mode
```
>fuck
usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
               [--enable-experimental-instant-mode] [-h] [-y | -r] [-d]
               [command [command ...]]
```

**Comment by Enochenti** [comment]
When I use 
`eval $(thefuck --alias --enable-experimental-instant-mode)`
in my .zshrc ,I get
>fuck
```
[WARN] Script not found in output log
No fucks given
```
but I use 
`eval "$(thefuck --alias --enable-experimental-instant-mode)"`
get this too
`>fuck
usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
               [--enable-experimental-instant-mode] [-h] [-y | -r] [-d]
               [command [command ...]]`

so,it`s not the problem of instant mode.
then another problem homebrew asked me to use eval "XXXX",
but README.md asked me to use eval XXXX.
Is that because I use oh-my-zsh or I use macOS?

**Comment by jukben** [comment]
I have figured it out. I had to use `eval $(thefuck --alias)` in my `.zshrc` without quotes.

**Comment by jukben** [comment]
I had the same issue but I've figured it out. I had to use eval $(thefuck --alias) in my .zshrc without quotes.

**Comment by Enochenti** [comment]
works now，thanks

**Comment by faelin** [comment]
I am still experiencing this issue. Installed thefuck using homebrew on OS X, using ZSH with oh-my-zsh (though that shouldn't be relevant), added the eval line without quotes as the final line of my `.zshrc`:

```
eval $(thefuck --alias)
```

**Comment by jeriewang** [comment]
I can confirm that it's still an issue with the instant-mode and zshrc.

**Comment by bbminhtri** [comment]
+1 on the issue with instant mode and zshrc, can we reopen this issue?

**Comment by martin-sweeny** [comment]
Can confirm that this warning is shown with `--enable-experimental-instant-mode` with `zsh`

Without experimental instant mode flag: 

![without experimental instant mode flag](https://user-images.githubusercontent.com/3329959/110234511-e726c900-7ef8-11eb-830b-1a2a3b592733.png)

With experimental instant mode flag:

![with experimental instant mode flag](https://user-images.githubusercontent.com/3329959/110234446-826b6e80-7ef8-11eb-9495-29f4d60814c3.png)

**Comment by xmika** [comment]
+1 here, following instructions with --enable-experimental-instant-mode it doesn't work in zsh nor bash.

**Comment by junukwon7** [comment]
+1. Still getting the same message

**Comment by estiens** [comment]
+1

**Comment by brucecantarim** [comment]
+1

**Comment by krishna-parajuli** [comment]
+1

**Comment by codehath** [comment]
+1

**Comment by Wahid7852** [comment]
+1

**Comment by Vahtera** [comment]
+1 Still the same issue. The Fuck 3.29, Python 3.11.2, Bash 5.2.15(1)-release
