### ISSUE TITLE
ImportError: No module named fcntl

### ISSUE THREAD

**Issue by minecrawler** [nvbn/thefuck#715]
On Windows7 x64, Powershell.

According to [this post on SO](https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows), you have to use winapi on Windows instead. Is it possible to fix this issue?

**Comment by jameshal** [comment]
Looks like this broke with the addition of the internal shell logger in d2c70bd8. I switched back to 3.23 for now (on Windows 7 x64, msys bash).

**Comment by josephfrazier** [comment]
It looks like https://github.com/nvbn/thefuck/commit/08082e606be80b45a5738e60bf5ad7aaa9d206ee fixed the issue, so I'm closing this. Let me know if that's not the case, and I'll gladly re-open!
