### ISSUE TITLE
Cannot run fuck in zsh without export errors

### ISSUE THREAD

**Issue by icithis** [nvbn/thefuck#718]
Installed via pip. Ran eval "$(thefuck --alias)" in both bash and zsh. $ fuck then produces 'No fucks given' in bash while in zsh it complains about invalid arguments.
```
$ eval "$(thefuck --alias)"
$ fuck
fuck:export:3: not valid in this context: -'
fuck:3: not an identifier: [skip
```

Also FWIW:
```
$ zsh --version
zsh 4.3.11 (x86_64-redhat-linux-gnu)
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
```

**Comment by iraquitan** [comment]
Almost same problem here:
```zsh
$ fuck
fuck:export: not valid in this context: -'
pyenv:11: command not found: pyenv                                                                                                                                                                                                                                                                                                                                        
prompt_context:10: command not found: whoami
prompt_dir:1: command not found: sed
prompt_background_jobs:1: command not found: wc
prompt_background_jobs:2: command not found: awk
```

Additional info:
```zsh
$ zsh --version                                                                                                                                                                                                                                                                                                     
zsh 5.4.2 (x86_64-apple-darwin15.6.0)
$ sw_vers                                                                                                                                                                                                                                                                                                           
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G17023

```

**Comment by yeonzi** [comment]
it seems that was a issue of zsh.

when run `export TF_SHELL_ALIASES=$(alias)` in zsh, you can see the same error.

run `unalias -- -` and this error will disappear, but another error comes.

my way to deal with this problem is not use `eval "$(thefuck --alias)"` in ~/.zshrc

run `thefuck --alias` in your shell, delete the line which contain `export TF_SHELL_ALIASES=$(alias)`, and write the output in your .zshrc

just like

```
fuck () {
    TF_PYTHONIOENCODING=$PYTHONIOENCODING;
    export TF_ALIAS=fuck;
    export TF_HISTORY="$(fc -ln -10)";
    export PYTHONIOENCODING=utf-8;
    TF_CMD=$(
        thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
    ) && eval $TF_CMD;
    unset TF_HISTORY;
    export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
    test -n "$TF_CMD" && print -s $TF_CMD
}
```

It may not the best way to deal with this problem, but it really works.

**Comment by wrecklass** [comment]
It appears that the export won't allow aliases that start with non alphanumeric characters. I made this change to the third line:

`TF_SHELL_ALIASES = $(alias | grep "^[a-zA-Z0-9]")`
And it seems to be working fine for me now.

**Comment by davidnagli** [comment]
I have the same issue. Is there an official fix?

**Comment by scorphus** [comment]
Hello! I cannot reproduce this one:
```
$ eval "$(thefuck --alias fuck)"
$ fuck
Nothing found
$ functions fuck
fuck () {
	TF_PYTHONIOENCODING=$PYTHONIOENCODING 
	export TF_SHELL=zsh 
	export TF_ALIAS=fuck 
	export TF_SHELL_ALIASES=$(alias) 
	export TF_HISTORY="$(fc -ln -10)" 
	export PYTHONIOENCODING=utf-8 
	TF_CMD=$(
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
                )  && eval $TF_CMD
	unset TF_HISTORY
	export PYTHONIOENCODING=$TF_PYTHONIOENCODING 
	test -n "$TF_CMD" && print -s $TF_CMD
}
$ alias @asdf='echo this is asdf'
$ alias _wow='echo wow alias'        
$ alias
@asdf='echo this is asdf'
_wow='echo wow alias'
which-command=whence
$ @asdf
this is asdf
$ @@asdf
zsh: command not found: @@asdf
$ fuck
@asdf [enter/↑/↓/ctrl+c]
this is asdf
```
Versions:
```
$ grep RELEASE= /etc/linuxmint/info
RELEASE=18.3
$ zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
$ thefuck --version
The Fuck 3.25 using Python 3.6.1
```
Looks like I'm missing something. But what?

ps.: I'll try with a newer zsh and post the results

**Comment by SilvesterHsu** [comment]
@scorphus Thefuck works fine on Ubuntu with zsh, but I met the above problen on mac.

**Comment by scorphus** [comment]
What zsh version, @SilvesterHsu?

**Comment by rosiecakes** [comment]
having this exact issue on mac as well - zsh 5.2 (x86_64-apple-darwin15.6.0)

**Comment by omershelef** [comment]
have this same issue on mac. any solution?

**Comment by scorphus** [comment]
I still can't reproduce this issue. Can you please share your aliases? IWO output of `alias` omitting any sensitive information, of course. Thanks.

**Comment by whirlp00l** [comment]
I have this problem with `zsh 5.0.2 (x86_64-pc-linux-gnu)` and have the `alias` output as following:
```
fuck () {
                TF_PYTHONIOENCODING=$PYTHONIOENCODING;
                export TF_SHELL=zsh;
                export TF_ALIAS=fuck;
                export TF_SHELL_ALIASES=$(alias);
                export TF_HISTORY="$(fc -ln -10)";
                export PYTHONIOENCODING=utf-8;
                TF_CMD=$(
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
                ) && eval $TF_CMD;
                unset TF_HISTORY;
                export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
                test -n "$TF_CMD" && print -s $TF_CMD
            }
```

**Comment by scorphus** [comment]
So this is not an issue anymore since some 5.2 minor (?) version:

```
1b23d830ba7f# echo $ZSH_VERSION
5.2
1b23d830ba7f# zsh --version
zsh 5.2 (x86_64-alpine-linux-musl)
1b23d830ba7f# unalias -m '*'
1b23d830ba7f# alias
1b23d830ba7f# alias ll='ls -a'
1b23d830ba7f# alias
ll='ls -a'
1b23d830ba7f# foo=$(alias)
1b23d830ba7f# export foo=$(alias)
1b23d830ba7f# export foo="$(alias)"
1b23d830ba7f# print $foo
ll='ls -a'
```

Zsh 5.2 was released almost 3 years ago.

The question now is: should we support old versions?

Please cast your vote with either 👍 or 👎 reaction to this very message:

![image](https://user-images.githubusercontent.com/2112697/41915923-28fc7082-7957-11e8-8885-accb9a42ed35.png)

Thanks!

**Comment by sqzrmhj** [comment]
> it seems that was a issue of zsh.
> 
> when run `export TF_SHELL_ALIASES=$(alias)` in zsh, you can see the same error.
> 
> run `unalias -- -` and this error will disappear, but another error comes.
> 
> my way to deal with this problem is not use `eval "$(thefuck --alias)"` in ~/.zshrc
> 
> run `thefuck --alias` in your shell, delete the line which contain `export TF_SHELL_ALIASES=$(alias)`, and write the output in your .zshrc
> 
> just like
> 
> ```
> fuck () {
>     TF_PYTHONIOENCODING=$PYTHONIOENCODING;
>     export TF_ALIAS=fuck;
>     export TF_HISTORY="$(fc -ln -10)";
>     export PYTHONIOENCODING=utf-8;
>     TF_CMD=$(
>         thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
>     ) && eval $TF_CMD;
>     unset TF_HISTORY;
>     export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
>     test -n "$TF_CMD" && print -s $TF_CMD
> }
> ```
> It may not the best way to deal with this problem, but it really works.

fantastic
