### ISSUE TITLE
Terminal prompt takes forever to appear. eval $(thefuck --alias)

### ISSUE THREAD

**Issue by johnpiers** [nvbn/thefuck#721]
zsh 5.4.2 (x86_64-unknown-linux-gnu)
The Fuck 3.24 using Python 3.6.2
OS: Arch Linux x86_64 Kernel Release: 4.13.9-1-ARCH
Ok, so I'm not sure if this is a bug or if I've done something wrong. I noticed that when opening any terminal, the prompt would take about 10 to 15 secs before it appeared. I eventually found this in my ~/.zshrc under:

```
# alias
alias pacupg='sudo pacman -Syu'
alias ls='ls --color=auto -lh'
alias l='ls'
echo 'eval $(thefuck --alias)' >> ~/.zshrc

# run ls after directory change
function chpwd() {
    emulate -L zsh
    ls
}

eval $(thefuck --alias)

```
There were about a hundred of these, **eval $(thefuck --alias)** entries at the bottom of zshrc
I removed them and when opening a terminal window, everything is instantaneous, no lag at all. So after saving the config and exiting, proceed to open another terminal and for every subsequent terminal window that I open it adds one more of these lines and obviously after a while when i've opened a few hundred of these terminal windows over a period of time I have a few hundred of these entries in my **zshrc**.
To stop this behaviour (as a temporary measure) I commented out the line  **echo 'eval $(thefuck --alias)' >> ~/.zshrc** but presume that is not the correct way to go about it. I'm definitely a rookie when it comes to these things so apologies if I've gone about this in the wrong way, here and on my PC!

**Comment by Rom1deTroyes** [comment]
Le Saturday 28 Oct 2017 à 23:15:24 (+0000), John Piers Cilliers a écrit :

Hello !

> alias l='ls'
> echo 'eval $(thefuck --alias)' >> ~/.zshrc

So, each time you open a zsh session (login, run a terminal, ...) you
add the line 'eval $(thefuck --alias)' at the bottom of your .zshrc
config file...

Comment (or remove) this line, and every thing will go round (-:

> }
> 
> eval $(thefuck --alias)

Keep just one of this line at the end, btw !

> There were about a hundred of these, **eval $(thefuck --alias)** entries at the bottom of zshrc

Yes, you add one each time the `echo >> ~/.zshrc` is evalued, so it
might grow quickly !

> I removed them and when opening a terminal window, everything is
> instantaneous, no lag at all.

Yep, you don't eval the alias a hundred of time (-:

> So after saving the config and exiting, proceed to open another
> terminal and for every subsequent terminal window that I open it
> adds one more of these lines

Yes, that what the unwanted `echo >> ~/.zshrc` command do...

> and obviously after a while when i've opened a few hundred of these
> terminal windows over a period of time I have a few hundred of these
> entries in my **zshrc**.

Yep, you've point it : the error is right there...

> To stop this behaviour (as a temporary measure) I commented out the
> line  **echo 'eval $(thefuck --alias)' >> ~/.zshrc**

... And you've found the solution !

> but presume that is not the correct way to go about it.

The `echo 'eval $(thefuck --alias)' >> ~/.zshrc` has to be run in a
terminal once to write the `eval $(thefuck --alias)` at the end of your
`~/.zshrc` config file.

> I'm definitely a rookie when it comes to these things so apologies
> if I've gone about this in the wrong way, here and on my PC! 

Well, if you messed it, it may be a problem in the documentation, so
feel free to point out where you miss something, and the doc will be
more clear and precise for all non-developers user (-:

++
    Romain
-- 
Je vote [OUI] a la création de fr.rec.chasse.newbies
-+- AT in: Guide du Cabaliste Usenet - Bien configurer son newbie -+-

**Comment by johnpiers** [comment]
Shot man, totally cool. Really appreciate the answer(s) Loving this, keep up the good work! Thanks again! Stay well.
