### ISSUE TITLE
Installation failed on Debian 9 (stretch)

### ISSUE THREAD

**Issue by Geolim4** [nvbn/thefuck#750]
I got this error :(

![image](https://user-images.githubusercontent.com/1332071/34451899-925cf268-ed34-11e7-9558-565c039ea52a.png)

**Comment by josephfrazier** [comment]
It's hard to say without more information, but it seems like something might be messed up (or "confused") with your Python installation. As a workaround, you could try to install the Homebrew version (which should bring its own Python with it) using [Linuxbrew](http://linuxbrew.sh/). This is how I do it, and it works well for me.

**Comment by Geolim4** [comment]
Okay thanks !
