### ISSUE TITLE
require_confirmation not working on fish

### ISSUE THREAD

**Issue by installgen2** [nvbn/thefuck#76]
Running fuck with require_confirmation enabled doesn't work in fish shell. Instead of prompting for user input, it simply outputs ```[Enter/Ctrl+C]⏎ ``` and exits. Running without it enabled works as expected, see the picture bellow for more info. On the left is disabled, on the right is enabled.

![njkfgo](http://a.pomf.se/njkfgo.png)

**Comment by daenney** [comment]
Can confirm.

**Comment by mbirth** [comment]
I fixed it by changing my alias to:

```
function fuck -d "Magnificient app which corrects your previous console command."
    thefuck $history[2]
end
```

**Comment by installgen2** [comment]
@mbirth that doesn't work, that just results in pic related

![broken](http://a.pomf.se/iqirlw.png)

**Comment by daenney** [comment]
Same. I just get the replaced command printed on the console, not actually executed.

**Comment by steamraven** [comment]
This is related to a fish bug: fish-shell/fish-shell#1362
Basically, when running a command in parenthesis, fish does not give the command a stdin.  Thus, thefuck doesn't have a stdin.  

 I though of moving the confirmation out to the shell with something like the read command. But that hits fish-shell/fish-shell#1820, which prevents the contents of the eval from getting a stdin as well.

**Comment by mbirth** [comment]
Okay, this time I tested it before posting and the workaround from the [fzf README](https://github.com/junegunn/fzf#fish-shell) seems to work for me:

```
function fuck -d "Magnificient app which corrects your previous console command."                                                                                                                                                     
    thefuck $history[2] > /tmp/thefuck.sh
    . /tmp/thefuck.sh
end
```

**Comment by installgen2** [comment]
Yay it works! Well, kinda, it still executes the wrong command, but that can be fixed by changing it to $history[1]. See pic below.

![picture](http://a.pomf.se/edkcgh.png)

**Comment by scorphus** [comment]
Please check above referenced commit. BTW, I've subscribed to https://github.com/fish-shell/fish-shell/issues/1362 to make future amendments to the documentation.

**Comment by scorphus** [comment]
And thanks @mbirth for pointing out the solution.

**Comment by nvbn** [comment]
Is it works now?

**Comment by scorphus** [comment]
Yes, it does. The wiki contains a working function which makes confirmation work. We can close this issue.
