### ISSUE TITLE
Syntax errors in fish shell

### ISSUE THREAD

**Issue by Genora51** [nvbn/thefuck#768]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):

    The Fuck 3.25 using Python 3.6.4

Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):

    fish, version 2.7.1

Your system (Debian 7, ArchLinux, Windows, etc.):

MacOS High Sierra 10.13.2

How to reproduce the bug:

    Place into config.fish `thefuck --alias | source`, as in instructions.

On terminal startup, gives Fish syntax error message relating to the use of `&&` rather than `; and` in fish, plus more relating to the use of variable setting. Essentially it seems that `thefuck --alias` gives out a result that only runs in bash.

**Comment by Genora51** [comment]
Ok, so it seems as though PR #767 fixes this issue. I recommend merging pronto, before more people experience this problem with the current version.

**Comment by Jomik** [comment]
Interesting, i have no issue on `The Fuck 3.27 using Python 3.6.7`, but I decided to make a function rather than source in `config.fish`. Maybe `thefuck --alias` is outputting the bash function rather than the fish function..?

**Comment by Genora51** [comment]
I'm fairly sure that's the issue; I believe that's what the PR fixes.

**Comment by scorphus** [comment]
Fixed in 6290560
