### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by zhangenming** [nvbn/thefuck#771]
Reaction is too slow, although not a solid state drive, but not normal, you are the same?

**Comment by josephfrazier** [comment]
If you're having trouble with `fuck` running slowly, maybe these issues would help (found by searching the issues for "slow"):

* https://github.com/nvbn/thefuck/issues/353 - Command is slow
* https://github.com/nvbn/thefuck/issues/576 - "thefuck" typically loads slower that I manually type the command
* https://github.com/nvbn/thefuck/issues/660 - Slow execution time
