### ISSUE TITLE
Use python 3 by default if it is set as default version of python.

### ISSUE THREAD

**Issue by ankibalyan** [nvbn/thefuck#779]
It always show a Warning for python 3

    [WARN] The Fuck will drop Python 2 support soon, more details https://github.com/nvbn/thefuck/issues/685
    [WARN] Instant mode requires Python 3

The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):

    The Fuck 3.25 using Python 2.7.12

Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):

    GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

Your system (Debian 7, ArchLinux, Windows, etc.):

    Ubuntu 16.04.3 LTS

How to reproduce the bug:

    Open in any terminal window

Anything else you think is relevant:

    ~$ python --version
    Python 3.6.3 :: Anaconda, Inc.

    ~$ pip --version
     pip 9.0.1 from /home/devserve/anaconda3/lib/python3.6/site-packages (python 3.6)

**Comment by nvbn** [comment]
On linux you need to install it with pip from python 3 and it will use python 3.
Otherwise it can't use python 3.

**Comment by BillLucky** [comment]
brew upgrade thefuck
