### ISSUE TITLE
Permission denied: '/tmp/thefuck.last_not_configured_run'

### ISSUE THREAD

**Issue by wligtenberg** [nvbn/thefuck#788]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):

The Fuck 3.25 using Python 3.5.2

Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):

bash

Your system (Debian 7, ArchLinux, Windows, etc.):

Ubuntu 16.04

How to reproduce the bug:

Try the fuck as a different user on the same machine, the file /tmp/thefuck.last_not_configured_run seems to be the culprit.

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

Traceback (most recent call last):
  File "/usr/local/bin/fuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/thefuck/entrypoints/not_configured.py", line 109, in main
    _record_first_run()
  File "/usr/local/lib/python3.5/dist-packages/thefuck/entrypoints/not_configured.py", line 39, in _record_first_run
    with _get_not_configured_usage_tracker_path().open(mode) as tracker:
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/tmp/thefuck.last_not_configured_run'

If the bug only appears with a specific application, the output of that application and its version:

nope, first try lucky. :) Works fine with the other user still.

Anything else you think is relevant:

So I installed it, and demoed it to my colleague, he gets the above error. The file mentioned there is indeed owned by my user and not writeable by him. A quick fix might be to add the username to the file name.

**Comment by SuperRun** [comment]
I met this problem too.
The Fuck 3.30
Python 3.8.0
