### ISSUE TITLE
Python 3.3 dropped, but still artifacts in setup.py

### ISSUE THREAD

**Issue by johnthagen** [nvbn/thefuck#789]
https://github.com/nvbn/thefuck/blob/master/setup.py#L37

```py
extras_require = {':python_version<"3.4"': ['pathlib2'],
```

Is this line still required?

**Comment by nvbn** [comment]
Python 2.7 needs pathlib2. It's already deprecated and when we will finally drop support of Python 2 we will remove this line.

**Comment by johnthagen** [comment]
Oh, duh, sorry I missed 2.7 support. I'll close this issue as I'm sure dropping Python 2 will involve much bigger cleanups.
