### ISSUE TITLE
AutoFuck, aka calling thefuck whenever a command is not found

### ISSUE THREAD

**Issue by JulesGM** [nvbn/thefuck#796]
First, I want to say I'm sorry if this isn't the place to post this. 

I was thinking that having bash call thefuck automatically whenever it doesn't find a command I tried to type could be cool and even maybe useful.

Also, AutoFuck kind of has a nice ring to it :P

I can't be the first to have thought about this though; but I couldn't find information about the idea on the README or elsewhere.

**Comment by fire17** [comment]
Hey yo , was wondering the same..
Have you managed to so this ?
Thanks a lot and all the best!
