### ISSUE TITLE
Powershell, The term 'thefuck' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by maracuja-juice** [nvbn/thefuck#809]
**The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):**

    The Fuck 3.26 using Python 3.6.5

**Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):**

    Windows Powershell, 5.1.16299.251

**Your system (Debian 7, ArchLinux, Windows, etc.):**

    Windows 10

**How to reproduce the bug:**

    - install thefuck
	`py -m pip install thefuck`
    - put the alias into your powershell profile
    ```
    $env:PYTHONIOENCODING="utf-8"
    iex "$(thefuck --alias)"
    ```
    - start a new powershell

Result:
```
thefuck : The term 'thefuck' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
```
    
**The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):**

Hmm I can't manage to output this.

**Anything else you think is relevant:**

I also tried it with the following in my profile:
```
...
iex "$(C:\Users\MyUserName\AppData\Local\Programs\Python\Python36-32\Scripts\thefuck.exe --alias)"
```
Then I get a similar error after executing `fuck`:
```
thefuck : The term 'thefuck' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:141
+ ... g]::IsNullOrWhiteSpace($history)) {         $fuck = $(thefuck $args $ ...
+                                                           ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (thefuck:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by MattKotsenas** [comment]
Hi @maracuja-juice!  From the error message you posted, it looks like `thefuck` is not on your path environment variable.

You can verify that the path is missing by running this command from PowerShell

```powershell
echo $ENV:Path
```

Based on your example, you should see the path `C:\Users\MyUserName\AppData\Local\Programs\Python\Python36-32\Scripts` listed (be sure it has semi-colon `;` separators).

You can also verify that `thefuck` is / isn't on your path by running this command from PowerShell

```powershell
Get-Command -Name thefuck
```

If you get an entry back from `Get-Command`, the tool is on your path, if you get a `CommandNotFoundException` error message, then you'll need to update your environment variables to add it. You can follow the direction on [this stackoverflow question](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10) to add `C:\Users\MyUserName\AppData\Local\Programs\Python\Python36-32\Scripts` to your path (be sure to close and re-open your PowerShell windows to pick up the changed path environment variable!)

**Comment by Gabgab2003** [comment]
The new normal alias is fuck so try that @maracuja-juice

**Comment by scorphus** [comment]
Thanks for confirming, @friendlyfreedom!

@maracuja-juice, please feel free to reopen if this still an issue for you.

**Comment by maracuja-juice** [comment]
Thanks. Will try this out as soon as I'm on a Windows PC again.

**Comment by michaelpalumbo** [comment]
```shell
Powershell, The term 'thefuck' is not recognized as the name of a cmdlet
```
I mean, I came across this in a somewhat unrelated google search and it made me laugh loudly at work. But I have to say, this utility is a nice idea :)

**Comment by grafst** [comment]
i had to reinstall thefuck from administrator prompt. 
Now it works.
