### ISSUE TITLE
How about i18n?

### ISSUE THREAD

**Issue by Dugucloud** [nvbn/thefuck#81]
I'm a Linux user and working with shell commands every day. My system's default language is Chinese, so the output messages of some commonly used tools (git, gcc, etc.) were translated into Chinese in the i18n mechanism of the software itself. So I think it is considerable to match i18n messages.

Do you have any ideas to implement this feature? It may be gossip to write strings of all languages in the match function. Can there be any more beautiful ways to make it?

**Comment by nvbn** [comment]
The Fuck works with commands output with `LANG=C`, so only match-strings in English are required.

**Comment by Dugucloud** [comment]
Thanks. I've got it. It works!
