### ISSUE TITLE
Distributing as a snap

### ISSUE THREAD

**Issue by mati865** [nvbn/thefuck#828]
I'd like to maintain `thefuck` packaged as a [snap](https://snapcraft.io/store) but wanted to reach to you before reserving `thefuck` name. Are you fine with it?

Build script [`snapcraft.yaml`](https://github.com/mati865/thefuck/blob/7f1fcf7cc3cc0af487a45e08a5f343f31e839b83/snap/snapcraft.yaml) would either in this repo (`./snapcraft.yaml` or `snap/snapcraft.yaml`) or in it's own depending on your preference.

**Comment by nvbn** [comment]
I don't know how snap works, but will it be updated automatically after each release or it requires some manual actions?

**Comment by mati865** [comment]
To give some context there are 4 release channels: `edge`, `beta`, `candidate`, `stable`. Differences are explained [here](https://docs.snapcraft.io/reference/channels#risk-level).

As far as I know you there are following strategies:
- use https://build.snapcraft.io to release new version for every commit to channel `egde` and handle other channels manually (you can add collaborators via dashboard) or [via CI/launchpad](https://docs.snapcraft.io/reference/channels#risk-level)
- use [CI/launchpad](https://docs.snapcraft.io/reference/channels#risk-level) to handle `edge`, rest just like above
- release new versions via CI for tagged commit or do it by hand

**Comment by nvbn** [comment]
@mati865 sounds good!

I guess it will be the best to place `snapcraft.yaml` in the root of the repo, there're already a few yaml configs.

**Comment by jraspiprojects** [comment]
not sure if they'll allow the name.....
