### ISSUE TITLE
Fresh brew install, [ --yeah ] not available

### ISSUE THREAD

**Issue by ChaseFlorell** [nvbn/thefuck#831]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):

> The Fuck 3.27 using Python 3.7.0

Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):

> ➜  ~ echo $ZSH_VERSION 
> 5.3

Your system (Debian 7, ArchLinux, Windows, etc.):

macOC High Sierra 10.13.6

How to reproduce the bug:

> fuck --yeah
> thefuck: error: unrecognized arguments: --yeah

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

> fuck --yeah
> thefuck: error: unrecognized arguments: --yeah

If the bug only appears with a specific application, the output of that application and its version:

> N/A

Anything else you think is relevant:

So the documentation says the following
> To run fixed commands without confirmation, use the --yeah option (or just -y for short):

But when I run the help command it actually says that we're to use `-y, --yes`. I really think `--yeah` is super awesome, and am wondering why it's been removed?

**Comment by Dean-Coakley** [comment]
https://github.com/nvbn/thefuck/blob/master/thefuck/argument_parser.py#L58 :confused:

**Comment by scorphus** [comment]
Not yet, 3.28 will include it. Unfortunatelly (and confusing) README.md contents don't follow what's released.
