### ISSUE TITLE
"sudo apt-get update && apt-get upgrade ; fuck" makes an error

### ISSUE THREAD

**Issue by Thibaut-Fontaine** [nvbn/thefuck#837]
I updated thefuck and checked other issues.
Running on GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu) and ubuntu 18.04.1 LTS updated.

Run this : 

> sudo apt-get update && apt-get upgrade ; fuck

it will make : 

> Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:2 https://dl.yarnpkg.com/debian stable InRelease                                                                                                                                                
> Hit:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease                                                                                                                            
> Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                         
> Hit:5 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease                                                   
> Hit:6 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease       
> Hit:7 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease
> Reading package lists... Done                      
> E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
> E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
> Traceback (most recent call last):
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/rerun.py", line 22, in _wait_output
>     else settings.wait_command)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py", line 1262, in wait
>     return self._proc.wait(timeout)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/_pslinux.py", line 1459, in wrapper
>     return fun(self, *args, **kwargs)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/_pslinux.py", line 1637, in wait
>     return _psposix.wait_pid(self.pid, timeout, self._name)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/_psposix.py", line 104, in wait_pid
>     delay = check_timeout(delay)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/_psposix.py", line 66, in check_timeout
>     raise TimeoutExpired(timeout, pid=pid, name=proc_name)
> psutil._exceptions.TimeoutExpired: psutil.TimeoutExpired timeout after 3 seconds (pid=20029)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py", line 1170, in _send_signal
>     os.kill(self.pid, sig)
> PermissionError: [Errno 1] Operation not permitted
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/thefuck", line 11, in <module>
>     sys.exit(main())
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/entrypoints/main.py", line 25, in main
>     fix_command(known_args)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/entrypoints/fix_command.py", line 36, in fix_command
>     command = types.Command.from_raw_script(raw_command)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/types.py", line 82, in from_raw_script
>     output = get_output(script, expanded)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/__init__.py", line 20, in get_output
>     return rerun.get_output(script, expanded)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/rerun.py", line 47, in get_output
>     if _wait_output(result, is_slow):
>   File "/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/rerun.py", line 26, in _wait_output
>     child.kill()
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py", line 285, in wrapper
>     return fun(self, *args, **kwargs)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py", line 1244, in kill
>     self._send_signal(signal.SIGKILL)
>   File "/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py", line 1181, in _send_signal
>     raise AccessDenied(self.pid, self._name)
> psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=20030)

This seems weird to me, anyway this is an error.

**Comment by CottonEaster** [comment]
I just experienced this exact same problem, on Mint 19 Cinnamon.

`The Fuck 3.27 using Python 3.6.5`

**Comment by scorphus** [comment]
Thanks for reporting! This is kinda expected behavior, for the previous command takes longer than 3s to finish and times out. Only that `AccessDenied` exception needs to be excepted. Fix is on its way.

BTW, TheFuck is meant to fix the *previous* failed command, not the current one:
```
$ echoo ok; fuck
-su: echoo: command not found
No fucks given
$ echoo ok
-su: echoo: command not found
$ fuck
echo ok [enter/↑/↓/ctrl+c]
ok
```

**Comment by scorphus** [comment]
Oh. This is already fixed and should have been closed by one of those merged commits.
