### ISSUE TITLE
Can't use fuck to install TheFuck

### ISSUE THREAD

**Issue by Ben-Epstein** [nvbn/thefuck#840]
<img width="568" alt="screen shot 2018-09-25 at 7 34 48 pm" src="https://user-images.githubusercontent.com/22605641/46050539-5bd76580-c0fa-11e8-89e5-b7565655dd2a.png">

**Comment by manikantanallagatla** [comment]
@scorphus , I am getting the expected output with Fuck 3.29.
![image](https://user-images.githubusercontent.com/6606201/46312530-f47e5180-c5e2-11e8-85a5-01c80a2a5e64.png)

**Comment by sragha45** [comment]
Lol this must be a joke

You can correct with thefuck only after you install thefuck properly
