### ISSUE TITLE
ImportError: No module named shutil_get_terminal_size

### ISSUE THREAD

**Issue by nicolargo** [nvbn/thefuck#850]
Just install thefuck on my Ubuntu 18.04 laptop.

I use:

```
$ pip install thefuck
```

After adding the alias in the .bashrc file, the following error appears wheni try to run the fuck command:

```
$ thefuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/local/lib/python2.7/dist-packages/thefuck/entrypoints/main.py", line 12, in <module>
    from .fix_command import fix_command  # noqa: E402
  File "/usr/local/lib/python2.7/dist-packages/thefuck/entrypoints/fix_command.py", line 5, in <module>
    from .. import logs, types, const
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 10, in <module>
    from .output_readers import get_output
  File "/usr/local/lib/python2.7/dist-packages/thefuck/output_readers/__init__.py", line 2, in <module>
    from . import read_log, rerun, shell_logger
  File "/usr/local/lib/python2.7/dist-packages/thefuck/output_readers/read_log.py", line 8, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size
```

I already try to upgrade backports.shutil_get_terminal_size (pip install --upgrade backports.shutil_get_terminal_size) but same issue...

Any idea ?

**Comment by TheHackmeister** [comment]
Just thought I'd mention that I've had the same problem in Fedora 28. 

$ thefuck
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 7, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/lib/python2.7/site-packages/thefuck/entrypoints/main.py", line 12, in <module>
    from .fix_command import fix_command  # noqa: E402
  File "/usr/lib/python2.7/site-packages/thefuck/entrypoints/fix_command.py", line 5, in <module>
    from .. import logs, types, const
  File "/usr/lib/python2.7/site-packages/thefuck/types.py", line 10, in <module>
    from .output_readers import get_output
  File "/usr/lib/python2.7/site-packages/thefuck/output_readers/__init__.py", line 2, in <module>
    from . import read_log, rerun, shell_logger
  File "/usr/lib/python2.7/site-packages/thefuck/output_readers/read_log.py", line 8, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size

**Comment by Aquakor** [comment]
I think you got ImportError because you try to use Python 2.7 which is not supported. Try to use Python 3.4+.

**Comment by steaksauce-** [comment]
> @nicolargo @TheHackmeister I think you got ImportError because you try to use Python 2.7 which is not supported. Try to use Python 3.4+.

I can confirm that on Ubuntu 18.04, I had to install `python3` and `pip3` and use `pip3` to install `thefuck`.
To install `pip3` on Ubuntu 18.04: `sudo apt-get -y install python3-pip` and then `pip3 install thefuck`

**Comment by TheHackmeister** [comment]
I had to reinstall pip3 for some reason, but once I did that and installed python3-devel, I was good to go. Thanks for your help @Aquakor!

**Comment by scorphus** [comment]
This issue cannot be reproduced. Check the output from a fresh install:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
```
$ python --version
Python 2.7.15+
```
```
$ thefuck --version
The Fuck 3.29 using Python 2.7.15+ and Bash 4.4.19(1)-release
```
```
$ apt list --installed | grep python | cut -d/ -f1
libpython-all-dev
libpython-dev
libpython-stdlib
libpython2.7
libpython2.7-dev
libpython2.7-minimal
libpython2.7-stdlib
python
python-all
python-all-dev
python-asn1crypto
python-cffi-backend
python-crypto
python-cryptography
python-dbus
python-dev
python-enum34
python-gi
python-idna
python-ipaddress
python-keyring
python-keyrings.alt
python-minimal
python-pip
python-pip-whl
python-pkg-resources
python-secretstorage
python-setuptools
python-six
python-wheel
python-xdg
python2.7
python2.7-dev
python2.7-minimal
```

Here's a Dockerfile that can get you TheFuck working with Ubuntu 18.04:

```Dockerfile
FROM ubuntu:18.04

# Install dependencies
RUN apt update; apt install -y python python-pip python-dev

# Set the locale
ENV LANG=C.UTF-8

# Install TheFuck
RUN pip install thefuck

# Test TheFuck installation
RUN thefuck --version
```
