### ISSUE TITLE
up/down arrow keys not working

### ISSUE THREAD

**Issue by joelnet** [nvbn/thefuck#857]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.27 using Python 3.7.1

Your system (Debian 7, ArchLinux, Windows, etc.):

    Mac (High Sierra 10.13.6)

How to reproduce the bug:

    $ cat ~/.ssh
    cat: /Users/joelnet/.ssh: Is a directory
    $ fuck

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    DEBUG: Run with settings: {'alter_history': True,
    'debug': True,
    'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
    'exclude_rules': [],
    'history_limit': None,
    'instant_mode': False,
    'no_colors': False,
    'priority': {},
    'repeat': False,
    'require_confirmation': True,
    'rules': [<const: All rules enabled>],
    'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
    'user_dir': PosixPath('/Users/joelnet/.config/thefuck'),
    'wait_command': 3,
    'wait_slow_command': 15}
    DEBUG: Received output: cat: /Users/joelnet/.ssh: Is a directory

    DEBUG: Call: cat ~/.ssh; with env: {'THEFUCK_DEBUG': 'true', 'TERM_PROGRAM': 'Apple_Terminal', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'TMPDIR': '/var/folders/v9/nd6fgp_n22zctpmzfbtrzfp1d6nmss/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.WhprNH36gp/Render', 'TERM_PROGRAM_VERSION': '404', 'TF_SHELL': 'bash', 'TERM_SESSION_ID': 'D2A7A0D5-5688-41F1-9BAC-C09BC7078B50', 'TF_HISTORY': '\t fuck\n\t cat ~/dev\n\t fuck\n\t python --version\n\t python3 --version\n\t fuck --versin\n\t fuck -v\n\t fuck --version\n\t uname -a\n\t cat ~/.ssh', 'TF_ALIAS': 'fuck', 'TF_SHELL_ALIASES': "alias ll='exa -al'", 'PYTHONIOENCODING': 'utf-8', 'USER': 'joelnet', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.Q7gj2VSnYW/Listeners', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/apache-maven-3.5.3/bin', 'PWD': '/Users/joelnet', 'BAT_STYLE': 'changes', 'LANG': 'C', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'M2_HOME': '/Applications/apache-maven-3.5.3', 'SHLVL': '1', 'HOME': '/Users/joelnet', 'LOGNAME': 'joelnet', '_': '/usr/local/bin/thefuck', '__CF_USER_TEXT_ENCODING': '0x5A6AD339:0x0:0x0', 'LC_ALL': 'C', 'GIT_TRACE': '1'}; is slow:  took: 0:00:00.019532
    DEBUG: Importing rule: adb_unknown_command; took: 0:00:00.000779
    DEBUG: Importing rule: ag_literal; took: 0:00:00.000823
    DEBUG: Importing rule: apt_get; took: 0:00:00.001792
    DEBUG: Importing rule: apt_get_search; took: 0:00:00.000623
    DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.001481
    DEBUG: Importing rule: apt_list_upgradable; took: 0:00:00.000696
    DEBUG: Importing rule: apt_upgrade; took: 0:00:00.000701
    DEBUG: Importing rule: aws_cli; took: 0:00:00.001363
    DEBUG: Importing rule: brew_cask_dependency; took: 0:00:00.001459
    DEBUG: Importing rule: brew_install; took: 0:00:00.000427
    DEBUG: Importing rule: brew_link; took: 0:00:00.000602
    DEBUG: Importing rule: brew_reinstall; took: 0:00:00.000924
    DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000558
    DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000430
    DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000533
    DEBUG: Importing rule: cargo; took: 0:00:00.000287
    DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000523
    DEBUG: Importing rule: cd_correction; took: 0:00:00.002078
    DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000464
    DEBUG: Importing rule: cd_parent; took: 0:00:00.000324
    DEBUG: Importing rule: chmod_x; took: 0:00:00.000333
    DEBUG: Importing rule: composer_not_command; took: 0:00:00.000569
    DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000782
    DEBUG: Importing rule: cpp11; took: 0:00:00.000636
    DEBUG: Importing rule: dirty_untar; took: 0:00:00.002258
    DEBUG: Importing rule: dirty_unzip; took: 0:00:00.003507
    DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000360
    DEBUG: Importing rule: django_south_merge; took: 0:00:00.000342
    DEBUG: Importing rule: dnf_no_such_command; took: 0:00:00.001444
    DEBUG: Importing rule: docker_not_command; took: 0:00:00.000809
    DEBUG: Importing rule: dry; took: 0:00:00.000283
    DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000732
    DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000587
    DEBUG: Importing rule: fix_file; took: 0:00:00.002896
    DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.000861
    DEBUG: Importing rule: git_add; took: 0:00:00.001342
    DEBUG: Importing rule: git_add_force; took: 0:00:00.000549
    DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000538
    DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000564
    DEBUG: Importing rule: git_branch_exists; took: 0:00:00.000810
    DEBUG: Importing rule: git_branch_list; took: 0:00:00.000606
    DEBUG: Importing rule: git_checkout; took: 0:00:00.000632
    DEBUG: Importing rule: git_commit_amend; took: 0:00:00.000600
    DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000538
    DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000479
    DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000531
    DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000526
    DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000535
    DEBUG: Importing rule: git_merge; took: 0:00:00.000519
    DEBUG: Importing rule: git_merge_unrelated; took: 0:00:00.000697
    DEBUG: Importing rule: git_not_command; took: 0:00:00.000539
    DEBUG: Importing rule: git_pull; took: 0:00:00.000486
    DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000521
    DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000530
    DEBUG: Importing rule: git_push; took: 0:00:00.000533
    DEBUG: Importing rule: git_push_different_branch_names; took: 0:00:00.000527
    DEBUG: Importing rule: git_push_force; took: 0:00:00.000555
    DEBUG: Importing rule: git_push_pull; took: 0:00:00.000652
    DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000658
    DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000489
    DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000414
    DEBUG: Importing rule: git_remote_delete; took: 0:00:00.000517
    DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000466
    DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000551
    DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000672
    DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000580
    DEBUG: Importing rule: git_stash; took: 0:00:00.000485
    DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000551
    DEBUG: Importing rule: git_tag_force; took: 0:00:00.000561
    DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000531
    DEBUG: Importing rule: go_run; took: 0:00:00.000539
    DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000886
    DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000533
    DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000551
    DEBUG: Importing rule: grep_recursive; took: 0:00:00.000470
    DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000766
    DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000555
    DEBUG: Importing rule: has_exists_script; took: 0:00:00.000589
    DEBUG: Importing rule: heroku_multiple_apps; took: 0:00:00.000580
    DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000741
    DEBUG: Importing rule: history; took: 0:00:00.000346
    DEBUG: Importing rule: hostscli; took: 0:00:00.000652
    DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000614
    DEBUG: Importing rule: java; took: 0:00:00.000570
    DEBUG: Importing rule: javac; took: 0:00:00.000563
    DEBUG: Importing rule: lein_not_task; took: 0:00:00.000749
    DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000535
    DEBUG: Importing rule: ln_s_order; took: 0:00:00.000596
    DEBUG: Importing rule: long_form_help; took: 0:00:00.000336
    DEBUG: Importing rule: ls_all; took: 0:00:00.000491
    DEBUG: Importing rule: ls_lah; took: 0:00:00.000585
    DEBUG: Importing rule: man; took: 0:00:00.000557
    DEBUG: Importing rule: man_no_space; took: 0:00:00.000349
    DEBUG: Importing rule: mercurial; took: 0:00:00.000659
    DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000490
    DEBUG: Importing rule: mkdir_p; took: 0:00:00.000514
    DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000516
    DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000546
    DEBUG: Importing rule: no_command; took: 0:00:00.000668
    DEBUG: Importing rule: no_such_file; took: 0:00:00.000391
    DEBUG: Importing rule: npm_missing_script; took: 0:00:00.001152
    DEBUG: Importing rule: npm_run_script; took: 0:00:00.000525
    DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000837
    DEBUG: Importing rule: open; took: 0:00:00.000643
    DEBUG: Importing rule: pacman; took: 0:00:00.000964
    DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000342
    DEBUG: Importing rule: path_from_history; took: 0:00:00.000387
    DEBUG: Importing rule: php_s; took: 0:00:00.000688
    DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000704
    DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000405
    DEBUG: Importing rule: prove_recursively; took: 0:00:00.000522
    DEBUG: Importing rule: python_command; took: 0:00:00.000608
    DEBUG: Importing rule: python_execute; took: 0:00:00.000571
    DEBUG: Importing rule: quotation_marks; took: 0:00:00.000325
    DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.000630
    DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000350
    DEBUG: Importing rule: rm_dir; took: 0:00:00.000545
    DEBUG: Importing rule: rm_root; took: 0:00:00.000525
    DEBUG: Importing rule: scm_correction; took: 0:00:00.000556
    DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000550
    DEBUG: Importing rule: sl_ls; took: 0:00:00.000337
    DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000546
    DEBUG: Importing rule: sudo; took: 0:00:00.000435
    DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000581
    DEBUG: Importing rule: switch_lang; took: 0:00:00.000318
    DEBUG: Importing rule: systemctl; took: 0:00:00.000678
    DEBUG: Importing rule: test.py; took: 0:00:00.000329
    DEBUG: Importing rule: tmux; took: 0:00:00.000543
    DEBUG: Importing rule: touch; took: 0:00:00.000602
    DEBUG: Importing rule: tsuru_login; took: 0:00:00.000533
    DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000537
    DEBUG: Importing rule: unknown_command; took: 0:00:00.000339
    DEBUG: Importing rule: unsudo; took: 0:00:00.000292
    DEBUG: Importing rule: vagrant_up; took: 0:00:00.000519
    DEBUG: Importing rule: whois; took: 0:00:00.000717
    DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000620
    DEBUG: Importing rule: yarn_alias; took: 0:00:00.000499
    DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000906
    DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000624
    DEBUG: Importing rule: yarn_help; took: 0:00:00.000497
    DEBUG: Trying rule: path_from_history; took: 0:00:00.000619
    DEBUG: Trying rule: dry; took: 0:00:00.000077
    DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000033
    DEBUG: Trying rule: test.py; took: 0:00:00.000004
    DEBUG: Trying rule: adb_unknown_command; took: 0:00:00.000018
    DEBUG: Trying rule: ag_literal; took: 0:00:00.000015
    DEBUG: Trying rule: aws_cli; took: 0:00:00.000014
    DEBUG: Trying rule: brew_cask_dependency; took: 0:00:00.000013
    DEBUG: Trying rule: brew_install; took: 0:00:00.000003
    DEBUG: Trying rule: brew_link; took: 0:00:00.000014
    DEBUG: Trying rule: brew_reinstall; took: 0:00:00.000012
    DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000012
    DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000003
    DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000012
    DEBUG: Trying rule: cargo; took: 0:00:00.000002
    DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000014
    DEBUG: Trying rule: cd_correction; took: 0:00:00.000015
    DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000012
    DEBUG: Trying rule: cd_parent; took: 0:00:00.000002
    DEBUG: Trying rule: chmod_x; took: 0:00:00.000003
    DEBUG: Trying rule: composer_not_command; took: 0:00:00.000013
    DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000013
    DEBUG: Trying rule: cpp11; took: 0:00:00.000014
    DEBUG: Trying rule: dirty_untar; took: 0:00:00.000013
    DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000013
    DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000003
    DEBUG: Trying rule: django_south_merge; took: 0:00:00.000002
    DEBUG: Trying rule: docker_not_command; took: 0:00:00.000014
    DEBUG: Trying rule: fab_command_not_found; took: 0:00:00.000017
    DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000005
    DEBUG: Trying rule: fix_file; took: 0:00:00.000011
    DEBUG: Trying rule: gem_unknown_command; took: 0:00:00.000013
    DEBUG: Trying rule: git_add; took: 0:00:00.000012
    DEBUG: Trying rule: git_add_force; took: 0:00:00.000011
    DEBUG: Trying rule: git_bisect_usage; took: 0:00:00.000010
    DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000010
    DEBUG: Trying rule: git_branch_exists; took: 0:00:00.000010
    DEBUG: Trying rule: git_branch_list; took: 0:00:00.000010
    DEBUG: Trying rule: git_checkout; took: 0:00:00.000010
    DEBUG: Trying rule: git_commit_amend; took: 0:00:00.000044
    DEBUG: Trying rule: git_diff_no_index; took: 0:00:00.000019
    DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000013
    DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000011
    DEBUG: Trying rule: git_flag_after_filename; took: 0:00:00.000011
    DEBUG: Trying rule: git_help_aliased; took: 0:00:00.000011
    DEBUG: Trying rule: git_merge; took: 0:00:00.000010
    DEBUG: Trying rule: git_merge_unrelated; took: 0:00:00.000012
    DEBUG: Trying rule: git_not_command; took: 0:00:00.000010
    DEBUG: Trying rule: git_pull; took: 0:00:00.000010
    DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000010
    DEBUG: Trying rule: git_pull_uncommitted_changes; took: 0:00:00.000011
    DEBUG: Trying rule: git_push; took: 0:00:00.000010
    DEBUG: Trying rule: git_push_different_branch_names; took: 0:00:00.000011
    DEBUG: Trying rule: git_push_pull; took: 0:00:00.000010
    DEBUG: Trying rule: git_push_without_commits; took: 0:00:00.000010
    DEBUG: Trying rule: git_rebase_merge_dir; took: 0:00:00.000011
    DEBUG: Trying rule: git_rebase_no_changes; took: 0:00:00.000011
    DEBUG: Trying rule: git_remote_delete; took: 0:00:00.000011
    DEBUG: Trying rule: git_remote_seturl_add; took: 0:00:00.000010
    DEBUG: Trying rule: git_rm_local_modifications; took: 0:00:00.000010
    DEBUG: Trying rule: git_rm_recursive; took: 0:00:00.000010
    DEBUG: Trying rule: git_rm_staged; took: 0:00:00.000009
    DEBUG: Trying rule: git_stash; took: 0:00:00.000010
    DEBUG: Trying rule: git_tag_force; took: 0:00:00.000010
    DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000010
    DEBUG: Trying rule: go_run; took: 0:00:00.000015
    DEBUG: Trying rule: gradle_no_task; took: 0:00:00.000014
    DEBUG: Trying rule: gradle_wrapper; took: 0:00:00.000012
    DEBUG: Trying rule: grep_arguments_order; took: 0:00:00.000020
    DEBUG: Trying rule: grep_recursive; took: 0:00:00.000027
    DEBUG: Trying rule: grunt_task_not_found; took: 0:00:00.000015
    DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000013
    DEBUG: Trying rule: has_exists_script; took: 0:00:00.000020
    DEBUG: Trying rule: heroku_multiple_apps; took: 0:00:00.000013
    DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000011
    DEBUG: Trying rule: hostscli; took: 0:00:00.000014
    DEBUG: Trying rule: ifconfig_device_not_found; took: 0:00:00.000013
    DEBUG: Trying rule: java; took: 0:00:00.000013
    DEBUG: Trying rule: javac; took: 0:00:00.000013
    DEBUG: Trying rule: lein_not_task; took: 0:00:00.000013
    DEBUG: Trying rule: ln_no_hard_link; took: 0:00:00.000004
    DEBUG: Trying rule: ln_s_order; took: 0:00:00.000005
    DEBUG: Trying rule: ls_all; took: 0:00:00.000012
    DEBUG: Trying rule: ls_lah; took: 0:00:00.000011
    DEBUG: Trying rule: man; took: 0:00:00.000013
    DEBUG: Trying rule: mercurial; took: 0:00:00.000012
    DEBUG: Trying rule: mkdir_p; took: 0:00:00.000003
    DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000019
    DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000013
    DEBUG: Trying rule: no_such_file; took: 0:00:00.000745
    DEBUG: Trying rule: npm_missing_script; took: 0:00:00.000020
    DEBUG: Trying rule: npm_run_script; took: 0:00:00.000014
    DEBUG: Trying rule: npm_wrong_command; took: 0:00:00.000013
    DEBUG: Trying rule: open; took: 0:00:00.000015
    DEBUG: Trying rule: php_s; took: 0:00:00.000013
    DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000014
    DEBUG: Trying rule: port_already_in_use; took: 0:00:00.000543
    DEBUG: Trying rule: prove_recursively; took: 0:00:00.000019
    DEBUG: Trying rule: python_command; took: 0:00:00.000005
    DEBUG: Trying rule: python_execute; took: 0:00:00.000015
    DEBUG: Trying rule: quotation_marks; took: 0:00:00.000003
    DEBUG: Trying rule: react_native_command_unrecognized; took: 0:00:00.000013
    DEBUG: Trying rule: remove_trailing_cedilla; took: 0:00:00.000003
    DEBUG: Trying rule: rm_dir; took: 0:00:00.000003
    DEBUG: Trying rule: scm_correction; took: 0:00:00.000014
    DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000013
    DEBUG: Trying rule: sl_ls; took: 0:00:00.000003
    DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000014
    DEBUG: Trying rule: sudo; took: 0:00:00.000010
    DEBUG: Trying rule: sudo_command_from_user_path; took: 0:00:00.000014
    DEBUG: Trying rule: switch_lang; took: 0:00:00.000002
    DEBUG: Trying rule: systemctl; took: 0:00:00.000014
    DEBUG: Trying rule: tmux; took: 0:00:00.000018
    DEBUG: Trying rule: touch; took: 0:00:00.000012
    DEBUG: Trying rule: tsuru_login; took: 0:00:00.000012
    DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000011
    DEBUG: Trying rule: unknown_command; took: 0:00:00.000129
    DEBUG: Trying rule: unsudo; took: 0:00:00.000004
    DEBUG: Trying rule: vagrant_up; took: 0:00:00.000016
    DEBUG: Trying rule: whois; took: 0:00:00.000015
    DEBUG: Trying rule: workon_doesnt_exists; took: 0:00:00.000013
    DEBUG: Trying rule: yarn_alias; took: 0:00:00.000012
    DEBUG: Trying rule: yarn_command_not_found; took: 0:00:00.000012
    DEBUG: Trying rule: yarn_command_replaced; took: 0:00:00.000011
    DEBUG: Trying rule: yarn_help; took: 0:00:00.000013
    DEBUG: Trying rule: man_no_space; took: 0:00:00.000003
    DEBUG: Trying rule: no_command; took: 0:00:00.000124
    DEBUG: Trying rule: missing_space_before_subcommand; took: 0:00:00.000026
    DEBUG: Trying rule: long_form_help; took: 0:00:00.000299
    DEBUG: Trying rule: history; took: 0:00:00.004177
    cat ~/.bash_profile [enter/↑/↓/ctrl+c]DEBUG: Corrected commands: 

Anything else you think is relevant:

    Pressing the up and down arrow keys have no effect. I can only press enter or ctrl-c.
    I expected to receive the option to `ls ~/.ssh` but I was only prompted with `cd ~/.ssh`.

**Comment by nvbn** [comment]
It seems like it's not related to arrow keys, we just don't have a rule for correcting `cat` to `ls`.

Can you try with another command to be sure? Something like `git br`.

**Comment by joelnet** [comment]
You are correct. `git br` works just fine with arrow keys.

I did see this in the `README.md` so that was the first thing I tested:

    cat_dir – replaces cat with ls when you try to cat a directory;

I don't see `cat_dir` in the `DEBUG`, but the `README` states it is enabled by default.

**Comment by nvbn** [comment]
Haven't released thefuck for a while and the rule wasn't included in the previous release, should work with 3.28:
```
➜  ~ cat go
cat: go: Is a directory
➜  ~ fuck
ls go [enter/↑/↓/ctrl+c]
bin  pkg  src
```

**Comment by joelnet** [comment]
Most excellent! I patiently await.
