### ISSUE TITLE
Potential missing dependency: 

### ISSUE THREAD

**Issue by redyoshi49q** [nvbn/thefuck#858]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    3.11 using Python 2.7.15rc1

Your system (Debian 7, ArchLinux, Windows, etc.):

    Linux Mint 19 Tara

How to reproduce the bug:

    Install Thefuck on a clean Linux Mint install using apt-get, then insert `eval $(thefuck --alias --enable-experimental-instant-mode)` into the `.bashrc` and spawn a bash shell (using `eval $(thefuck --alias)` would presumably also reproduce this).

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    (n/a)

If the bug only appears with a specific application, the output of that application and its version:

    (n/a)

Anything else you think is relevant:

Installing thefuck on my system and adding `eval $(thefuck --alias oops --enable-experimental-instant-mode)` to the .bashrc resulted in the following output when new bash shells were spawned:

    Traceback (most recent call last):
      File "/usr/bin/thefuck", line 6, in <module>
        from pkg_resources import load_entry_point
    ImportError: No module named pkg_resources

Installing the package `python-setuptools` via apt-get allowed the .bashrc to load without errors (and for thefuck to function as expected when called by the specified `oops` alias).  The setuptools python package appears to be missing as a dependency (for at least the case of installation by apt-get, but possibly for installation by pip as well).

**Comment by scorphus** [comment]
This and other requirements are covered in “[Installation](https://github.com/nvbn/thefuck#installation)”.

**Comment by KaKi87** [comment]
Hello, shouldn't dependencies be automatically handled when installing using APT ? Thanks.

**Comment by scorphus** [comment]
If any dependency is missing, please report a bug on the package of your distro of choice. Ubuntu, for instance, has got some bugs reported, with one in particular regarding dependencies: https://launchpad.net/ubuntu/+source/thefuck/+bugs
