### ISSUE TITLE
How it works on windows?

### ISSUE THREAD

**Issue by Sunyelw** [nvbn/thefuck#867]
I have install python and pip.
![image](https://user-images.githubusercontent.com/31758533/50418248-5b6b7980-0865-11e9-8d0a-97d3a325068b.png)
![image](https://user-images.githubusercontent.com/31758533/50418254-61f9f100-0865-11e9-9b5b-b739e538d3d2.png)

and install thefuck by `pip install thefuck`

![image](https://user-images.githubusercontent.com/31758533/50418240-4abb0380-0865-11e9-8f2d-038e95403976.png)

but, it doesn't work....
![image](https://user-images.githubusercontent.com/31758533/50418268-7dfd9280-0865-11e9-9969-437782f0a785.png)

I have tried many solutions from network and none is useful.

**Comment by scorphus** [comment]
Have you kindly followed the [installation instructions](https://github.com/nvbn/thefuck#manual-installation)?

Please, feel free to reopen this issue if that still doesn't work for you.

**Comment by eromoe** [comment]
Seems like fuck alias isn't configured!
More details - https://github.com/nvbn/thefuck#manual-installation , how could I use it in windows cmd?

**Comment by PhoenixDiscord** [comment]
Same problem here.

**Comment by JAspeling** [comment]
Yeah also lost on the mapping the alias on windows. The instructions are releated to the .bashrc file which isnt applicable to windows (as far as I know). I've already tried to map it using a `fuck.bat` file with the following contents:

```
@echo off
echo.
thefuck %*
```

and that alias is in a folder which is in my PATH directory. Still getting the same issue though

**Comment by youtiao66** [comment]
Same problem here in windows cmd

**Comment by NoamLeshem** [comment]
Same problem here in windows cmd
