### ISSUE TITLE
feature request: common git branch typos

### ISSUE THREAD

**Issue by jonathanong** [nvbn/thefuck#87]
```
Jonathans-MacBook-Pro:studio jong$ git checkout amster
error: pathspec 'amster' did not match any file(s) known to git.
Jonathans-MacBook-Pro:studio jong$ fuck
No fuck given
```

**Comment by mattjmcnaughton** [comment]
I can take a look at implementing this if there's interest.

**Comment by installgen2** [comment]
I'm interested!

**Comment by paramsingh** [comment]
What common typos do you think should be fixed?

* `amster`
* `masetr`

**Comment by nwinkler** [comment]
I suggest to take a similar approach to the `no_command` rule (https://github.com/nvbn/thefuck/blob/master/thefuck%2Frules%2Fno_command.py#L24):

* Get the list of available branches (from `git branch -a`)
* Use a function like `get_close_matches` (see code example above) to find the one that's closest to what the user typed.

**Comment by nvbn** [comment]
In 2.1+ `git_checkout` rule tries to use branch with similar name before creating new.
