### ISSUE TITLE
[thefork] were 1,975 forks necessary?

### ISSUE THREAD

**Issue by rhaleblian** [nvbn/thefuck#876]
(no system information or repro case)

Is there a program that corrects which fork you're using if you pick an incorrect one?

**Comment by steaksauce-** [comment]
Assuming that you mean you installed the package from an unofficial source that uses a forked version, it would be nice to have `thefuck` correct your installation by uninstalling the unofficial version and installing the official version. This would have to assume that the fork keeps the feature.

**Comment by rhaleblian** [comment]
Thank for considering the question.
This feature could be a provided as a separate subsystem called `thefork`. If it could be extended to handle all other GitHub projects, wouldn't that be great?

**Comment by rhaleblian** [comment]
Closing, the requestor is being too silly.
`thefuck` is a great idea BTW.

**Comment by rhaleblian** [comment]
Hey, the fork count went down to 1,974!
