### ISSUE TITLE
Use yay or another AUR manager instead of yaourt

### ISSUE THREAD

**Issue by person4268** [nvbn/thefuck#901]
In Arch Linux, `yaout` is now unmaintained, and has some security issues. It would be recommended to use `yay` or some other AUR package manager.

**Comment by alecastle** [comment]
For `yaourt` alternatives, I recommend `pikaur`. From what I can tell it has the same command structure as `pacman`, e.g. `-S` for install and `-R` for remove.

**Comment by ZerataX** [comment]
seems like this can be closed since it's now part of the official repos?

**Comment by scorphus** [comment]
Fixed in 201c01fc74d479d9e418d32c92a88b50b27728a7
