### ISSUE TITLE
Fuck windows

### ISSUE THREAD

**Issue by alastair-todd** [nvbn/thefuck#926]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

  The Fuck 3.29 using Python 3.6.1 and Generic Shell

Your system (Debian 7, ArchLinux, Windows, etc.):

    Windows

How to reproduce the bug:

**Jesus Christ the absolute fucking irony**

> 
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin feature/auth-z
> 
> 
> C:\_dev\seemis-workspace>thefuck
> usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
>                [--enable-experimental-instant-mode] [-h] [-y | -r] [-d]
>                [command [command ...]]
> 
> C:\_dev\seemis-workspace>fuck
> Seems like fuck alias isn't configured!
> More details - https://github.com/nvbn/thefuck#manual-installation
> 

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    not in windows

**Comment by primeroz** [comment]
Best Project ever !

**Comment by alastair-todd** [comment]
Powershell only....
