### ISSUE TITLE
When correcting `git branch list`, `thefuck` deletes the `list` branch then unexpectedly recreates it

### ISSUE THREAD

**Issue by dwurf** [nvbn/thefuck#930]
The output of `thefuck --version`

    The Fuck 3.29 using Python 3.5.2 and Bash 4.4.19(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

    Ubuntu 18.04

How to reproduce the bug:

    git init /tmp/foo
    cd /tmp/foo
    touch empty_file
    git add empty_file
    git commit -am "Empty file for testing"
    git branch list
    fuck # deletes the branch called 'list', then recreates it
    git branch # the branch called 'list' should be gone, but it is still present

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    DEBUG: Importing rule: adb_unknown_command; took: 0:00:00.000686
    DEBUG: Importing rule: ag_literal; took: 0:00:00.000742
    DEBUG: Importing rule: apt_get; took: 0:00:00.001541
    DEBUG: Importing rule: apt_get_search; took: 0:00:00.000551
    DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.001296
    DEBUG: Importing rule: apt_list_upgradable; took: 0:00:00.000540
    DEBUG: Importing rule: apt_upgrade; took: 0:00:00.000569
    DEBUG: Importing rule: aws_cli; took: 0:00:00.000616
    DEBUG: Importing rule: az_cli; took: 0:00:00.000464
    DEBUG: Importing rule: brew_cask_dependency; took: 0:00:00.000921
    DEBUG: Importing rule: brew_install; took: 0:00:00.000352
    DEBUG: Importing rule: brew_link; took: 0:00:00.000388
    DEBUG: Importing rule: brew_reinstall; took: 0:00:00.000646
    DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000385
    DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000599
    DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000368
    DEBUG: Importing rule: cargo; took: 0:00:00.000164
    DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000383
    DEBUG: Importing rule: cat_dir; took: 0:00:00.000370
    DEBUG: Importing rule: cd_correction; took: 0:00:00.001533
    DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000551
    DEBUG: Importing rule: cd_parent; took: 0:00:00.000177
    DEBUG: Importing rule: chmod_x; took: 0:00:00.000221
    DEBUG: Importing rule: composer_not_command; took: 0:00:00.000401
    DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000517
    DEBUG: Importing rule: cpp11; took: 0:00:00.000355
    DEBUG: Importing rule: dirty_untar; took: 0:00:00.000643
    DEBUG: Importing rule: dirty_unzip; took: 0:00:00.011152
    DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000379
    DEBUG: Importing rule: django_south_merge; took: 0:00:00.000237
    DEBUG: Importing rule: dnf_no_such_command; took: 0:00:00.001236
    DEBUG: Importing rule: docker_login; took: 0:00:00.000483
    DEBUG: Importing rule: docker_not_command; took: 0:00:00.001040
    DEBUG: Importing rule: dry; took: 0:00:00.000322
    DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000982
    DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000612
    DEBUG: Importing rule: fix_file; took: 0:00:00.003198
    DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.001027
    DEBUG: Importing rule: git_add; took: 0:00:00.001180
    DEBUG: Importing rule: git_add_force; took: 0:00:00.000555
    DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000751
    DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000557
    DEBUG: Importing rule: git_branch_exists; took: 0:00:00.000536
    DEBUG: Importing rule: git_branch_list; took: 0:00:00.000371
    DEBUG: Importing rule: git_checkout; took: 0:00:00.000519
    DEBUG: Importing rule: git_commit_amend; took: 0:00:00.000339
    DEBUG: Importing rule: git_commit_reset; took: 0:00:00.000334
    DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000397
    DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000358
    DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000458
    DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000436
    DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000374
    DEBUG: Importing rule: git_merge; took: 0:00:00.000395
    DEBUG: Importing rule: git_merge_unrelated; took: 0:00:00.000433
    DEBUG: Importing rule: git_not_command; took: 0:00:00.000418
    DEBUG: Importing rule: git_pull; took: 0:00:00.000617
    DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000624
    DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000611
    DEBUG: Importing rule: git_push; took: 0:00:00.000830
    DEBUG: Importing rule: git_push_different_branch_names; took: 0:00:00.000628
    DEBUG: Importing rule: git_push_force; took: 0:00:00.000623
    DEBUG: Importing rule: git_push_pull; took: 0:00:00.000665
    DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000563
    DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000640
    DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000439
    DEBUG: Importing rule: git_remote_delete; took: 0:00:00.000538
    DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000451
    DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000632
    DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000550
    DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000487
    DEBUG: Importing rule: git_stash; took: 0:00:00.000607
    DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000672
    DEBUG: Importing rule: git_tag_force; took: 0:00:00.000512
    DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000514
    DEBUG: Importing rule: go_run; took: 0:00:00.000461
    DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000815
    DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000468
    DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000706
    DEBUG: Importing rule: grep_recursive; took: 0:00:00.000778
    DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000784
    DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000476
    DEBUG: Importing rule: has_exists_script; took: 0:00:00.000380
    DEBUG: Importing rule: heroku_multiple_apps; took: 0:00:00.000395
    DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000389
    DEBUG: Importing rule: history; took: 0:00:00.000217
    DEBUG: Importing rule: hostscli; took: 0:00:00.000759
    DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000760
    DEBUG: Importing rule: java; took: 0:00:00.000972
    DEBUG: Importing rule: javac; took: 0:00:00.000592
    DEBUG: Importing rule: lein_not_task; took: 0:00:00.000591
    DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000373
    DEBUG: Importing rule: ln_s_order; took: 0:00:00.000432
    DEBUG: Importing rule: long_form_help; took: 0:00:00.000244
    DEBUG: Importing rule: ls_all; took: 0:00:00.000350
    DEBUG: Importing rule: ls_lah; took: 0:00:00.000354
    DEBUG: Importing rule: man; took: 0:00:00.000440
    DEBUG: Importing rule: man_no_space; took: 0:00:00.000200
    DEBUG: Importing rule: mercurial; took: 0:00:00.000456
    DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000266
    DEBUG: Importing rule: mkdir_p; took: 0:00:00.000463
    DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000366
    DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000458
    DEBUG: Importing rule: nixos_cmd_not_found; took: 0:00:00.000662
    DEBUG: Importing rule: no_command; took: 0:00:00.000533
    DEBUG: Importing rule: no_such_file; took: 0:00:00.000273
    DEBUG: Importing rule: npm_missing_script; took: 0:00:00.000879
    DEBUG: Importing rule: npm_run_script; took: 0:00:00.000433
    DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000681
    DEBUG: Importing rule: open; took: 0:00:00.000568
    DEBUG: Importing rule: pacman; took: 0:00:00.000851
    DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000367
    DEBUG: Importing rule: path_from_history; took: 0:00:00.000638
    DEBUG: Importing rule: php_s; took: 0:00:00.000671
    DEBUG: Importing rule: pip_install; took: 0:00:00.000712
    DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000793
    DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000732
    DEBUG: Importing rule: prove_recursively; took: 0:00:00.001113
    DEBUG: Importing rule: pyenv_no_such_command; took: 0:00:00.002060
    DEBUG: Importing rule: python_command; took: 0:00:00.000542
    DEBUG: Importing rule: python_execute; took: 0:00:00.000445
    DEBUG: Importing rule: quotation_marks; took: 0:00:00.000253
    DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.000745
    DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000285
    DEBUG: Importing rule: rm_dir; took: 0:00:00.000508
    DEBUG: Importing rule: rm_root; took: 0:00:00.000497
    DEBUG: Importing rule: scm_correction; took: 0:00:00.000608
    DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000596
    DEBUG: Importing rule: sl_ls; took: 0:00:00.000238
    DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000599
    DEBUG: Importing rule: sudo; took: 0:00:00.000349
    DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000549
    DEBUG: Importing rule: switch_lang; took: 0:00:00.001050
    DEBUG: Importing rule: systemctl; took: 0:00:00.000676
    DEBUG: Importing rule: terraform_init; took: 0:00:00.000388
    DEBUG: Importing rule: test.py; took: 0:00:00.000193
    DEBUG: Importing rule: tmux; took: 0:00:00.000464
    DEBUG: Importing rule: touch; took: 0:00:00.000474
    DEBUG: Importing rule: tsuru_login; took: 0:00:00.000378
    DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000397
    DEBUG: Importing rule: unknown_command; took: 0:00:00.000236
    DEBUG: Importing rule: unsudo; took: 0:00:00.000218
    DEBUG: Importing rule: vagrant_up; took: 0:00:00.000440
    DEBUG: Importing rule: whois; took: 0:00:00.000643
    DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000885
    DEBUG: Importing rule: yarn_alias; took: 0:00:00.000719
    DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000923
    DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000467
    DEBUG: Importing rule: yarn_help; took: 0:00:00.000392
    DEBUG: Trying rule: path_from_history; took: 0:00:00.000369
    DEBUG: Trying rule: dry; took: 0:00:00.000065
    DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000024
    DEBUG: Trying rule: test.py; took: 0:00:00.000005
    DEBUG: Trying rule: adb_unknown_command; took: 0:00:00.000017
    DEBUG: Trying rule: ag_literal; took: 0:00:00.000015
    DEBUG: Trying rule: apt_get_search; took: 0:00:00.000014
    DEBUG: Trying rule: apt_invalid_operation; took: 0:00:00.000036
    DEBUG: Trying rule: apt_list_upgradable; took: 0:00:00.000015
    DEBUG: Trying rule: apt_upgrade; took: 0:00:00.000013
    DEBUG: Trying rule: aws_cli; took: 0:00:00.000013
    DEBUG: Trying rule: az_cli; took: 0:00:00.000013
    DEBUG: Trying rule: brew_link; took: 0:00:00.000015
    DEBUG: Trying rule: brew_reinstall; took: 0:00:00.000012
    DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000012
    DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000012
    DEBUG: Trying rule: cargo; took: 0:00:00.000004
    DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000014
    DEBUG: Trying rule: cat_dir; took: 0:00:00.000013
    DEBUG: Trying rule: cd_correction; took: 0:00:00.000014
    DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000012
    DEBUG: Trying rule: cd_parent; took: 0:00:00.000006
    DEBUG: Trying rule: chmod_x; took: 0:00:00.000005
    DEBUG: Trying rule: composer_not_command; took: 0:00:00.000013
    DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000014
    DEBUG: Trying rule: cpp11; took: 0:00:00.000015
    DEBUG: Trying rule: dirty_untar; took: 0:00:00.000013
    DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000013
    DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000005
    DEBUG: Trying rule: django_south_merge; took: 0:00:00.000005
    DEBUG: Trying rule: docker_login; took: 0:00:00.000013
    DEBUG: Trying rule: docker_not_command; took: 0:00:00.000012
    DEBUG: Trying rule: fab_command_not_found; took: 0:00:00.000012
    DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000006
    DEBUG: Trying rule: fix_file; took: 0:00:00.000050
    DEBUG: Trying rule: gem_unknown_command; took: 0:00:00.000015
    DEBUG: Trying rule: git_add; took: 0:00:00.000014
    DEBUG: Trying rule: git_add_force; took: 0:00:00.000013
    DEBUG: Trying rule: git_bisect_usage; took: 0:00:00.000013
    DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000012
    DEBUG: Trying rule: git_branch_exists; took: 0:00:00.000012
    git branch -d list && git branch list [enter/↑/↓/ctrl+c]
    DEBUG: PYTHONIOENCODING: utf-8
    DEBUG: Total took: 0:00:01.970486
    Deleted branch list (was 6502806).

If the bug only appears with a specific application, the output of that application and its version:

    $ git version
    git version 2.17.1

Anything else you think is relevant:

    I have `hub` installed, but the behaviour was the same with and without the `hub` alias set.
    Deleting rules/git_branch_exists.py causes `thefuck git branch list` to work correctly. The @eager decorator in git_branch_exists.py might be the culprit?

**Comment by cjmartian** [comment]
@dwurf  If I'm understanding this correctly, are you wanting something like:
`git branch list #creates the branch 'list'`
`fuck #deletes the branch list`
`git branch #list should not be present`

**Comment by dwurf** [comment]
@cjmartian yes, and based on my reading of the code I think that is what it's trying to do:

https://github.com/nvbn/thefuck/blob/master/thefuck/rules/git_branch_list.py

So I'm expecting the trace to show this:

    git branch -d list && git branch

when it actually shows this:

    git branch -d list && git branch list

I tried tracing the code, and it seems like the linked code in `git_branch_list.py` never gets run. My suspicion is that this code is being run instead https://github.com/nvbn/thefuck/blob/master/thefuck/rules/git_branch_exists.py

**Comment by scorphus** [comment]
Both rules are doing what expected.

`git_branch_exists` is returning five suggestions:

* `git branch -d list; and git branch list`
* `git branch -d list; and git checkout -b list`
* `git branch -D list; and git branch list`
* `git branch -D list; and git checkout -b list`
* `git checkout list`

`git_branch_list` is returning one:

* `git branch --delete list; and git branch`

All of those six suggestions are offered in that order. If you'd like to have `git_branch_list`'s suggested first, give it a slightly lower priority:

```python
# ~/.config/thefuck/settings.py
priority = {
    "git_branch_list": 999
}
```
You can read more about settings [here](https://github.com/nvbn/thefuck#settings).

I'm closing this issue for now.

**Comment by dwurf** [comment]
Works for me :+1:
