### ISSUE TITLE
How can I debug thefuck using IDE?

### ISSUE THREAD

**Issue by ik1ne** [nvbn/thefuck#932]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.29 using Python 3.7.4 and ZSH 5.3

Your system (Debian 7, ArchLinux, Windows, etc.):

    OSX Mojave, 10.14.5 (18F203)

How to reproduce the bug:

    Not a bug, below sections are deleted for that reason.

---
Hi, I was surprised that golang hasn't been added to _thefuck_ so decided to add it and open a PR ny myself.

As an introductory step I'm planning to basically copypaste another ruleset&testcase and start from there. However, I can't figure out how to inspect a variable. I often times put a breakpoint, pause the program, inspect the variable and its methods to get used to source code.

I finally found a way: `logger.debug(command)` and `thefuck --debug` to read the console log, but that doesn't tell me call stacks, the method I can use with `command`, etc.

So, is there a way to debug _thefuck_ using IDE or, at least, manually call _thefuck_ from cli?

**Comment by scorphus** [comment]
Hi! Glad to know you're willing to contribute.

You can debug on the terminal. To add a breakpoint you can use the `pdb`, a package from the standard library. Or `ipdb`, a third party package a bit more friendly than `pdb`. You can install `ipdb` with pip: `pip install ipdb`.

To create a breakpoint you first import it – i.e. `import ipdb` – and then add `ipdb.set_trace()` to the line you'd like to stop at. For example:

```python
import ipdb


def fib(n):
    a1, a2 = 0, 1
    for _ in range(1, n):
        ipdb.set_trace()  # BREAKPOINT
        a1, a2 = a2, a1 + a2
    return a1
```

Once the execution stops at the breakpoint, you can enter `?` to show the available commands:

```
In [9]: fib(9)
> <ipython-input-5-b5a3a0041c90>(5)fib()
      4         ipdb.set_trace()  # BREAKPOINT
----> 5         a1, a2 = a2, a1 + a2
      6     return a1

ipdb> ?

Documented commands (type help <topic>):
========================================
EOF    cl         disable  interact  next    psource  rv         unt   
a      clear      display  j         p       q        s          until 
alias  commands   down     jump      pdef    quit     source     up    
args   condition  enable   l         pdoc    r        step       w     
b      cont       exit     list      pfile   restart  tbreak     whatis
break  continue   h        ll        pinfo   return   u          where 
bt     d          help     longlist  pinfo2  retval   unalias  
c      debug      ignore   n         pp      run      undisplay

Miscellaneous help topics:
==========================
exec  pdb

ipdb> a2                                                                            
3
ipdb>
```

To manually call TheFuck:

```bash
$ thefuck echoo ok
```

To create a new rule, you can also start with and test and progress from that.

Let me know if you need any further help.

Looking forward to your PR!

**Comment by ik1ne** [comment]
Thanks for the reply, the cli command you provided was really helpful for setting up TheFuck debugging environment on PyCharm.
I was able to setup debug configuration in pycharm like this:
```
Script Path: /.../thefuck/.env/bin/thefuck
Parameter: echoo ok
Execution: Check "Emulate terminal in output code"
```
