### ISSUE TITLE
git push not working with thefuck

### ISSUE THREAD

**Issue by bcullman** [nvbn/thefuck#949]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

`The Fuck 3.29 using Python 3.7.4 and Bash 3.2.57(1)-release`

Your system (Debian 7, ArchLinux, Windows, etc.):

 `MacOS`

How to reproduce the bug:

```
> git push

fatal: The current branch fck/test has no upstream branch.
To push the current branch and set the remote as upstream, use

git push --set-upstream origin fck/test

> fuck
.. .completed. [enter/↑/↓/ctrl+c]
```

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

`Debug flag has no affect.`

If the bug only appears with a specific application, the output of that application and its version:

**Comment by schneekatze** [comment]
Similar issue 

```» fuck
alias git="LANG="en_US.UTF-8" git" [enter/↑/↓/ctrl+c]```

**Comment by scorphus** [comment]
I couldn't reproduce this issue, unfortunately. Could you please provide the version of Git being used? Also, could you please update TheFuck to the latest version and try again? A few points more:

* Debugging information (outputted with `THEFUCK_DEBUG=true`) may be useful to better understand your issue. Please provide it too.
* TheFuck tells that you have Bash version 3.2.57. Maybe – and hopefully – you're using a newer release and TheFuck has the wrong one (in PATH).

Thanks!

**Comment by bcullman** [comment]
not sure what has happened, but this is working with the latest now. 

```
> thefuck --version
The Fuck 3.30 using Python 3.8.2 and Bash 3.2.57(1)-release
```

can close the issue.
