### ISSUE TITLE
First call fails with "nothing found", second succeeds (same command)

### ISSUE THREAD

**Issue by riley-martine** [nvbn/thefuck#971]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    ﻿The Fuck 3.29 using Python 3.7.4 and ZSH 5.3

Your system (Debian 7, ArchLinux, Windows, etc.):

    MacOS Mojave Version 10.14.6 (Tmux, iterm2)

How to reproduce the bug:

    I cannot consistently reproduce this bug.

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

   See above

If the bug only appears with a specific application, the output of that application and its version:

   iTerm2 Build 3.3.6

Anything else you think is relevant:
[image with output example](https://imgur.com/a/XpYibcA)

**Comment by scorphus** [comment]
Closing for the lack of reproducibility info.
