### ISSUE TITLE
What command line interpreter used for rules

### ISSUE THREAD

**Issue by ncrocfer** [nvbn/thefuck#98]
Hello,

I want to create a new rule based on the `cd` command, but I noticed that the returned error is not the same when I use bash or sh.

With bash :
```
$ cd foo
bash: cd: foo: No such file or directory
```
With sh :
```
$ cd foo
sh: 1: cd: can't cd to foo
```

And when I print `command.stderr` in the `match()` function, the stderr is the sh style. So my question is : when we create a new rule, should we use this stderr style to test errors?

Thank you :smiley:

**Comment by nwinkler** [comment]
Looks like #50...

**Comment by nvbn** [comment]
Python uses `/bin/sh` as a shell for `subprocess.Popen` and related functions.
We should use output from `/bin/sh`.

**Comment by ncrocfer** [comment]
Ok, thanks !
My rule is the same as #50, so I'm waiting his PR rather than sending mine.
